evio: evio::evioChannelBufferizable Class Reference
evio::evioChannelBufferizable Class Reference abstract
Pure virtual class defines single method that implements serialization of object to evio buffer.
#include <evioChannel.hxx>
Public Member Functions
virtual int toEVIOBuffer (uint32_t *buf, int size) const =0
virtual ~evioChannelBufferizable ()
Detailed Description
Pure virtual class defines single method that implements serialization of object to evio buffer.
Constructor & Destructor Documentation
~evioChannelBufferizable()
virtual evio::evioChannelBufferizable::~evioChannelBufferizable () inline virtual
Member Function Documentation
toEVIOBuffer()
virtual int evio::evioChannelBufferizable::toEVIOBuffer (uint32_t * buf, int size) const pure virtual
Implemented in evio::evioDOMTree.
Referenced by evio::evioBufferChannel::write(), evio::evioFileChannel::write(), and evio::evioSocketChannel::write().
The documentation for this class was generated from the following file:
evioChannel.hxx