# scons build file for evio
Import('env', 'platform', 'archDir', 'incInstallDir', 'libInstallDir', 'binInstallDir', 'archIncInstallDir', 'execLibs', 'debugSuffix', 'disruptorHome')

# Headers to install
headerList = Glob('*.h', strings=True)

# Files to compile
#fileList = Glob('*.cpp',  strings=True, exclude=['ReadWriteTest.cpp', 'EventWriter.cpp', 'EventWriter.h'])
fileList = Glob('*.cpp',  strings=True, exclude=['ReadWriteTest.cpp'])

env.AppendUnique(CPPPATH = ['/usr/local/include', '/usr/include/boost', '/usr/local/include/boost'])

# Compile C++ files and install

boostThdLib = 'boost_thread'
if platform == 'Darwin':
    boostThdLib = 'boost_thread-mt'

compiledFile1 = env.Program(source  = 'ReadWriteTest.cpp',
                           LIBS    = ['boost_system', boostThdLib,  'boost_chrono',  execLibs],
                           LIBPATH = ['/usr/local/lib'],
                           CPPPATH = ['/usr/local/include',
                                      '/usr/include/boost', '/usr/local/include/boost'])


if 'install' in COMMAND_LINE_TARGETS:
    env.Alias('install', env.Install(target = binInstallDir, source = [compiledFile1]))
