/*
 * This file was generated by the Gradle 'init' task.
 *
 * Copyright (c) 2025.  Jefferson Lab (JLab). All rights reserved. Permission
 * to use, copy, modify, and distribute  this software and its documentation for
 * educational, research, and not-for-profit purposes, without fee and without a
 * signed licensing agreement.
 *
 * IN NO EVENT SHALL JLAB BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL
 * INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING
 * OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF JLAB HAS
 * BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * JLAB SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE. THE CLARA SOFTWARE AND ACCOMPANYING DOCUMENTATION, IF ANY,
 * PROVIDED HEREUNDER IS PROVIDED "AS IS". JLAB HAS NO OBLIGATION TO PROVIDE
 * MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 * This software was developed under the United States Government license.
 * For more information contact maintainer at jzarling@jlab.org
 * Department of Experimental Nuclear Physics, Jefferson Lab.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    // `com.github.spotbugs`
    id("com.gradleup.shadow") version "9.2.2"
}

java {
    toolchain { languageVersion.set(JavaLanguageVersion.of(17)) }
    withJavadocJar()
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.lz4.lz4.java)
    api(files("$projectDir/java/jars/disruptor-4.0.0.jar")) 
    testImplementation(platform("org.junit:junit-bom:5.10.3")) // Makes sure JUnit dependencies below have matching versions
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    }

group = "org.jlab.coda"
version = "6.2.0"
description = "Jefferson Lab EVIO Java Library (JEVIO)"
defaultTasks("build")

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.test {
  useJUnitPlatform()
  failOnNoDiscoveredTests = false
}

// spotbugs {
//     toolVersion.set("4.7.3")
//     effort.set(com.github.spotbugs.snom.Effort.MAX)
//     reportLevel.set(com.github.spotbugs.snom.ReportLevel.LOW)
//     excludeFilter.set(file("config/spotbugs/exclude.xml"))
// }
