/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    // `com.github.spotbugs`
    id("com.gradleup.shadow") version "9.2.2"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.lz4.lz4.java)
    api(files("$projectDir/java/jars/disruptor-4.0.0.jar")) 
    testImplementation(platform("org.junit:junit-bom:5.10.3")) // Makes sure JUnit dependencies below have matching versions
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    }

group = "org.jlab.coda"
version = "6.2.0"
description = "Jefferson Lab EVIO Java Library (JEVIO)"
java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17

defaultTasks("build")

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.test {
  useJUnitPlatform()
  failOnNoDiscoveredTests = false
}

// spotbugs {
//     toolVersion.set("4.7.3")
//     effort.set(com.github.spotbugs.snom.Effort.MAX)
//     reportLevel.set(com.github.spotbugs.snom.ReportLevel.LOW)
//     excludeFilter.set(file("config/spotbugs/exclude.xml"))
// }
