evio: evio::evioChannel Class Reference
evio::evioChannel Class Reference abstract
Defines EVIO I/O channel functionality.
#include <evioChannel.hxx>
Public Member Functions
evioChannel ()
evioChannel (evioDictionary *dict)
virtual ~evioChannel ()
virtual void open ()=0
virtual bool read ()=0
virtual bool read (uint32_t *myBuf, int length)=0
virtual bool readAlloc (uint32_t **buffer, uint32_t *bufLen)=0
virtual bool readNoCopy ()=0
virtual bool readRandom (uint32_t eventNumber)
virtual void write ()=0
virtual void write (const uint32_t *myBuf)=0
virtual void write (const evioChannel &channel)=0
virtual void write (const evioChannel *channel)=0
virtual void write (const evioChannelBufferizable &o)=0
virtual void write (const evioChannelBufferizable *o)=0
virtual void close ()=0
virtual int ioctl (const string &request, void *argp)=0
virtual const evioDictionary * getDictionary () const
virtual const uint32_t * getBuffer () const =0
virtual int getBufSize () const =0
virtual const uint32_t * getNoCopyBuffer () const =0
virtual const uint32_t * getRandomBuffer () const
virtual void getRandomAccessTable (uint32_t ***const table, uint32_t *len) const
Protected Attributes
evioDictionary * dictionary
Detailed Description
Defines EVIO I/O channel functionality.
Sub-class gets channel-specific info from constructor and implements evioChannel methods.
Some default methods throw unsupported feature exception.
Users should be able to program to this interface.
Constructor & Destructor Documentation
evioChannel() [1/2]
evio::evioChannel::evioChannel () inline
evioChannel() [2/2]
evio::evioChannel::evioChannel (evioDictionary * dict) inline
~evioChannel()
virtual evio::evioChannel::~evioChannel () inline virtual
Member Function Documentation
close()
virtual void evio::evioChannel::close () pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
getBuffer()
virtual const uint32_t* evio::evioChannel::getBuffer () const pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
Referenced by evio::evioDOMTree::evioDOMTree(), evio::evioBufferChannel::write(), evio::evioFileChannel::write(), and evio::evioSocketChannel::write().
getBufSize()
virtual int evio::evioChannel::getBufSize () const pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
getDictionary()
virtual const evioDictionary* evio::evioChannel::getDictionary () const inline virtual
Referenced by evio::evioDOMTree::evioDOMTree().
getNoCopyBuffer()
virtual const uint32_t* evio::evioChannel::getNoCopyBuffer () const pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
Referenced by evio::evioDOMTree::evioDOMTree().
getRandomAccessTable()
virtual void evio::evioChannel::getRandomAccessTable (uint32_t ***const table, uint32_t * len) const inline virtual
Reimplemented in evio::evioFileChannel, and evio::evioBufferChannel.
getRandomBuffer()
virtual const uint32_t* evio::evioChannel::getRandomBuffer () const inline virtual
Reimplemented in evio::evioFileChannel, and evio::evioBufferChannel.
Referenced by evio::evioDOMTree::evioDOMTree().
ioctl()
virtual int evio::evioChannel::ioctl (const string & request, void * argp) pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
open()
virtual void evio::evioChannel::open () pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
read() [1/2]
virtual bool evio::evioChannel::read () pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
read() [2/2]
virtual bool evio::evioChannel::read (uint32_t * myBuf, int length) pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
readAlloc()
virtual bool evio::evioChannel::readAlloc (uint32_t ** buffer, uint32_t * bufLen) pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
readNoCopy()
virtual bool evio::evioChannel::readNoCopy () pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
readRandom()
virtual bool evio::evioChannel::readRandom (uint32_t eventNumber) inline virtual
Reimplemented in evio::evioFileChannel, and evio::evioBufferChannel.
write() [1/6]
virtual void evio::evioChannel::write () pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
write() [2/6]
virtual void evio::evioChannel::write (const evioChannel & channel) pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
write() [3/6]
virtual void evio::evioChannel::write (const evioChannel * channel) pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
write() [4/6]
virtual void evio::evioChannel::write (const evioChannelBufferizable & o) pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
write() [5/6]
virtual void evio::evioChannel::write (const evioChannelBufferizable * o) pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
write() [6/6]
virtual void evio::evioChannel::write (const uint32_t * myBuf) pure virtual
Implemented in evio::evioSocketChannel, evio::evioFileChannel, and evio::evioBufferChannel.
Member Data Documentation
dictionary
evioDictionary* evio::evioChannel::dictionary protected
Referenced by evio::evioBufferChannel::open(), evio::evioFileChannel::open(), evio::evioSocketChannel::open(), evio::evioBufferChannel::~evioBufferChannel(), evio::evioFileChannel::~evioFileChannel(), and evio::evioSocketChannel::~evioSocketChannel().
The documentation for this class was generated from the following file:
evioChannel.hxx