evio: evio::StructureType Class Reference
evio::StructureType Class Reference
Numerical values associated with evio structure types.
#include <StructureType.h>
Public Member Functions
const std::string & getName () const
Get the name associated with this structure type.
uint32_t getValue () const
Get the integer value associated with this structure type.
std::string toString ()
Return a string which is usually the same as the name of the enumerated value, except in the cases of ALSOSEGMENT and ALSOBANK which return SEGMENT and BANK respectively.
bool isBank ()
Convenience routine to see if "this" structure type is a bank structure.
bool isSegment ()
Convenience routine to see if "this" structure type is a segment structure.
bool isTagSegment ()
Convenience routine to see if "this" structure type is a tagsegment structure.
bool operator== (const StructureType &rhs) const
bool operator!= (const StructureType &rhs) const
Static Public Member Functions
static const StructureType & getStructureType (uint32_t val)
Get the object from the integer value.
static std::string getName (uint32_t val)
Get the name from the integer value.
static bool isBank (uint32_t type)
Convenience method to see if the given integer arg represents a BANK.
static bool isSegment (uint32_t type)
Convenience method to see if the given integer arg represents a SEGMENT.
static bool isTagSegment (uint32_t type)
Convenience method to see if the given integer arg represents a TAGSEGMENT.
Static Public Attributes
static const StructureType STRUCT_UNKNOWN32 = StructureType("UNKNOWN32", 0)
Unknown data type.
static const StructureType STRUCT_TAGSEGMENT = StructureType("TAGSEGMENT", 0xc)
Tag segment.
static const StructureType STRUCT_SEGMENT = StructureType("SEGMENT", 0x20, 0xd)
Segment.
static const StructureType STRUCT_BANK = StructureType("BANK", 0x10, 0xe)
Bank.
Detailed Description
Numerical values associated with evio structure types.
This class approximates the Java enum it was copied from. This class converts structure type numerical values to a more meaningful name. For example, the structure type with value 0xe corresponds to a BANK. This is mostly used for printing.
Author
heddle
timmer
Version
6.0
Since
6.0 4/13/2020
Member Function Documentation
getName() [1/2]
const std::string& evio::StructureType::getName () const inline
Get the name associated with this structure type.
Returns
name associated with this structure type.
getName() [2/2]
static std::string evio::StructureType::getName (uint32_t val) inline static
Get the name from the integer value.
Parameters
val the value to match.
Returns
the name, or null.
References getStructureType().
getStructureType()
static const StructureType& evio::StructureType::getStructureType (uint32_t val) inline static
Get the object from the integer value.
Parameters
val the value to match.
Returns
the matching StructureType object.
References STRUCT_UNKNOWN32.
Referenced by getName().
getValue()
uint32_t evio::StructureType::getValue () const inline
Get the integer value associated with this structure type.
Returns
integer value associated with this structure type.
isBank() [1/2]
bool evio::StructureType::isBank () inline
Convenience routine to see if "this" structure type is a bank structure.
Returns
true if this structure type corresponds to a bank structure.
References STRUCT_BANK.
isBank() [2/2]
static bool evio::StructureType::isBank (uint32_t type) inline static
Convenience method to see if the given integer arg represents a BANK.
Parameters
type the int value to match.
Returns
true if the structure type corresponds to a BANK.
References STRUCT_BANK.
isSegment() [1/2]
bool evio::StructureType::isSegment () inline
Convenience routine to see if "this" structure type is a segment structure.
Returns
true if this structure type corresponds to a segment structure.
References STRUCT_SEGMENT.
isSegment() [2/2]
static bool evio::StructureType::isSegment (uint32_t type) inline static
Convenience method to see if the given integer arg represents a SEGMENT.
Parameters
type the int value to match.
Returns
true if the structure type corresponds to a SEGMENT.
References STRUCT_SEGMENT.
isTagSegment() [1/2]
bool evio::StructureType::isTagSegment () inline
Convenience routine to see if "this" structure type is a tagsegment structure.
Returns
true if this structure type corresponds to a tagsegment structure.
References STRUCT_TAGSEGMENT.
isTagSegment() [2/2]
static bool evio::StructureType::isTagSegment (uint32_t type) inline static
Convenience method to see if the given integer arg represents a TAGSEGMENT.
Parameters
type the int value to match.
Returns
true if the structure type corresponds to a TAGSEGMENT.
References STRUCT_TAGSEGMENT.
operator!=()
bool evio::StructureType::operator!= (const StructureType & rhs) const
operator==()
bool evio::StructureType::operator== (const StructureType & rhs) const
toString()
std::string evio::StructureType::toString () inline
Return a string which is usually the same as the name of the enumerated value, except in the cases of ALSOSEGMENT and ALSOBANK which return SEGMENT and BANK respectively.
Returns
name of the enumerated type
Referenced by evio::BaseStructure::toString().
Member Data Documentation
STRUCT_BANK
const StructureType evio::StructureType::STRUCT_BANK = StructureType("BANK", 0x10, 0xe) static
Bank.
Referenced by evio::EventBuilder::addChild(), evio::StructureFinder::getMatchingBanks(), evio::StructureFinder::getMatchingNonBanks(), evio::EvioBank::getStructureType(), isBank(), evio::BaseStructure::toString(), and evio::EvioEvent::toString().
STRUCT_SEGMENT
const StructureType evio::StructureType::STRUCT_SEGMENT = StructureType("SEGMENT", 0x20, 0xd) static
Segment.
Referenced by evio::EventBuilder::addChild(), evio::EvioSegment::getStructureType(), and isSegment().
STRUCT_TAGSEGMENT
const StructureType evio::StructureType::STRUCT_TAGSEGMENT = StructureType("TAGSEGMENT", 0xc) static
Tag segment.
Referenced by evio::EventBuilder::addChild(), evio::EvioTagSegment::getStructureType(), and isTagSegment().
STRUCT_UNKNOWN32
const StructureType evio::StructureType::STRUCT_UNKNOWN32 = StructureType("UNKNOWN32", 0) static
Unknown data type.
Referenced by getStructureType().
The documentation for this class was generated from the following files:
StructureType.h
StructureType.cpp