evio: evio::FileEventIndex Class Reference
evio::FileEventIndex Class Reference
Class used to handle event indexes in the context of a file (or buffer) and having to change records.
#include <FileEventIndex.h>
Public Member Functions
FileEventIndex ()=default
Constructor.
void clear ()
Clear the entire object.
void resetIndex ()
Resets the current index to 0.
void show ()
Prints the content of the event index array on the screen.
void addEventSize (uint32_t size)
Adds the number of events in the next record to the index of records.
uint32_t getEventNumber () const
Gets the current event number which is set by advance(), retreat() or setEvent(uint32_t) (which also sets the record number that the event belongs to).
uint32_t getRecordNumber () const
Gets the current record number which is set by setEvent(uint32_t), or by using advance() or retreat() (which set the event number to the next available or previous available respectively).
uint32_t getRecordEventNumber () const
Gets the event number inside the record that corresponds to the current global event number from the file.
uint32_t getMaxEvents () const
Gets the total number of events in file.
bool canAdvance () const
Checks to see if the event counter reached the end.
bool canRetreat () const
Checks if the event index can retreat (decrease).
bool advance ()
Advances the current event number by one.
bool retreat ()
Reduces current event number by one.
bool setEvent (uint32_t event)
Set the current event to the desired position.
std::string toString ()
Get a string representation of this object.
int main (int argc, char **argv)
Detailed Description
Class used to handle event indexes in the context of a file (or buffer) and having to change records.
Date
09/25/2019
Author
gavalian (original java)
timmer
Constructor & Destructor Documentation
FileEventIndex()
evio::FileEventIndex::FileEventIndex () default
Constructor.
Member Function Documentation
addEventSize()
void evio::FileEventIndex::addEventSize (uint32_t size)
Adds the number of events in the next record to the index of records.
Internally, what is stored is the total number of events in the file up to and including the record of this entry.
Parameters
size number of events in the next record.
Referenced by evio::Reader::forceScanFile(), main(), evio::Reader::scanBuffer(), evio::Reader::scanFile(), and evio::Reader::scanUncompressedBuffer().
advance()
bool evio::FileEventIndex::advance ()
Advances the current event number by one.
If the event is not from current record, the record number will also be changed. If calling this would advance the current event number beyond its maximum limit, nothing is done.
Returns
false if the record number is the same, and true if the record number has changed.
Referenced by main().
canAdvance()
bool evio::FileEventIndex::canAdvance () const
Checks to see if the event counter reached the end.
Returns
true if there are more events to advance to, false otherwise.
References getMaxEvents().
Referenced by evio::Reader::hasNext().
canRetreat()
bool evio::FileEventIndex::canRetreat () const
Checks if the event index can retreat (decrease).
Convenience function.
Returns
true if the event index can be lowered by one.
Referenced by evio::Reader::hasPrev().
clear()
void evio::FileEventIndex::clear ()
Clear the entire object.
Referenced by evio::Reader::forceScanFile(), evio::Reader::scanBuffer(), evio::Reader::scanFile(), evio::Reader::scanUncompressedBuffer(), and evio::Reader::setBuffer().
getEventNumber()
uint32_t evio::FileEventIndex::getEventNumber () const
Gets the current event number which is set by advance(), retreat() or setEvent(uint32_t) (which also sets the record number that the event belongs to).
Returns
current event number.
getMaxEvents()
uint32_t evio::FileEventIndex::getMaxEvents () const
Gets the total number of events in file.
Returns
returns the number of events corresponding to the all records.
Referenced by canAdvance(), evio::Reader::getEvent(), evio::Reader::getEventCount(), evio::Reader::getEventLength(), evio::Reader::getEventNode(), evio::Reader::getNextEventNode(), evio::Reader::getNumEventsRemaining(), setEvent(), show(), and toString().
getRecordEventNumber()
uint32_t evio::FileEventIndex::getRecordEventNumber () const
Gets the event number inside the record that corresponds to the current global event number from the file.
Returns
event offset in the record.
Referenced by evio::Reader::getEvent(), and evio::Reader::getEventLength().
getRecordNumber()
uint32_t evio::FileEventIndex::getRecordNumber () const
Gets the current record number which is set by setEvent(uint32_t), or by using advance() or retreat() (which set the event number to the next available or previous available respectively).
Returns
current record number.
Referenced by evio::Reader::getEvent(), and evio::Reader::getEventLength().
main()
int evio::FileEventIndex::main (int argc, char ** argv)
References addEventSize(), advance(), retreat(), setEvent(), show(), and toString().
resetIndex()
void evio::FileEventIndex::resetIndex ()
Resets the current index to 0.
The corresponding record number is recalculated by calling the setEvent(uint32_t) method.
References setEvent().
retreat()
bool evio::FileEventIndex::retreat ()
Reduces current event number by one.
If the record number changes, it returns true.
Returns
false if the record number is the same, and true is the record number has changed.
Referenced by main().
setEvent()
bool evio::FileEventIndex::setEvent (uint32_t event)
Set the current event to the desired position.
The current record and event offset inside of the record are updated as well.
Parameters
event event number in the stream, must be 0 to getMaxEvents()-1.
Returns
true if record is different from previous one, false if it is the same.
References getMaxEvents().
Referenced by evio::Reader::getEvent(), evio::Reader::getEventLength(), main(), and resetIndex().
show()
void evio::FileEventIndex::show ()
Prints the content of the event index array on the screen.
References getMaxEvents().
Referenced by main().
toString()
std::string evio::FileEventIndex::toString ()
Get a string representation of this object.
Returns
a string representation of this object.
References getMaxEvents().
Referenced by main().
The documentation for this class was generated from the following files:
FileEventIndex.h
FileEventIndex.cpp