evio: eviocopy.c File Reference
eviocopy.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include "evio.h"
Macros
#define _POSIX_C_SOURCE 200809L
#define MAXEVIOBUF 1000000
Functions
void decode_command_line (int argc, char **argv)
int user_event_select (unsigned int *buf)
int main (int argc, char **argv)
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
MAXEVIOBUF
#define MAXEVIOBUF 1000000
Function Documentation
decode_command_line()
void decode_command_line (int argc, char ** argv)
Referenced by main().
main()
int main (int argc, char ** argv)
References decode_command_line(), and evOpen().
user_event_select()
int user_event_select (unsigned int * buf)