evio: evio::DataType Class Reference
evio::DataType Class Reference
Numerical values associated with evio data types.
#include <DataType.h>
Public Member Functions
const std::string & getName () const
Get the name associated with this data type.
uint32_t getValue () const
Get the integer value associated with this data type.
std::string toString () const
Return a string which is usually the same as the name of the enumerated value, except in the cases of ALSOSEGMENT and ALSOBANK which return SEGMENT and BANK respectively.
bool isStructure () const
Convenience routine to see if "this" data type is a structure (a container.)
bool isBank () const
Convenience routine to see if "this" data type is a bank structure.
bool isSegment () const
Convenience routine to see if "this" data type is a segment structure.
bool isTagSegment () const
Convenience routine to see if "this" data type is a tagsegment structure.
bool isInteger () const
Convenience method to see if "this" data type is an integer of some kind - either 8, 16, 32, or 64 bits worth.
int getBytes () const
Return the number of bytes this data type takes (if relevant).
bool operator== (const DataType &rhs) const
bool operator!= (const DataType &rhs) const
Static Public Member Functions
static const DataType & getDataType (uint32_t val)
Get the object from the integer value.
static std::string getName (uint32_t val)
Get the name from the integer value.
static DataType valueOf (std::string const &typeName)
Get the enum constant from a string.
static bool isStructure (uint32_t dataType)
Convenience method to see if the given integer arg represents a data type which is a structure (a container).
static bool isBank (uint32_t dataType)
Convenience method to see if the given integer arg represents a BANK.
static bool isSegment (uint32_t dataType)
Convenience method to see if the given integer arg represents a SEGMENT.
static bool isTagSegment (uint32_t dataType)
Convenience method to see if the given integer arg represents a TAGSEGMENT.
Static Public Attributes
static const DataType UNKNOWN32 = DataType(0x0, "UNKNOWN32")
Unknown data type.
static const DataType UINT32 = DataType(0x1, "UINT32", 4)
Unsigned 32 bit int.
static const DataType FLOAT32 = DataType(0x2, "FLOAT32", 4)
32 bit float.
static const DataType CHARSTAR8 = DataType(0x3, "CHARSTAR8")
ASCII characters.
static const DataType SHORT16 = DataType(0x4, "SHORT16", 2)
16 bit int.
static const DataType USHORT16 = DataType(0x5, "USHORT16", 2)
Unsigned 16 bit int.
static const DataType CHAR8 = DataType(0x6, "CHAR8", 1)
8 bit int.
static const DataType UCHAR8 = DataType(0x7, "UCHAR8", 1)
Unsigned 8 bit int.
static const DataType DOUBLE64 = DataType(0x8, "DOUBLE64", 8)
64 bit double.
static const DataType LONG64 = DataType(0x9, "LONG64", 8)
64 bit int.
static const DataType ULONG64 = DataType(0xa, "ULONG64", 8)
Unsigned 64 bit int.
static const DataType INT32 = DataType(0xb, "INT32", 4)
32 bit int.
static const DataType TAGSEGMENT = DataType(0xc, "TAGSEGMENT")
Tag segment.
static const DataType ALSOSEGMENT = DataType(0xd, "ALSOSEGMENT")
Segment alternate value.
static const DataType ALSOBANK = DataType(0xe, "ALSOBANK")
Bank alternate value.
static const DataType COMPOSITE = DataType(0xf, "COMPOSITE")
Composite data type.
static const DataType BANK = DataType(0x10, "BANK")
Bank.
static const DataType SEGMENT = DataType(0x20, "SEGMENT")
Segment.
static const DataType HOLLERIT = DataType(0x21, "HOLLERIT")
In composite data, Hollerit type.
static const DataType NVALUE = DataType(0x22, "NVALUE")
In composite data, N value.
static const DataType nVALUE = DataType(0x23, "nVALUE")
In composite data, n value.
static const DataType mVALUE = DataType(0x24, "mVALUE")
In composite data, m value.
static const DataType NOT_A_VALID_TYPE = DataType(0x30, "INVALID")
Not a valid data type.
Detailed Description
Numerical values associated with evio data types.
This class approximates the Java enum it was copied from. ALSOTAGSEGMENT (0x40) value was removed from this class because the upper 2 bits of a byte containing the datatype are now used to store padding data.
Version
6.0
Since
6.0 7/22/2019
Author
timmer
Member Function Documentation
getBytes()
int evio::DataType::getBytes () const inline
Return the number of bytes this data type takes (if relevant).
Returns
the number of bytes this data type takes (if relevant).
Referenced by evio::BaseStructure::dataLength(), and evio::BaseStructure::getNumberDataItems().
getDataType()
static const DataType& evio::DataType::getDataType (uint32_t val) inline static
Get the object from the integer value.
Parameters
val the value to match.
Returns
the matching DataType object.
References UNKNOWN32.
Referenced by evio::EventBuilder::addChild(), evio::StructureTransformer::copy(), evio::EvioNode::getDataTypeObj(), evio::EvioXMLDictionary::getName(), getName(), evio::EvioNode::getTypeObj(), evio::BaseStructureHeader::setDataType(), evio::BaseStructure::transform(), and evio::StructureTransformer::transform().
getName() [1/2]
const std::string& evio::DataType::getName () const inline
Get the name associated with this data type.
Returns
name associated with this data type.
getName() [2/2]
static std::string evio::DataType::getName (uint32_t val) inline static
Get the name from the integer value.
Parameters
val the value to match.
Returns
the name, or null.
References getDataType().
Referenced by evio::EventBuilder::addChild(), and evio::BaseStructureHeader::getDataTypeName().
getValue()
uint32_t evio::DataType::getValue () const inline
Get the integer value associated with this data type.
Returns
integer value associated with this data type.
Referenced by evio::EvioNode::EvioNode(), evio::EvioNode::extractNode(), evio::BaseStructureHeader::getDataTypeValue(), evio::CompactEventBuilder::openBank(), evio::CompactEventBuilder::openSegment(), evio::CompactEventBuilder::openTagSegment(), evio::EvioNode::scanStructure(), evio::EvioNode::setData(), evio::BankHeader::write(), evio::SegmentHeader::write(), and evio::TagSegmentHeader::write().
isBank() [1/2]
bool evio::DataType::isBank () const inline
Convenience routine to see if "this" data type is a bank structure.
Returns
true if this data type corresponds to a bank structure.
References ALSOBANK, and BANK.
Referenced by evio::EvioNode::scanStructure().
isBank() [2/2]
static bool evio::DataType::isBank (uint32_t dataType) inline static
Convenience method to see if the given integer arg represents a BANK.
Parameters
dataType the int value to match.
Returns
true if the data type corresponds to a BANK.
References ALSOBANK, and BANK.
Referenced by evio::RecordOutput::addEvent(), and evio::EvioXMLDictionary::getName().
isInteger()
bool evio::DataType::isInteger () const inline
Convenience method to see if "this" data type is an integer of some kind - either 8, 16, 32, or 64 bits worth.
Returns
true if the data type corresponds to an integer type
References CHAR8, INT32, LONG64, SHORT16, UCHAR8, UINT32, ULONG64, and USHORT16.
isSegment() [1/2]
bool evio::DataType::isSegment () const inline
Convenience routine to see if "this" data type is a segment structure.
Returns
true if this data type corresponds to a bank structure.
References ALSOSEGMENT, and SEGMENT.
Referenced by evio::EvioNode::scanStructure().
isSegment() [2/2]
static bool evio::DataType::isSegment (uint32_t dataType) inline static
Convenience method to see if the given integer arg represents a SEGMENT.
Parameters
dataType the int value to match.
Returns
true if the data type corresponds to a SEGMENT.
References ALSOSEGMENT, and SEGMENT.
isStructure() [1/2]
bool evio::DataType::isStructure () const inline
Convenience routine to see if "this" data type is a structure (a container.)
Returns
true if the data type corresponds to one of the structure types: BANK, SEGMENT, TAGSEGMENT, ALSOBANK, or ALSOSEGMENT.
References ALSOBANK, ALSOSEGMENT, BANK, SEGMENT, and TAGSEGMENT.
Referenced by evio::EvioNode::scanStructure().
isStructure() [2/2]
static bool evio::DataType::isStructure (uint32_t dataType) inline static
Convenience method to see if the given integer arg represents a data type which is a structure (a container).
Parameters
dataType the int value to match.
Returns
true if the data type corresponds to one of the structure types: BANK, SEGMENT, TAGSEGMENT, ALSOBANK, or ALSOSEGMENT.
References ALSOBANK, ALSOSEGMENT, BANK, SEGMENT, and TAGSEGMENT.
Referenced by evio::EventBuilder::addChild(), and evio::BaseStructure::transform().
isTagSegment() [1/2]
bool evio::DataType::isTagSegment () const inline
Convenience routine to see if "this" data type is a tagsegment structure.
Returns
true if this data type corresponds to a tagsegment structure.
References TAGSEGMENT.
isTagSegment() [2/2]
static bool evio::DataType::isTagSegment (uint32_t dataType) inline static
Convenience method to see if the given integer arg represents a TAGSEGMENT.
Parameters
dataType the int value to match.
Returns
true if the data type corresponds to a TAGSEGMENT.
References TAGSEGMENT.
operator!=()
bool evio::DataType::operator!= (const DataType & rhs) const
operator==()
bool evio::DataType::operator== (const DataType & rhs) const
toString()
std::string evio::DataType::toString () const inline
Return a string which is usually the same as the name of the enumerated value, except in the cases of ALSOSEGMENT and ALSOBANK which return SEGMENT and BANK respectively.
Returns
name of the enumerated type
References ALSOBANK, and ALSOSEGMENT.
Referenced by evio::RecordOutput::addEvent(), evio::EvioNode::toString(), evio::BaseStructure::toString(), evio::EvioEvent::toString(), evio::BaseStructure::updateCharData(), evio::BaseStructure::updateCompositeData(), evio::BaseStructure::updateDoubleData(), evio::BaseStructure::updateFloatData(), evio::BaseStructure::updateIntData(), evio::BaseStructure::updateLongData(), evio::BaseStructure::updateShortData(), evio::BaseStructure::updateStringData(), evio::BaseStructure::updateUCharData(), evio::BaseStructure::updateUIntData(), evio::BaseStructure::updateULongData(), and evio::BaseStructure::updateUShortData().
valueOf()
static DataType evio::DataType::valueOf (std::string const & typeName) inline static
Get the enum constant from a string.
Parameters
typeName the name of the DataType to obtain.
Returns
the DataType object associated with the given type name, or DataType::UNKNOWN32 if there's no match.
References UNKNOWN32.
Referenced by evio::EvioXMLDictionary::parseXML().
Member Data Documentation
ALSOBANK
const DataType evio::DataType::ALSOBANK = DataType(0xe, "ALSOBANK") static
Bank alternate value.
Referenced by evio::EventBuilder::addChild(), evio::EvioCompactReaderV4::addStructure(), evio::StructureTransformer::copy(), evio::Util::getDataType(), isBank(), isStructure(), evio::CompactEventBuilder::openBank(), evio::EvioCompactReaderV4::removeStructure(), toString(), evio::StructureTransformer::transform(), evio::EvioNode::updateLengths(), evio::EvioNode::updateNum(), and evio::EvioNode::updateTag().
ALSOSEGMENT
const DataType evio::DataType::ALSOSEGMENT = DataType(0xd, "ALSOSEGMENT") static
Segment alternate value.
Referenced by evio::EventBuilder::addChild(), evio::EvioCompactReaderV4::addStructure(), evio::StructureTransformer::copy(), evio::Util::getDataType(), isSegment(), isStructure(), evio::CompactEventBuilder::openSegment(), evio::EvioCompactReaderV4::removeStructure(), toString(), evio::StructureTransformer::transform(), evio::EvioNode::updateLengths(), and evio::EvioNode::updateTag().
BANK
const DataType evio::DataType::BANK = DataType(0x10, "BANK") static
Bank.
Referenced by evio::EvioNode::EvioNode(), evio::EventBuilder::addChild(), evio::EvioCompactReaderV4::addStructure(), evio::StructureTransformer::copy(), evio::EvioNode::extractNode(), isBank(), isStructure(), evio::EventBuilder::main(), evio::CompactEventBuilder::openBank(), evio::EvioCompactReaderV4::removeStructure(), evio::EvioNode::scanStructure(), evio::EvioNode::setData(), evio::StructureTransformer::transform(), evio::EvioNode::updateLengths(), evio::EvioNode::updateNum(), and evio::EvioNode::updateTag().
CHAR8
const DataType evio::DataType::CHAR8 = DataType(0x6, "CHAR8", 1) static
8 bit int.
Referenced by evio::CompactEventBuilder::addByteData(), evio::CompositeData::Data::addChar(), evio::EventBuilder::appendCharData(), evio::BaseStructure::dataLength(), evio::BaseStructure::getCharData(), evio::Util::getDataType(), isInteger(), evio::EventBuilder::setCharData(), evio::EvioSwap::swapLeafData(), evio::BaseStructure::updateCharData(), and evio::BaseStructure::write().
CHARSTAR8
const DataType evio::DataType::CHARSTAR8 = DataType(0x3, "CHARSTAR8") static
ASCII characters.
Referenced by evio::CompositeData::Data::addString(), evio::CompactEventBuilder::addStringData(), evio::EventBuilder::appendStringData(), evio::BaseStructure::dataLength(), evio::Util::getDataType(), evio::BaseStructure::getNumberDataItems(), evio::BaseStructure::getStringData(), evio::EventBuilder::main(), evio::EventBuilder::setStringData(), evio::EvioSwap::swapLeafData(), evio::BaseStructure::updateStringData(), and evio::BaseStructure::write().
COMPOSITE
const DataType evio::DataType::COMPOSITE = DataType(0xf, "COMPOSITE") static
Composite data type.
Referenced by evio::CompactEventBuilder::addCompositeData(), evio::EventBuilder::appendCompositeData(), evio::BaseStructure::dataLength(), evio::BaseStructure::getCompositeData(), evio::Util::getDataType(), evio::BaseStructure::getNumberDataItems(), evio::EventBuilder::setCompositeData(), evio::EvioSwap::swapLeafData(), evio::BaseStructure::updateCompositeData(), and evio::BaseStructure::write().
DOUBLE64
const DataType evio::DataType::DOUBLE64 = DataType(0x8, "DOUBLE64", 8) static
64 bit double.
Referenced by evio::CompositeData::Data::addDouble(), evio::CompactEventBuilder::addDoubleData(), evio::EventBuilder::appendDoubleData(), evio::Util::getDataType(), evio::BaseStructure::getDoubleData(), evio::EventBuilder::main(), evio::EventBuilder::setDoubleData(), evio::EvioSwap::swapData(), evio::EvioSwap::swapLeafData(), evio::BaseStructure::updateDoubleData(), and evio::BaseStructure::write().
FLOAT32
const DataType evio::DataType::FLOAT32 = DataType(0x2, "FLOAT32", 4) static
32 bit float.
Referenced by evio::CompositeData::Data::addFloat(), evio::CompactEventBuilder::addFloatData(), evio::EventBuilder::appendFloatData(), evio::Util::getDataType(), evio::BaseStructure::getFloatData(), evio::EventBuilder::setFloatData(), evio::EvioSwap::swapData(), evio::EvioSwap::swapLeafData(), evio::BaseStructure::updateFloatData(), and evio::BaseStructure::write().
HOLLERIT
const DataType evio::DataType::HOLLERIT = DataType(0x21, "HOLLERIT") static
In composite data, Hollerit type.
INT32
const DataType evio::DataType::INT32 = DataType(0xb, "INT32", 4) static
32 bit int.
Referenced by evio::CompositeData::Data::addInt(), evio::CompactEventBuilder::addIntData(), evio::EventBuilder::appendIntData(), evio::Util::getDataType(), evio::BaseStructure::getIntData(), isInteger(), evio::EventBuilder::main(), evio::EventBuilder::setIntData(), evio::EvioSwap::swapData(), evio::EvioSwap::swapLeafData(), evio::BaseStructure::updateIntData(), and evio::BaseStructure::write().
LONG64
const DataType evio::DataType::LONG64 = DataType(0x9, "LONG64", 8) static
64 bit int.
Referenced by evio::CompositeData::Data::addLong(), evio::CompactEventBuilder::addLongData(), evio::EventBuilder::appendLongData(), evio::Util::getDataType(), evio::BaseStructure::getLongData(), isInteger(), evio::EventBuilder::setLongData(), evio::EvioSwap::swapData(), evio::EvioSwap::swapLeafData(), evio::BaseStructure::updateLongData(), and evio::BaseStructure::write().
mVALUE
const DataType evio::DataType::mVALUE = DataType(0x24, "mVALUE") static
In composite data, m value.
NOT_A_VALID_TYPE
const DataType evio::DataType::NOT_A_VALID_TYPE = DataType(0x30, "INVALID") static
Not a valid data type.
Referenced by evio::Util::getDataType(), evio::EvioXMLDictionary::getType(), and evio::EvioXMLDictionary::parseXML().
NVALUE
const DataType evio::DataType::NVALUE = DataType(0x22, "NVALUE") static
In composite data, N value.
nVALUE
const DataType evio::DataType::nVALUE = DataType(0x23, "nVALUE") static
In composite data, n value.
SEGMENT
const DataType evio::DataType::SEGMENT = DataType(0x20, "SEGMENT") static
Segment.
Referenced by evio::EventBuilder::addChild(), evio::EvioCompactReaderV4::addStructure(), evio::StructureTransformer::copy(), isSegment(), isStructure(), evio::EventBuilder::main(), evio::CompactEventBuilder::openSegment(), evio::EvioCompactReaderV4::removeStructure(), evio::EvioNode::scanStructure(), evio::StructureTransformer::transform(), evio::EvioNode::updateLengths(), and evio::EvioNode::updateTag().
SHORT16
const DataType evio::DataType::SHORT16 = DataType(0x4, "SHORT16", 2) static
16 bit int.
Referenced by evio::CompositeData::Data::addShort(), evio::CompactEventBuilder::addShortData(), evio::EventBuilder::appendShortData(), evio::Util::getDataType(), evio::BaseStructure::getShortData(), isInteger(), evio::EventBuilder::main(), evio::EventBuilder::setShortData(), evio::EvioSwap::swapData(), evio::EvioSwap::swapLeafData(), evio::BaseStructure::updateShortData(), and evio::BaseStructure::write().
TAGSEGMENT
const DataType evio::DataType::TAGSEGMENT = DataType(0xc, "TAGSEGMENT") static
Tag segment.
Referenced by evio::EventBuilder::addChild(), evio::EvioCompactReaderV4::addStructure(), evio::Util::getDataType(), isStructure(), isTagSegment(), evio::EventBuilder::main(), evio::CompactEventBuilder::openTagSegment(), evio::EvioCompactReaderV4::removeStructure(), evio::EvioNode::scanStructure(), evio::EvioNode::updateLengths(), and evio::EvioNode::updateTag().
UCHAR8
const DataType evio::DataType::UCHAR8 = DataType(0x7, "UCHAR8", 1) static
Unsigned 8 bit int.
Referenced by evio::CompactEventBuilder::addByteData(), evio::CompositeData::Data::addm(), evio::CompositeData::Data::addUChar(), evio::EventBuilder::appendUCharData(), evio::BaseStructure::dataLength(), evio::Util::getDataType(), evio::BaseStructure::getUCharData(), isInteger(), evio::EventBuilder::setUCharData(), evio::EvioSwap::swapLeafData(), evio::BaseStructure::updateUCharData(), and evio::BaseStructure::write().
UINT32
const DataType evio::DataType::UINT32 = DataType(0x1, "UINT32", 4) static
Unsigned 32 bit int.
Referenced by evio::CompactEventBuilder::addIntData(), evio::CompositeData::Data::addN(), evio::CompositeData::Data::addUint(), evio::EventBuilder::appendUIntData(), evio::Util::getDataType(), evio::BaseStructure::getUIntData(), isInteger(), evio::EventBuilder::setUIntData(), evio::EvioSwap::swapData(), evio::EvioSwap::swapLeafData(), evio::BaseStructure::updateUIntData(), and evio::BaseStructure::write().
ULONG64
const DataType evio::DataType::ULONG64 = DataType(0xa, "ULONG64", 8) static
Unsigned 64 bit int.
Referenced by evio::CompactEventBuilder::addLongData(), evio::CompositeData::Data::addULong(), evio::EventBuilder::appendULongData(), evio::Util::getDataType(), evio::BaseStructure::getULongData(), isInteger(), evio::EventBuilder::setULongData(), evio::EvioSwap::swapData(), evio::EvioSwap::swapLeafData(), evio::BaseStructure::updateULongData(), and evio::BaseStructure::write().
UNKNOWN32
const DataType evio::DataType::UNKNOWN32 = DataType(0x0, "UNKNOWN32") static
Unknown data type.
Referenced by evio::CompactEventBuilder::addIntData(), evio::BaseStructure::dataLength(), evio::Util::getDataType(), getDataType(), evio::EvioXMLDictionary::getName(), evio::EvioXMLDictionary::parseXML(), evio::EvioSwap::swapLeafData(), valueOf(), and evio::BaseStructure::write().
USHORT16
const DataType evio::DataType::USHORT16 = DataType(0x5, "USHORT16", 2) static
Unsigned 16 bit int.
Referenced by evio::CompositeData::Data::addn(), evio::CompactEventBuilder::addShortData(), evio::CompositeData::Data::addUShort(), evio::EventBuilder::appendUShortData(), evio::Util::getDataType(), evio::BaseStructure::getUShortData(), isInteger(), evio::EventBuilder::setUShortData(), evio::EvioSwap::swapData(), evio::EvioSwap::swapLeafData(), evio::BaseStructure::updateUShortData(), and evio::BaseStructure::write().
The documentation for this class was generated from the following files:
DataType.h
DataType.cpp