evio: evio::evioDOMNode Class Reference
evio::evioDOMNode Class Reference abstract
Virtual class represents an evio node in memory, concrete sub-classes evioDOMContainerNode and evioDOMLeafNode are hidden from users.
#include <evioUtil.hxx>
Public Member Functions
virtual ~evioDOMNode ()=default
virtual void addNode (evioDOMNodeP node)
Adds node to container node.
void append (const string &s)
Appends string to leaf node.
void append (const char *s)
Appends const char* to leaf node.
void append (char *s)
Appends char* to leaf node.
void append (const char **ca, int len)
Appends array of const char* to leaf node.
void append (char **ca, int len)
Appends array of const char* to leaf node.
template<typename T >
void append (T tVal)
template<typename T >
void append (const vector< T > &tVec)
template<typename T >
void append (const T *tBuf, int len)
template<typename T >
void replace (const vector< T > &tVec)
template<typename T >
void replace (const T *tBuf, int len)
virtual evioDOMNodeP cut ()
Cleanly removes node from tree or node hierarchy.
virtual void cutAndDelete ()
Cleanly removes node from tree or node hierarchy and recursively deletes node and its contents.
virtual evioDOMNodeP move (evioDOMNodeP newParent)
Changes node parent.
virtual bool operator== (uint16_t tag) const
True if node tag equals value.
virtual bool operator!= (uint16_t tag) const
True if node tag does not equal value.
bool operator== (evioDictEntry tnPair) const
True if node tag and num same as in evioDictEntry pair.
bool operator!= (evioDictEntry tnPair) const
True if node tag and num NOT the same as in evioDictEntry pair.
evioDOMNode & operator<< (evioDOMNodeP node)
Adds node to container node.
evioDOMNode & operator<< (const string &s)
Appends single string to leaf node.
evioDOMNode & operator<< (const char *s)
Appends single const char* to leaf node.
evioDOMNode & operator<< (char *s)
Appends single char* to leaf node.
template<typename T >
evioDOMNode & operator<< (T tVal)
template<typename T >
evioDOMNode & operator<< (const vector< T > &tVec)
evioDOMNodeList * getChildList ()
Returns pointer to child list of container node.
evioDOMNodeListP getChildren ()
Returns copy of child list of container node.
template<class Predicate >
evioDOMNodeListP getChildren (Predicate pred)
template<typename T >
vector< T > * getVector ()
virtual string toString () const
Returns XML string listing container node contents.
virtual string getHeader (int depth, const evioToStringConfig *config=&defaultToStringConfig) const =0
virtual string getBody (int depth, const evioToStringConfig *config=&defaultToStringConfig) const =0
virtual string getFooter (int depth, const evioToStringConfig *config=&defaultToStringConfig) const =0
virtual int getSize () const =0
evioDOMNodeP getParent () const
Returns parent evioDOMNode.
int getContentType () const
Returns content type.
evioDOMTree * getParentTree () const
Returns parent evioDOMTree.
bool isContainer () const
True if node is a container node.
bool isLeaf () const
True if node is a leaf node.
Static Public Member Functions
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, ContainerType cType=BANK)
Static factory method to create container node.
template<typename T >
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num)
template<typename T >
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, const vector< T > &tVec)
template<typename T >
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, const T *t, int len)
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, const evioSerializable &o, ContainerType cType=BANK)
Static factory method to create container node holding evioSerializable object.
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, void(*f)(evioDOMNodeP c, void *userArg), void *userArg, ContainerType cType=BANK)
Static factory method to create container node using C function to fill container.
template<typename T >
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, T *t, void *userArg, ContainerType cType=BANK)
template<typename T >
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, T *t, void *T::*mfp(evioDOMNodeP c, void *userArg), void *userArg, ContainerType cType=BANK)
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, uint16_t formatTag, const string &formatString, uint16_t dataTag, uint8_t dataNum, const vector< uint32_t > &tVec)
Static factory method to create composite leaf node.
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, uint16_t formatTag, const string &formatString, uint16_t dataTag, uint8_t dataNum, const uint32_t *t, int len)
Static factory method to create composite leaf node.
static evioDOMNodeP createUnknownEvioDOMNode (uint16_t tag, uint8_t num, const vector< uint32_t > &tVec)
Unknown type node constructor used internally.
static evioDOMNodeP createUnknownEvioDOMNode (uint16_t tag, uint8_t num, const uint32_t *t, int len)
Unknown type node constructor used internally.
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, ContainerType cType=BANK)
Static factory method to create container node.
template<typename T >
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary)
template<typename T >
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, const vector< T > &tVec)
template<typename T >
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, const T *t, int len)
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, const evioSerializable &o, ContainerType cType=BANK)
Static factory method to create container node holding evioSerializable object.
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, void(*f)(evioDOMNodeP c, void *userArg), void *userArg, ContainerType cType=BANK)
Static factory method to create container node using C function to fill container.
template<typename T >
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, T *t, void *userArg, ContainerType cType=BANK)
template<typename T >
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, T *t, void *T::*mfp(evioDOMNodeP c, void *userArg), void *userArg, ContainerType cType=BANK)
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, uint16_t formatTag, const string &formatString, uint16_t dataTag, uint8_t dataNum, const vector< uint32_t > &tVec)
Static factory method to create composite leaf node.
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, uint16_t formatTag, const string &formatString, uint16_t dataTag, uint8_t dataNum, const uint32_t *t, int len)
Static factory method to create composite leaf node.
static evioDOMNodeP createUnknownEvioDOMNode (const string &name, const evioDictionary *dictionary, const vector< uint32_t > &tVec)
Unknown type node constructor used internally.
static evioDOMNodeP createUnknownEvioDOMNode (const string &name, const evioDictionary *dictionary, const uint32_t *t, int len)
Unknown type node constructor used internally.
Public Attributes
uint16_t tag
The node tag, max 16-bits depending on container type.
uint8_t num
The node num, max 8 bits, used by BANK and String container types (2-word header).
Protected Member Functions
evioDOMNode (evioDOMNodeP parent, uint16_t tag, uint8_t num, int contentType)
Container node constructor used internally.
evioDOMNode (evioDOMNodeP parent, const string &name, const evioDictionary *dictionary, int contentType)
Container node constructor used internally.
Static Protected Member Functions
static string getIndent (int depth, int size=3)
Returns indent for pretty-printing, used internally.
Protected Attributes
evioDOMNodeP parent
Pointer to node parent.
evioDOMTree * parentTree
Pointer to parent tree if this node is the root.
int contentType
Content type.
Friends
class evioDOMTree
Allows evioDOMTree class to manipulate nodes.
Detailed Description
Virtual class represents an evio node in memory, concrete sub-classes evioDOMContainerNode and evioDOMLeafNode are hidden from users.
Users work with nodes via this class, and create nodes via factory method createEvioDOMNode. Factory model ensures nodes are created on heap.
Constructor & Destructor Documentation
evioDOMNode() [1/2]
evioDOMNode::evioDOMNode (evioDOMNodeP par, uint16_t tag, uint8_t num, int contentType) protected
Container node constructor used internally.
Parameters
par Parent node
tag Node tag
num Node num
contentType Container node content type
evioDOMNode() [2/2]
evioDOMNode::evioDOMNode (evioDOMNodeP par, const string & name, const evioDictionary * dictionary, int contentType) protected
Container node constructor used internally.
Parameters
par Parent node
name Bank name @parem dictionary Dictionary to use
contentType Container node content type
References evio::evioDictionary::getEntry(), evio::evioDictEntry::getNum(), evio::evioDictEntry::getTag(), num, and tag.
~evioDOMNode()
virtual evio::evioDOMNode::~evioDOMNode () virtual default
Member Function Documentation
addNode()
void evioDOMNode::addNode (evioDOMNodeP node) virtual
Adds node to container node.
Parameters
node Node to be added
References isContainer(), and move().
Referenced by operator<<().
append() [1/8]
void evioDOMNode::append (char ** ca, int len)
Appends array of const char* to leaf node.
Parameters
sa array of char* to append
References append().
append() [2/8]
void evioDOMNode::append (char * s)
Appends char* to leaf node.
Parameters
s char* to append
References append().
append() [3/8]
void evioDOMNode::append (const char ** ca, int len)
Appends array of const char* to leaf node.
Parameters
sa array of char* to append
References contentType, and evio::evioDOMLeafNode< T >::data.
append() [4/8]
void evioDOMNode::append (const char * s)
Appends const char* to leaf node.
Parameters
s char* to append
References contentType, and evio::evioDOMLeafNode< T >::data.
append() [5/8]
void evioDOMNode::append (const string & s)
Appends string to leaf node.
Parameters
s string to append
References contentType, and evio::evioDOMLeafNode< T >::data.
Referenced by append(), and operator<<().
append() [6/8]
template<typename T > void evio::evioDOMNode::append (const T * tBuf, int len)
append() [7/8]
template<typename T > void evio::evioDOMNode::append (const vector< T > & tVec)
append() [8/8]
template<typename T > void evio::evioDOMNode::append (T tVal)
createEvioDOMNode() [1/20]
template<typename T > static evioDOMNodeP evio::evioDOMNode::createEvioDOMNode (const string & name, const evioDictionary * dictionary) static
createEvioDOMNode() [2/20]
evioDOMNodeP evioDOMNode::createEvioDOMNode (const string & name, const evioDictionary * dictionary, const evioSerializable & o, ContainerType cType = BANK) static
Static factory method to create container node holding evioSerializable object.
Parameters
name Node name
dictionary Dictionary to use
o evioSerializable object
cType Container node content type
Returns
Pointer to new node
References evio::evioDictionary::getEntry(), evio::evioDictEntry::getNum(), evio::evioDictEntry::getTag(), and evio::evioSerializable::serialize().
createEvioDOMNode() [3/20]
template<typename T > static evioDOMNodeP evio::evioDOMNode::createEvioDOMNode (const string & name, const evioDictionary * dictionary, const T * t, int len) static
createEvioDOMNode() [4/20]
template<typename T > static evioDOMNodeP evio::evioDOMNode::createEvioDOMNode (const string & name, const evioDictionary * dictionary, const vector< T > & tVec) static
createEvioDOMNode() [5/20]
evioDOMNodeP evioDOMNode::createEvioDOMNode (const string & name, const evioDictionary * dictionary, ContainerType cType = BANK) static
Static factory method to create container node.
Parameters
name Node name
dictionary Dictionary to use
cType Container node content type
Returns
Pointer to new node
References evio::evioDictionary::getEntry(), evio::evioDictEntry::getNum(), and evio::evioDictEntry::getTag().
createEvioDOMNode() [6/20]
template<typename T > static evioDOMNodeP evio::evioDOMNode::createEvioDOMNode (const string & name, const evioDictionary * dictionary, T * t, void *T::* mfpevioDOMNodeP c, void *userArg, void * userArg, ContainerType cType = BANK) static
createEvioDOMNode() [7/20]
template<typename T > static evioDOMNodeP evio::evioDOMNode::createEvioDOMNode (const string & name, const evioDictionary * dictionary, T * t, void * userArg, ContainerType cType = BANK) static
createEvioDOMNode() [8/20]
evioDOMNodeP evioDOMNode::createEvioDOMNode (const string & name, const evioDictionary * dictionary, uint16_t formatTag, const string & formatString, uint16_t dataTag, uint8_t dataNum, const uint32_t * t, int len) static
Static factory method to create composite leaf node.
Parameters
name Node name
dictionary Dictionary to use
formatTag Format tag
formatString Format string
dataTag Data tag
dataNum Data num
t Pointer to array of uint32_t data
len Length of array
Returns
Pointer to new node
References evio::evioDictionary::getEntry(), evio::evioDictEntry::getNum(), and evio::evioDictEntry::getTag().
createEvioDOMNode() [9/20]
evioDOMNodeP evioDOMNode::createEvioDOMNode (const string & name, const evioDictionary * dictionary, uint16_t formatTag, const string & formatString, uint16_t dataTag, uint8_t dataNum, const vector< uint32_t > & tVec) static
Static factory method to create composite leaf node.
Parameters
name Node name
dictionary Dictionary to use
formatTag Format tag
formatString Format string
dataTag Data tag
dataNum Data num
tVec vector<uint32_t> of data
Returns
Pointer to new node
References evio::evioDictionary::getEntry(), evio::evioDictEntry::getNum(), and evio::evioDictEntry::getTag().
createEvioDOMNode() [10/20]
evioDOMNodeP evioDOMNode::createEvioDOMNode (const string & name, const evioDictionary * dictionary, void(*)(evioDOMNodeP c, void *userArg) f, void * userArg, ContainerType cType = BANK) static
Static factory method to create container node using C function to fill container.
Parameters
name Node name
dictionary Dictionary to use
f C function that fills container node
userArg User arg passed to C function
cType Container node content type
Returns
Pointer to new node
References evio::evioDictionary::getEntry(), evio::evioDictEntry::getNum(), and evio::evioDictEntry::getTag().
createEvioDOMNode() [11/20]
template<typename T > static evioDOMNodeP evio::evioDOMNode::createEvioDOMNode (uint16_t tag, uint8_t num) static
createEvioDOMNode() [12/20]
evioDOMNodeP evioDOMNode::createEvioDOMNode (uint16_t tag, uint8_t num, const evioSerializable & o, ContainerType cType = BANK) static
Static factory method to create container node holding evioSerializable object.
Parameters
tag Node tag
num Node num
o evioSerializable object
cType Container node content type
Returns
Pointer to new node
References num, evio::evioSerializable::serialize(), and tag.
createEvioDOMNode() [13/20]
template<typename T > static evioDOMNodeP evio::evioDOMNode::createEvioDOMNode (uint16_t tag, uint8_t num, const T * t, int len) static
createEvioDOMNode() [14/20]
template<typename T > static evioDOMNodeP evio::evioDOMNode::createEvioDOMNode (uint16_t tag, uint8_t num, const vector< T > & tVec) static
createEvioDOMNode() [15/20]
evioDOMNodeP evioDOMNode::createEvioDOMNode (uint16_t tag, uint8_t num, ContainerType cType = BANK) static
Static factory method to create container node.
Parameters
tag Node tag
num Node num
cType Container node content type
Returns
Pointer to new node
References num, and tag.
Referenced by evio::evioDOMTree::addBank(), evio::evioDOMTree::createNode(), createUnknownEvioDOMNode(), and evio::evioDOMTree::evioDOMTree().
createEvioDOMNode() [16/20]
template<typename T > static evioDOMNodeP evio::evioDOMNode::createEvioDOMNode (uint16_t tag, uint8_t num, T * t, void *T::* mfpevioDOMNodeP c, void *userArg, void * userArg, ContainerType cType = BANK) static
createEvioDOMNode() [17/20]
template<typename T > static evioDOMNodeP evio::evioDOMNode::createEvioDOMNode (uint16_t tag, uint8_t num, T * t, void * userArg, ContainerType cType = BANK) static
createEvioDOMNode() [18/20]
evioDOMNodeP evioDOMNode::createEvioDOMNode (uint16_t tag, uint8_t num, uint16_t formatTag, const string & formatString, uint16_t dataTag, uint8_t dataNum, const uint32_t * t, int len) static
Static factory method to create composite leaf node.
Parameters
tag Node tag
num Node num
formatTag Format tag
formatString Format string
dataTag Data tag
dataNum Data num
t Pointer to uint32_t data
len Length of data array
Returns
Pointer to new node
References num, and tag.
createEvioDOMNode() [19/20]
evioDOMNodeP evioDOMNode::createEvioDOMNode (uint16_t tag, uint8_t num, uint16_t formatTag, const string & formatString, uint16_t dataTag, uint8_t dataNum, const vector< uint32_t > & tVec) static
Static factory method to create composite leaf node.
Parameters
tag Node tag
num Node num
formatTag Format tag
formatString Format string
dataTag Data tag
dataNum Data num
tVec vector<uint32_t> of data
Returns
Pointer to new node
References num, and tag.
createEvioDOMNode() [20/20]
evioDOMNodeP evioDOMNode::createEvioDOMNode (uint16_t tag, uint8_t num, void(*)(evioDOMNodeP c, void *userArg) f, void * userArg, ContainerType cType = BANK) static
Static factory method to create container node using C function to fill container.
Parameters
tag Node tag
num Node num
f C function that fills container node
userArg User arg passed to C function
cType Container node content type
Returns
Pointer to new node
References num, and tag.
createUnknownEvioDOMNode() [1/4]
evioDOMNodeP evioDOMNode::createUnknownEvioDOMNode (const string & name, const evioDictionary * dictionary, const uint32_t * t, int len) static
Unknown type node constructor used internally.
Parameters
name Name
dictionary Dictionary
t Pointer to array of uint32_t
len Length of array
Returns
Pointer to new node
References contentType, createEvioDOMNode(), evio::evioDictionary::getEntry(), evio::evioDictEntry::getNum(), and evio::evioDictEntry::getTag().
createUnknownEvioDOMNode() [2/4]
evioDOMNodeP evioDOMNode::createUnknownEvioDOMNode (const string & name, const evioDictionary * dictionary, const vector< uint32_t > & tVec) static
Unknown type node constructor used internally.
Parameters
name Name
dictionary Dictionary
tVec Vector of uint32_t
Returns
Pointer to new node
References contentType, createEvioDOMNode(), evio::evioDictionary::getEntry(), evio::evioDictEntry::getNum(), and evio::evioDictEntry::getTag().
createUnknownEvioDOMNode() [3/4]
evioDOMNodeP evioDOMNode::createUnknownEvioDOMNode (uint16_t tag, uint8_t num, const uint32_t * t, int len) static
Unknown type node constructor used internally.
Parameters
tag Tag
num Num
t Pointer to uint32_t array
len Length of array
Returns
Pointer to new node
References contentType, createEvioDOMNode(), num, and tag.
createUnknownEvioDOMNode() [4/4]
evioDOMNodeP evioDOMNode::createUnknownEvioDOMNode (uint16_t tag, uint8_t num, const vector< uint32_t > & tVec) static
Unknown type node constructor used internally.
Parameters
tag Tag
num Num
tVec Vector of uint32_t
Returns
Pointer to new node
References contentType, createEvioDOMNode(), num, and tag.
cut()
evioDOMNodeP evioDOMNode::cut () virtual
Cleanly removes node from tree or node hierarchy.
Returns
Pointer to now liberated node
References evio::evioDOMContainerNode::childList, parent, parentTree, and evio::evioDOMTree::root.
Referenced by evio::evioDOMTree::addBank(), cutAndDelete(), and move().
cutAndDelete()
void evioDOMNode::cutAndDelete () virtual
Cleanly removes node from tree or node hierarchy and recursively deletes node and its contents.
References cut().
Referenced by evio::evioDOMTree::clear(), and evio::evioDOMTree::~evioDOMTree().
getBody()
virtual string evio::evioDOMNode::getBody (int depth, const evioToStringConfig * config = &defaultToStringConfig) const pure virtual
Implemented in evio::evioCompositeDOMLeafNode, evio::evioDOMLeafNode< T >, evio::evioDOMLeafNode< uint32_t >, and evio::evioDOMContainerNode.
getChildList()
evioDOMNodeList * evioDOMNode::getChildList ()
Returns pointer to child list of container node.
Returns
Pointer to internal child list
References isContainer().
Referenced by getChildren().
getChildren() [1/2]
evioDOMNodeListP evioDOMNode::getChildren ()
Returns copy of child list of container node.
List must be deleted by user
Returns
Copy of child list
References getChildList().
getChildren() [2/2]
template<class Predicate > evioDOMNodeListP evio::evioDOMNode::getChildren (Predicate pred)
getContentType()
int evioDOMNode::getContentType () const
Returns content type.
Returns
Content type
References contentType.
Referenced by evio::evioDOMContainerNode::getFooter(), and evio::evioDOMContainerNode::getHeader().
getFooter()
virtual string evio::evioDOMNode::getFooter (int depth, const evioToStringConfig * config = &defaultToStringConfig) const pure virtual
Implemented in evio::evioDOMLeafNode< T >, evio::evioDOMLeafNode< uint32_t >, and evio::evioDOMContainerNode.
Referenced by toString().
getHeader()
virtual string evio::evioDOMNode::getHeader (int depth, const evioToStringConfig * config = &defaultToStringConfig) const pure virtual
Implemented in evio::evioDOMLeafNode< T >, evio::evioDOMLeafNode< uint32_t >, and evio::evioDOMContainerNode.
Referenced by toString().
getIndent()
string evioDOMNode::getIndent (int depth, int size = 3) static protected
Returns indent for pretty-printing, used internally.
Parameters
depth Depth level
size Size of indent per level
Returns
String containing proper number of indent spaces for this depth
Referenced by evio::evioCompositeDOMLeafNode::getBody(), evio::evioDOMContainerNode::getFooter(), and evio::evioDOMContainerNode::getHeader().
getParent()
evioDOMNodeP evioDOMNode::getParent () const
Returns parent evioDOMNode.
Returns
Pointer to parent evioDOMNode
References parent.
getParentTree()
evioDOMTree * evioDOMNode::getParentTree () const
Returns parent evioDOMTree.
Returns
Pointer to parent evioDOMTree
References parentTree.
getSize()
virtual int evio::evioDOMNode::getSize () const pure virtual
Implemented in evio::evioCompositeDOMLeafNode, evio::evioDOMLeafNode< T >, evio::evioDOMLeafNode< uint32_t >, and evio::evioDOMContainerNode.
Referenced by toString().
getVector()
template<typename T > vector<T>* evio::evioDOMNode::getVector ()
isContainer()
bool evioDOMNode::isContainer () const
True if node is a container node.
Returns
true if node is a container
References contentType.
Referenced by evio::evioDOMTree::addBank(), addNode(), getChildList(), and move().
isLeaf()
bool evioDOMNode::isLeaf () const
True if node is a leaf node.
Returns
true if node is a leaf
References contentType.
Referenced by toString().
move()
evioDOMNodeP evioDOMNode::move (evioDOMNodeP newParent) virtual
Changes node parent.
Parameters
newParent New parent
Returns
Pointer to now node just moved
References evio::evioDOMContainerNode::childList, cut(), isContainer(), and parent.
Referenced by addNode().
operator!=() [1/2]
bool evioDOMNode::operator!= (evioDictEntry tnPair) const
True if node tag and num NOT the same as in evioDictEntry pair.
Parameters
tnPair evioDictEntry pair to compare to
Returns
true if tag and num disagree
References evio::evioDictEntry::getNum(), and evio::evioDictEntry::getTag().
operator!=() [2/2]
bool evioDOMNode::operator!= (uint16_t tg) const virtual
True if node tag does not equal value.
Parameters
tg Value to compare to
Returns
true if tags disagree
operator<<() [1/6]
evioDOMNode & evioDOMNode::operator<< (char * s)
Appends single char* to leaf node.
Parameters
s char* to be added
Returns
Reference to this
References append().
operator<<() [2/6]
evioDOMNode & evioDOMNode::operator<< (const char * s)
Appends single const char* to leaf node.
Parameters
s char* to be added
Returns
Reference to this
References append().
operator<<() [3/6]
evioDOMNode & evioDOMNode::operator<< (const string & s)
Appends single string to leaf node.
Parameters
sRef String to be added
Returns
Reference to this
References append().
operator<<() [4/6]
template<typename T > evioDOMNode& evio::evioDOMNode::operator<< (const vector< T > & tVec)
operator<<() [5/6]
evioDOMNode & evioDOMNode::operator<< (evioDOMNodeP node)
Adds node to container node.
Parameters
node Node to be added
Returns
Reference to node to be added
References addNode().
operator<<() [6/6]
template<typename T > evioDOMNode& evio::evioDOMNode::operator<< (T tVal)
operator==() [1/2]
bool evioDOMNode::operator== (evioDictEntry tnPair) const
True if node tag and num same as in evioDictEntry pair.
Parameters
tnPair evioDictEntry pair to compare to
Returns
true if tag and num agree
References evio::evioDictEntry::getNum(), and evio::evioDictEntry::getTag().
operator==() [2/2]
bool evioDOMNode::operator== (uint16_t tg) const virtual
True if node tag equals value.
Parameters
tg Value to compare to
Returns
true if tags agree
replace() [1/2]
template<typename T > void evio::evioDOMNode::replace (const T * tBuf, int len)
replace() [2/2]
template<typename T > void evio::evioDOMNode::replace (const vector< T > & tVec)
toString()
string evioDOMNode::toString () const virtual
Returns XML string listing container node contents.
Returns
XML string listing contents
References getFooter(), getHeader(), getSize(), and isLeaf().
Friends And Related Function Documentation
evioDOMTree
friend class evioDOMTree friend
Allows evioDOMTree class to manipulate nodes.
Member Data Documentation
contentType
int evio::evioDOMNode::contentType protected
Content type.
Referenced by append(), createUnknownEvioDOMNode(), evio::evioCompositeDOMLeafNode::evioCompositeDOMLeafNode(), getContentType(), evio::evioDOMContainerNode::getHeader(), isContainer(), and isLeaf().
num
uint8_t evio::evioDOMNode::num
The node num, max 8 bits, used by BANK and String container types (2-word header).
Referenced by createEvioDOMNode(), createUnknownEvioDOMNode(), evioDOMNode(), evio::evioDOMContainerNode::getFooter(), evio::evioDOMContainerNode::getHeader(), and evio::evioToStringConfig::skipNode().
parent
evioDOMNodeP evio::evioDOMNode::parent protected
Pointer to node parent.
Referenced by evio::evioDOMTree::addBank(), cut(), evio::evioDOMContainerNode::getFooter(), evio::evioDOMContainerNode::getHeader(), getParent(), and move().
parentTree
evioDOMTree* evio::evioDOMNode::parentTree protected
Pointer to parent tree if this node is the root.
Referenced by evio::evioDOMTree::addBank(), cut(), evio::evioDOMTree::evioDOMTree(), and getParentTree().
tag
uint16_t evio::evioDOMNode::tag
The node tag, max 16-bits depending on container type.
Referenced by createEvioDOMNode(), createUnknownEvioDOMNode(), evioDOMNode(), evio::evioDOMContainerNode::getFooter(), evio::evioDOMContainerNode::getHeader(), and evio::evioToStringConfig::skipNode().
The documentation for this class was generated from the following files:
evioUtil.hxx
evioUtil.cc