# scons build file for evio
Import('env', 'platform', 'archDir', 'incInstallDir', 'libInstallDir', 'binInstallDir', 'archIncInstallDir', 'execLibs', 'debugSuffix', 'disruptorHome')

# Headers to install
headerList = Glob('*.h', strings=True)

# Files to compile
fileList = Glob('*.cpp',  strings=True)

env.AppendUnique(CPPPATH = ['#src/libsrc', '/usr/local/include', '/usr/include/boost', '/usr/local/include/boost'])

#evioNewLib = env.StaticLibrary(target = 'eviocc'+debugSuffix, source = fileList)
evioNewLib = env.SharedLibrary(target = 'eviocc'+debugSuffix, source = fileList)

if 'install' in COMMAND_LINE_TARGETS:
    env.Alias("install", env.Install(target = [incInstallDir, archIncInstallDir], source = headerList))
    env.Alias("install", env.Install(target = libInstallDir, source = evioNewLib))
