# scons build file for evio
Import('env', 'libDir', 'incDir', 'archIncDir', 'debugSuffix')
import os
from os import sep

headerList = ['evio.h',
              'evio_util.h']

linkList = [archIncDir + sep + 'evio.h',
            archIncDir + sep + 'evio_util.h']

fileList = ['evio.c',
            'evioswap.c',
            'evio_util.c',
            'swap_util.c',
            'xml_util.c']

env.AppendUnique(CPPPATH = ['.'])
evioLib = env.SharedLibrary(target = 'evio'+debugSuffix, source = fileList)

env.Alias("install", env.Install(target = incDir, source = headerList))
env.Alias("install", env.Install(target = libDir, source = evioLib))
# create symbolic links to installed header files
env.Alias("install", env.CreateSymbolicLinks(target = linkList, source = env.Install(target = incDir, source = headerList)))
