# scons build file for evio execsrc
Import('env', 'libInstallDir', 'binInstallDir', 'archDir', 'execLibs', 'debugSuffix')

# lists of all C++ files
ccfileList = Glob('*.cpp', strings=True)


boostThdLib = 'boost_thread'
if platform == 'Darwin':
    boostThdLib = 'boost_thread-mt'


# Compile C++ files and install
for fileName in ccfileList:
    compiledFile = env.Program(source  = fileName,
                            LIBS    = ['evio'+debugSuffix, 'Disruptor',
                                       'boost_system', boostThdLib,  'boost_chrono',  execLibs],
                            LIBPATH = ['#src/libsrc/'+archDir, '/usr/local/lib'],
                            CPPPATH = ['#src/libsrc', disruptorHome, '/usr/local/include',
                                      '/usr/include/boost', '/usr/local/include/boost'])

    if 'install' in COMMAND_LINE_TARGETS:
        env.Alias('install', env.Install(target = binInstallDir, source = compiledFile))
