evio: evio::evioDictEntry Class Reference
evio::evioDictEntry Class Reference
This class defines an entry in the XML dictionary.
#include <evioDictEntry.hxx>
Public Member Functions
evioDictEntry ()
Zero arg constructor.
evioDictEntry (uint16_t tag)
Constructor for tag-only entry.
evioDictEntry (uint16_t tag, uint8_t num, uint16_t tagEnd)
Constructor for tag-range entry.
evioDictEntry (uint16_t tag, uint8_t num)
Constructor for tag and num entry.
evioDictEntry (uint16_t tag, uint8_t num, uint16_t tagEnd, DataType type, bool numIsUndefined=false, string format="", string description="")
General constructor.
evioDictEntry (uint16_t tag, uint8_t num, uint16_t tagEnd, bool hasParent, uint16_t parentTag, uint8_t parentNum, uint16_t parentTagEnd, DataType type, bool numIsUndefined=false, string format="", string description="")
General constructor.
evioDictEntry (const evioDictEntry &entry)
Copy constructor.
virtual ~evioDictEntry ()
Destructor.
uint16_t getTag (void) const
Get the tag value of this entry.
uint16_t getTagEnd (void) const
Get the ending value of a tag range defined by this entry.
uint8_t getNum (void) const
Get the num value of this entry.
bool isNumUndefined (void) const
Get whether num is undefined.
DataType getType (void) const
Get the data type of this entry.
DictEntryType getEntryType (void) const
Get the type of this entry.
string getFormat (void) const
Get the string describing the data format of this entry.
string getDescription (void) const
Get the string describing the data of this entry.
uint16_t getParentTag (void) const
Get the tag of parent entry if any.
uint16_t getParentTagEnd (void) const
Get the tagEnd of parent entry if any.
uint8_t getParentNum (void) const
Get the num of parent entry if any.
bool hasParent (void) const
Does this entry have a valid parent entry?
string toString (void) const throw (evioException)
Create a string representation of this object.
bool inRange (uint16_t tagArg)
Is the given tag within the specified range (inclusive) of this dictionary entry?
bool operator== (const evioDictEntry &tn) const
bool operator< (const evioDictEntry &tn) const
Static Public Member Functions
static DataType getDataType (const char *type)
Given a string data type, return the equivalent DataType enum.
Friends
class evioDictionary
Detailed Description
This class defines an entry in the XML dictionary.
Constructor & Destructor Documentation
evioDictEntry() [1/7]
evioDictEntry::evioDictEntry ()
Zero arg constructor.
References evio::EVIO_UNKNOWN32.
evioDictEntry() [2/7]
evioDictEntry::evioDictEntry (uint16_t tag) explicit
Constructor for tag-only entry.
Parameters
tag tag
References evio::EVIO_UNKNOWN32.
evioDictEntry() [3/7]
evioDictEntry::evioDictEntry (uint16_t tag, uint8_t num, uint16_t tagEnd)
Constructor for tag-range entry.
If tag > tagEnd, these values are switched.
Parameters
tag beginning tag of range
num num is used only to differentiate this from the tag-num constructor.
tagEnd ending tag of range
References evio::EVIO_UNKNOWN32.
evioDictEntry() [4/7]
evioDictEntry::evioDictEntry (uint16_t tag, uint8_t num)
Constructor for tag and num entry.
Parameters
tag tag
num num
References evio::EVIO_UNKNOWN32.
evioDictEntry() [5/7]
evioDictEntry::evioDictEntry (uint16_t tag, uint8_t num, uint16_t tagEnd, DataType type, bool numIsUndefined = false, string format = "", string description = "")
General constructor.
If tag > tagEnd, these values are switched.
Parameters
tag tag or the beginning tag of a range.
num num.
tagEnd ending tag of a range. Set to 0 or same value as tag if no range desired.
type type of evio data contained in evio structure this entry represents.
numIsUndefined if desiring a tag-range or tag-only entry, set this to
true
, else
false
. Defaults to false.
format string describing data format. Defaults to "".
description string describing data. Defaults to "".
evioDictEntry() [6/7]
evioDictEntry::evioDictEntry (uint16_t tag, uint8_t num, uint16_t tagEnd, bool hasParent, uint16_t parentTag, uint8_t parentNum, uint16_t parentTagEnd, DataType type, bool numIsUndefined = false, string format = "", string description = "")
General constructor.
If tag > tagEnd, these values are switched.
Parameters
tag tag or the beginning tag of a range.
num num.
tagEnd ending tag of a range. Set to 0 or same value as tag if no range desired.
type type of evio data contained in evio structure this entry represents.
numIsUndefined if desiring a tag-range or tag-only entry, set this to
true
, else
false
. Defaults to false.
format string describing data format. Defaults to "".
description string describing data. Defaults to "".
evioDictEntry() [7/7]
evioDictEntry::evioDictEntry (const evioDictEntry & entry)
Copy constructor.
~evioDictEntry()
evioDictEntry::~evioDictEntry () virtual
Destructor.
Member Function Documentation
getDataType()
DataType evioDictEntry::getDataType (const char * type) static
Given a string data type, return the equivalent DataType enum.
@parm type data type string of "unknown32", "uint32", ... "bank", "segment".
Returns
DataType enum equivalent of arg.
References evio::EVIO_UNKNOWN32.
Referenced by evio::evioDictionary::startElementHandler().
getDescription()
string evioDictEntry::getDescription (void) const
Get the string describing the data of this entry.
Since
5.2
Returns
description.
Referenced by evio::evioDictionary::toString().
getEntryType()
DictEntryType evioDictEntry::getEntryType (void) const
Get the type of this entry.
Since
5.2
Returns
DictEntryType enum specify a tag & num, only a tag, or a tag range.
Referenced by evio::evioDictionary::charDataHandler(), evio::evioDictionary::getName(), and evio::evioDictionary::startElementHandler().
getFormat()
string evioDictEntry::getFormat (void) const
Get the string describing the data format of this entry.
Since
5.2
Returns
format.
Referenced by evio::evioDictionary::toString().
getNum()
uint8_t evioDictEntry::getNum (void) const
Get the num value of this entry.
Returns
num.
Referenced by evio::evioDOMTree::addBank(), evio::evioDOMNode::createEvioDOMNode(), evio::evioDOMNode::createUnknownEvioDOMNode(), evio::evioDOMNode::evioDOMNode(), evio::evioDOMTree::evioDOMTree(), evio::evioDOMNode::operator!=(), evio::tagNumComp::operator()(), evio::evioDOMNode::operator==(), and evio::evioDictionary::toString().
getParentNum()
uint8_t evioDictEntry::getParentNum (void) const
Get the num of parent entry if any.
Returns
parent num.
getParentTag()
uint16_t evioDictEntry::getParentTag (void) const
Get the tag of parent entry if any.
Returns
parent tag.
getParentTagEnd()
uint16_t evioDictEntry::getParentTagEnd (void) const
Get the tagEnd of parent entry if any.
Returns
parent tagEnd.
getTag()
uint16_t evioDictEntry::getTag (void) const
Get the tag value of this entry.
Returns
tag.
Referenced by evio::evioDOMTree::addBank(), evio::evioDOMNode::createEvioDOMNode(), evio::evioDOMNode::createUnknownEvioDOMNode(), evio::evioDOMNode::evioDOMNode(), evio::evioDOMTree::evioDOMTree(), evio::evioDOMNode::operator!=(), evio::tagNumComp::operator()(), evio::evioDOMNode::operator==(), and evio::evioDictionary::toString().
getTagEnd()
uint16_t evioDictEntry::getTagEnd (void) const
Get the ending value of a tag range defined by this entry.
Since
5.2
Returns
tagEnd.
getType()
DataType evioDictEntry::getType (void) const
Get the data type of this entry.
Since
5.2
Returns
DataType enum describing type of data.
hasParent()
bool evioDictEntry::hasParent (void) const
Does this entry have a valid parent entry?
Returns
true if valid parent entry, else false.
inRange()
bool evioDictEntry::inRange (uint16_t tagArg)
Is the given tag within the specified range (inclusive) of this dictionary entry?
Since
5.2
Parameters
tagArg tag to compare with range
Returns
false
if tag not in range or this entry does not define a range, else
true
.
References evio::TAG_RANGE.
Referenced by evio::evioDictionary::getName().
isNumUndefined()
bool evioDictEntry::isNumUndefined (void) const
Get whether num is undefined.
Since
5.2
Returns
true if tag-only or tag-range, else false.
operator<()
bool evio::evioDictEntry::operator< (const evioDictEntry & tn) const inline
operator==()
bool evio::evioDictEntry::operator== (const evioDictEntry & tn) const inline
toString()
string evioDictEntry::toString (void) const throw (evioException)
Create a string representation of this object.
Returns
string representation of this object.
Friends And Related Function Documentation
evioDictionary
friend class evioDictionary friend
The documentation for this class was generated from the following files:
evioDictEntry.hxx
evioDictEntry.cc