evio: evio::evioDOMContainerNode Class Reference
evio::evioDOMContainerNode Class Reference
Sub-class of evioDOMNode represents an evio container node.
#include <evioUtil.hxx>
Public Member Functions
virtual string getHeader (int depth, const evioToStringConfig *config=&defaultToStringConfig) const
Returns XML string containing header needed for toString() and related methods.
virtual string getBody (int depth, const evioToStringConfig *config=&defaultToStringConfig) const
Returns empty body for container node.
virtual string getFooter (int depth, const evioToStringConfig *config=&defaultToStringConfig) const
Returns XML string containing footer needed by toString.
virtual int getSize () const
Returns number of children of this container node.
Public Member Functions inherited from evio::evioDOMNode
virtual ~evioDOMNode ()=default
virtual void addNode (evioDOMNodeP node)
Adds node to container node.
void append (const string &s)
Appends string to leaf node.
void append (const char *s)
Appends const char* to leaf node.
void append (char *s)
Appends char* to leaf node.
void append (const char **ca, int len)
Appends array of const char* to leaf node.
void append (char **ca, int len)
Appends array of const char* to leaf node.
template<typename T >
void append (T tVal)
template<typename T >
void append (const vector< T > &tVec)
template<typename T >
void append (const T *tBuf, int len)
template<typename T >
void replace (const vector< T > &tVec)
template<typename T >
void replace (const T *tBuf, int len)
virtual evioDOMNodeP cut ()
Cleanly removes node from tree or node hierarchy.
virtual void cutAndDelete ()
Cleanly removes node from tree or node hierarchy and recursively deletes node and its contents.
virtual evioDOMNodeP move (evioDOMNodeP newParent)
Changes node parent.
virtual bool operator== (uint16_t tag) const
True if node tag equals value.
virtual bool operator!= (uint16_t tag) const
True if node tag does not equal value.
bool operator== (evioDictEntry tnPair) const
True if node tag and num same as in evioDictEntry pair.
bool operator!= (evioDictEntry tnPair) const
True if node tag and num NOT the same as in evioDictEntry pair.
evioDOMNode & operator<< (evioDOMNodeP node)
Adds node to container node.
evioDOMNode & operator<< (const string &s)
Appends single string to leaf node.
evioDOMNode & operator<< (const char *s)
Appends single const char* to leaf node.
evioDOMNode & operator<< (char *s)
Appends single char* to leaf node.
template<typename T >
evioDOMNode & operator<< (T tVal)
template<typename T >
evioDOMNode & operator<< (const vector< T > &tVec)
evioDOMNodeList * getChildList ()
Returns pointer to child list of container node.
evioDOMNodeListP getChildren ()
Returns copy of child list of container node.
template<class Predicate >
evioDOMNodeListP getChildren (Predicate pred)
template<typename T >
vector< T > * getVector ()
virtual string toString () const
Returns XML string listing container node contents.
evioDOMNodeP getParent () const
Returns parent evioDOMNode.
int getContentType () const
Returns content type.
evioDOMTree * getParentTree () const
Returns parent evioDOMTree.
bool isContainer () const
True if node is a container node.
bool isLeaf () const
True if node is a leaf node.
Public Attributes
evioDOMNodeList childList
STL List of pointers to children.
Public Attributes inherited from evio::evioDOMNode
uint16_t tag
The node tag, max 16-bits depending on container type.
uint8_t num
The node num, max 8 bits, used by BANK and String container types (2-word header).
Protected Member Functions
evioDOMContainerNode (evioDOMNodeP parent, uint16_t tag, uint8_t num, ContainerType cType)
Container node constructor used internally.
virtual ~evioDOMContainerNode ()
Destructor recursively deletes children.
evioDOMContainerNode (const evioDOMContainerNode &cNode)
bool operator= (const evioDOMContainerNode &node)
Protected Member Functions inherited from evio::evioDOMNode
evioDOMNode (evioDOMNodeP parent, uint16_t tag, uint8_t num, int contentType)
Container node constructor used internally.
evioDOMNode (evioDOMNodeP parent, const string &name, const evioDictionary *dictionary, int contentType)
Container node constructor used internally.
Friends
class evioDOMNode
Allows evioDOMNode to use private subclass methods.
Additional Inherited Members
Static Public Member Functions inherited from evio::evioDOMNode
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, ContainerType cType=BANK)
Static factory method to create container node.
template<typename T >
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num)
template<typename T >
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, const vector< T > &tVec)
template<typename T >
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, const T *t, int len)
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, const evioSerializable &o, ContainerType cType=BANK)
Static factory method to create container node holding evioSerializable object.
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, void(*f)(evioDOMNodeP c, void *userArg), void *userArg, ContainerType cType=BANK)
Static factory method to create container node using C function to fill container.
template<typename T >
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, T *t, void *userArg, ContainerType cType=BANK)
template<typename T >
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, T *t, void *T::*mfp(evioDOMNodeP c, void *userArg), void *userArg, ContainerType cType=BANK)
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, uint16_t formatTag, const string &formatString, uint16_t dataTag, uint8_t dataNum, const vector< uint32_t > &tVec)
Static factory method to create composite leaf node.
static evioDOMNodeP createEvioDOMNode (uint16_t tag, uint8_t num, uint16_t formatTag, const string &formatString, uint16_t dataTag, uint8_t dataNum, const uint32_t *t, int len)
Static factory method to create composite leaf node.
static evioDOMNodeP createUnknownEvioDOMNode (uint16_t tag, uint8_t num, const vector< uint32_t > &tVec)
Unknown type node constructor used internally.
static evioDOMNodeP createUnknownEvioDOMNode (uint16_t tag, uint8_t num, const uint32_t *t, int len)
Unknown type node constructor used internally.
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, ContainerType cType=BANK)
Static factory method to create container node.
template<typename T >
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary)
template<typename T >
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, const vector< T > &tVec)
template<typename T >
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, const T *t, int len)
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, const evioSerializable &o, ContainerType cType=BANK)
Static factory method to create container node holding evioSerializable object.
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, void(*f)(evioDOMNodeP c, void *userArg), void *userArg, ContainerType cType=BANK)
Static factory method to create container node using C function to fill container.
template<typename T >
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, T *t, void *userArg, ContainerType cType=BANK)
template<typename T >
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, T *t, void *T::*mfp(evioDOMNodeP c, void *userArg), void *userArg, ContainerType cType=BANK)
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, uint16_t formatTag, const string &formatString, uint16_t dataTag, uint8_t dataNum, const vector< uint32_t > &tVec)
Static factory method to create composite leaf node.
static evioDOMNodeP createEvioDOMNode (const string &name, const evioDictionary *dictionary, uint16_t formatTag, const string &formatString, uint16_t dataTag, uint8_t dataNum, const uint32_t *t, int len)
Static factory method to create composite leaf node.
static evioDOMNodeP createUnknownEvioDOMNode (const string &name, const evioDictionary *dictionary, const vector< uint32_t > &tVec)
Unknown type node constructor used internally.
static evioDOMNodeP createUnknownEvioDOMNode (const string &name, const evioDictionary *dictionary, const uint32_t *t, int len)
Unknown type node constructor used internally.
Static Protected Member Functions inherited from evio::evioDOMNode
static string getIndent (int depth, int size=3)
Returns indent for pretty-printing, used internally.
Protected Attributes inherited from evio::evioDOMNode
evioDOMNodeP parent
Pointer to node parent.
evioDOMTree * parentTree
Pointer to parent tree if this node is the root.
int contentType
Content type.
Detailed Description
Sub-class of evioDOMNode represents an evio container node.
Only accessible to users via pointer to evioDOMNode object.
Constructor & Destructor Documentation
evioDOMContainerNode() [1/2]
evioDOMContainerNode::evioDOMContainerNode (evioDOMNodeP par, uint16_t tg, uint8_t num, ContainerType cType) protected
Container node constructor used internally.
Parameters
par Parent node
tg Node tag
num Node num
cType Container node content type
~evioDOMContainerNode()
evioDOMContainerNode::~evioDOMContainerNode () protected virtual
Destructor recursively deletes children.
References childList.
evioDOMContainerNode() [2/2]
evio::evioDOMContainerNode::evioDOMContainerNode (const evioDOMContainerNode & cNode) protected
Member Function Documentation
getBody()
string evioDOMContainerNode::getBody (int depth, const evioToStringConfig * config = &defaultToStringConfig) const virtual
Returns empty body for container node.
Parameters
depth Current depth
Returns
Empty string
Implements evio::evioDOMNode.
getFooter()
string evioDOMContainerNode::getFooter (int depth, const evioToStringConfig * config = &defaultToStringConfig) const virtual
Returns XML string containing footer needed by toString.
Parameters
depth Current depth
Returns
XML string
Implements evio::evioDOMNode.
References evio::BANK, evio::evioDOMNode::getContentType(), evio::evioDOMNode::getIndent(), evio::evioDictionary::getNameMap, evio::evioToStringConfig::indentSize, evio::evioDOMNode::num, evio::evioDOMNode::parent, evio::evioDOMNode::tag, and evio::evioToStringConfig::toStringDictionary.
getHeader()
string evioDOMContainerNode::getHeader (int depth, const evioToStringConfig * config = &defaultToStringConfig) const virtual
Returns XML string containing header needed for toString() and related methods.
Parameters
depth Current depth
Returns
XML string
Implements evio::evioDOMNode.
References evio::BANK, evio::evioDOMNode::contentType, evio::evioDOMNode::getContentType(), evio::evioDOMNode::getIndent(), evio::evioDictionary::getNameMap, getSize(), evio::evioToStringConfig::indentSize, evio::evioDOMNode::num, evio::evioDOMNode::parent, evio::evioDOMNode::tag, evio::evioToStringConfig::toStringDictionary, and evio::evioToStringConfig::verbose.
getSize()
int evioDOMContainerNode::getSize () const virtual
Returns number of children of this container node.
Returns
Number of children of this container node
Implements evio::evioDOMNode.
References childList.
Referenced by getHeader().
operator=()
bool evio::evioDOMContainerNode::operator= (const evioDOMContainerNode & node) protected
Friends And Related Function Documentation
evioDOMNode
friend class evioDOMNode friend
Allows evioDOMNode to use private subclass methods.
Member Data Documentation
childList
evioDOMNodeList evio::evioDOMContainerNode::childList
STL List of pointers to children.
Referenced by evio::evioDOMTree::addBank(), evio::evioDOMNode::cut(), getSize(), evio::evioDOMNode::move(), and ~evioDOMContainerNode().
The documentation for this class was generated from the following files:
evioUtil.hxx
evioUtil.cc