evio: evio::ByteOrder Class Reference
evio::ByteOrder Class Reference
Numerical values associated with endian byte order.
#include <ByteOrder.h>
Public Member Functions
std::string getName () const
Get the object name.
bool isBigEndian () const
Is this big endian?
bool isLittleEndian () const
Is this little endian?
bool isLocalEndian () const
Is this endian same as the local host?
ByteOrder getOppositeEndian () const
Get the oppposite endian (little if this is big and vice versa).
bool operator== (const ByteOrder &rhs) const
bool operator!= (const ByteOrder &rhs) const
Static Public Member Functions
static ByteOrder const & getLocalByteOrder ()
Get the byte order of the local host.
static ByteOrder const & nativeOrder ()
Get the byte order of the local host.
static bool isLocalHostBigEndian ()
Is the local host big endian?
static bool needToSwap (ByteOrder &order)
Is the argument the opposite of the local host's endian?
template<typename T >
static void byteSwapInPlace (T &var)
Templated method to swap data in place.
template<typename T >
static void byteSwapInPlace (T &var, size_t elements)
Templated method to swap array data in place.
template<typename T >
static void byteSwapInPlace (T *var, size_t elements)
Templated method to swap array data in place.
static float byteSwap (float var)
Convenience method to return swapped float.
static double byteSwap (double var)
Convenience method to return swapped double.
static uint16_t * byteSwap16 (uint16_t *src, size_t elements, uint16_t *dst)
This method swaps an array of 2-byte data.
static uint32_t * byteSwap32 (uint32_t *src, size_t elements, uint32_t *dst)
This method swaps an array of 4-byte data.
static uint64_t * byteSwap64 (uint64_t *src, size_t elements, uint64_t *dst)
This method swaps an array of 8-byte data.
static void byteNoSwap32 (const uint32_t *src, size_t elements, uint32_t *dst)
This routine swaps nothing, it just copies the given number of 32 bit ints.
Static Public Attributes
static const ByteOrder ENDIAN_LITTLE
Little endian byte order.
static const ByteOrder ENDIAN_BIG
Big endian byte order.
static const ByteOrder ENDIAN_UNKNOWN
Unknown endian byte order.
static const ByteOrder ENDIAN_LOCAL = ByteOrder::getLocalByteOrder()
Local host's byte order.
Detailed Description
Numerical values associated with endian byte order.
Version
6.0
Since
6.0 4/16/2019
Author
timmer
Member Function Documentation
byteNoSwap32()
void evio::ByteOrder::byteNoSwap32 (const uint32_t * src, size_t elements, uint32_t * dst) static
This routine swaps nothing, it just copies the given number of 32 bit ints.
If source pointer is null, nothing is done.
Parameters
src pointer to data to be copied
elements number of 32 bit ints to be copied
dst pointer to where data is to be copied to. If null, nothing is done.
Referenced by evio::EvioSwap::swapData().
byteSwap() [1/2]
double evio::ByteOrder::byteSwap (double var) static
Convenience method to return swapped double.
Parameters
var double to swap
Returns
swapped double.
byteSwap() [2/2]
float evio::ByteOrder::byteSwap (float var) static
Convenience method to return swapped float.
Parameters
var float to swap
Returns
swapped float.
Referenced by evio::ByteBuffer::getDouble(), evio::ByteBuffer::getFloat(), evio::ByteBuffer::putDouble(), and evio::ByteBuffer::putFloat().
byteSwap16()
uint16_t * evio::ByteOrder::byteSwap16 (uint16_t * src, size_t elements, uint16_t * dst) static
This method swaps an array of 2-byte data.
If source pointer is null, nothing is done. If destination pointer is null, src is swapped in place.
Parameters
src pointer to data source.
elements number of 2-byte elements to swap.
dst pointer to destination or nullptr if data is to be swapped in place.
Returns
pointer to beginning of swapped data; null if src is null.
References SWAP_16.
Referenced by evio::EvioSwap::swapData(), evio::BaseStructure::updateShortData(), evio::BaseStructure::updateUShortData(), and evio::BaseStructure::write().
byteSwap32()
uint32_t * evio::ByteOrder::byteSwap32 (uint32_t * src, size_t elements, uint32_t * dst) static
This method swaps an array of 4-byte data.
If source pointer is null, nothing is done. If destination pointer is null, src is swapped in place.
Parameters
src pointer to data source.
elements number of 4-byte elements to swap.
dst pointer to destination or nullptr if data is to be swapped in place.
Returns
pointer to beginning of swapped data; null if src is null.
References SWAP_32.
Referenced by evio::EvioSwap::swapBank(), evio::EvioSwap::swapData(), evio::EvioSwap::swapSegment(), evio::EvioSwap::swapTagsegment(), evio::BaseStructure::updateFloatData(), evio::BaseStructure::updateIntData(), evio::BaseStructure::updateUIntData(), and evio::BaseStructure::write().
byteSwap64()
uint64_t * evio::ByteOrder::byteSwap64 (uint64_t * src, size_t elements, uint64_t * dst) static
This method swaps an array of 8-byte data.
If source pointer is null, nothing is done. If destination pointer is null, src is swapped in place.
Parameters
src pointer to data source.
elements number of 8-byte elements to swap.
dst pointer to destination or nullptr if data is to be swapped in place.
Returns
pointer to beginning of swapped data; null if src is null.
References SWAP_64.
Referenced by evio::EvioSwap::swapData(), evio::BaseStructure::updateDoubleData(), evio::BaseStructure::updateLongData(), evio::BaseStructure::updateULongData(), and evio::BaseStructure::write().
byteSwapInPlace() [1/3]
template<typename T > void evio::ByteOrder::byteSwapInPlace (T & var) static
Templated method to swap data in place.
Template Parameters
T type of data.
Parameters
var reference to data to be swapped.
byteSwapInPlace() [2/3]
template<typename T > void evio::ByteOrder::byteSwapInPlace (T & var, size_t elements) static
Templated method to swap array data in place.
Template Parameters
T data type.
Parameters
var reference to data to be swapped.
elements number of data elements to be swapped.
byteSwapInPlace() [3/3]
template<typename T > void evio::ByteOrder::byteSwapInPlace (T * var, size_t elements) static
Templated method to swap array data in place.
If source pointer is null, nothing is done.
Template Parameters
T data type.
Parameters
var pointer to data to be swapped.
elements number of data elements to be swapped.
getLocalByteOrder()
static ByteOrder const& evio::ByteOrder::getLocalByteOrder () inline static
Get the byte order of the local host.
Returns
byte order of the local host.
References ENDIAN_BIG, ENDIAN_LITTLE, and isLocalHostBigEndian().
Referenced by nativeOrder(), and needToSwap().
getName()
std::string evio::ByteOrder::getName () const inline
Get the object name.
Returns
the object name.
getOppositeEndian()
ByteOrder evio::ByteOrder::getOppositeEndian () const inline
Get the oppposite endian (little if this is big and vice versa).
Returns
he oppposite endian.
References ENDIAN_BIG, ENDIAN_LITTLE, and isBigEndian().
Referenced by evio::EvioReaderV4::parseFirstHeader().
isBigEndian()
bool evio::ByteOrder::isBigEndian () const inline
Is this big endian?
Returns
true if big endian, else false.
References ENDIAN_BIG.
Referenced by getOppositeEndian().
isLittleEndian()
bool evio::ByteOrder::isLittleEndian () const inline
Is this little endian?
Returns
true if little endian, else false.
References ENDIAN_LITTLE.
Referenced by evio::ByteBuffer::ByteBuffer().
isLocalEndian()
bool evio::ByteOrder::isLocalEndian () const inline
Is this endian same as the local host?
Returns
true if endian is the same as the local host, else false.
References ENDIAN_LOCAL.
Referenced by evio::CompactEventBuilder::addDoubleData(), evio::CompactEventBuilder::addFloatData(), evio::CompactEventBuilder::addIntData(), evio::CompactEventBuilder::addLongData(), evio::CompactEventBuilder::addShortData(), and evio::BaseStructure::write().
isLocalHostBigEndian()
static bool evio::ByteOrder::isLocalHostBigEndian () inline static
Is the local host big endian?
Returns
true if the local host is big endian, else false.
Referenced by getLocalByteOrder().
nativeOrder()
static ByteOrder const& evio::ByteOrder::nativeOrder () inline static
Get the byte order of the local host.
Returns
byte order of the local host.
References getLocalByteOrder().
needToSwap()
static bool evio::ByteOrder::needToSwap (ByteOrder & order) inline static
Is the argument the opposite of the local host's endian?
Parameters
order byte order to compare to local host's.
Returns
true if the argument is the opposite of the local host's endian.
References getLocalByteOrder().
Referenced by evio::BaseStructure::updateDoubleData(), evio::BaseStructure::updateFloatData(), evio::BaseStructure::updateIntData(), evio::BaseStructure::updateLongData(), evio::BaseStructure::updateShortData(), evio::BaseStructure::updateUIntData(), evio::BaseStructure::updateULongData(), and evio::BaseStructure::updateUShortData().
operator!=()
bool evio::ByteOrder::operator!= (const ByteOrder & rhs) const
operator==()
bool evio::ByteOrder::operator== (const ByteOrder & rhs) const
Member Data Documentation
ENDIAN_BIG
const ByteOrder evio::ByteOrder::ENDIAN_BIG static
Big endian byte order.
Referenced by evio::EvioCompactReaderV4::addStructure(), evio::Util::findEvioVersion(), getLocalByteOrder(), getOppositeEndian(), isBigEndian(), evio::CompactEventBuilder::openBank(), evio::CompactEventBuilder::openSegment(), evio::CompactEventBuilder::openTagSegment(), evio::FileHeader::readHeader(), evio::EvioCompactReaderV4::removeStructure(), evio::CompactEventBuilder::setTopLevelTag(), evio::Util::toBytes(), evio::Util::toInt(), evio::Util::toLong(), evio::EvioNode::updateLengths(), evio::EvioNode::updateNum(), and evio::EvioNode::updateTag().
ENDIAN_LITTLE
const ByteOrder evio::ByteOrder::ENDIAN_LITTLE static
Little endian byte order.
Referenced by evio::Util::findEvioVersion(), getLocalByteOrder(), getOppositeEndian(), isLittleEndian(), evio::ByteBuffer::order(), and evio::FileHeader::readHeader().
ENDIAN_LOCAL
const ByteOrder evio::ByteOrder::ENDIAN_LOCAL = ByteOrder::getLocalByteOrder() static
Local host's byte order.
Referenced by evio::Writer::close(), evio::WriterMT::close(), isLocalEndian(), evio::BaseStructure::needSwap(), and evio::ByteBuffer::order().
ENDIAN_UNKNOWN
const ByteOrder evio::ByteOrder::ENDIAN_UNKNOWN static
Unknown endian byte order.
The documentation for this class was generated from the following files:
ByteOrder.h
ByteOrder.cpp