# scons build file for evio
Import('env', 'archDir', 'incInstallDir', 'libInstallDir', 'binInstallDir', 'archIncInstallDir', 'execLibs', 'debugSuffix', 'disruptorHome')

# Headers to install
headerList = Glob('*.h', strings=True)

# Files to compile
#fileList = Glob('*.cpp',  strings=True, exclude=['ReadWriteTest.cpp', 'EventWriter.cpp', 'EventWriter.h'])
fileList = Glob('*.cpp',  strings=True, exclude=['ReadWriteTest.cpp'])

env.AppendUnique(CPPPATH = ['#src/hipo', disruptorHome, '/usr/include/boost'])

#evioNewLib = env.StaticLibrary(target = 'hipo'+debugSuffix, source = fileList)
evioNewLib = env.SharedLibrary(target = 'hipo'+debugSuffix, source = fileList)

if 'install' in COMMAND_LINE_TARGETS:
    env.Alias("install", env.Install(target = [incInstallDir, archIncInstallDir], source = headerList))
    env.Alias("install", env.Install(target = libInstallDir, source = evioNewLib))

# Compile C++ files and install

compiledFile = env.Program(source  = 'ReadWriteTest.cpp',
                           LIBS    = ['hipo'+debugSuffix, 'Disruptor',
                                      'boost_system', 'boost_thread',  'boost_chrono',  execLibs],
                           LIBPATH = ['#src/hipo/'+archDir, disruptorHome+'/build/Disruptor'],
                           CPPPATH = ['#src/hipo', disruptorHome, '/usr/include/boost'])

if 'install' in COMMAND_LINE_TARGETS:
    env.Alias('install', env.Install(target = binInstallDir, source = compiledFile))
