evio: evio::RecordHeader Class Reference
evio::RecordHeader Class Reference
#include <RecordHeader.h>
Public Member Functions
RecordHeader ()
Default, no-arg constructor.
RecordHeader (const RecordHeader &head)
Copy constructor.
RecordHeader (const HeaderType &type)
Constructor which sets the type of header this is.
RecordHeader (size_t pos, uint32_t len, uint32_t ent)
Constructor.
~RecordHeader ()=default
RecordHeader & operator= (const RecordHeader &head)
void copy (std::shared_ptr< RecordHeader > const &head)
Copy method.
void reset ()
Reset generated data.
const HeaderType & getHeaderType () const
Get the type of header this is.
uint32_t getUncompressedRecordLength () const
Get the padded length in bytes of the entire uncompressed record.
uint32_t getCompressedRecordLength () const
Get the padded length in bytes of the entire compressed record.
uint32_t getLength () const
Get the total length of this record in bytes.
uint32_t getLengthWords () const
Get the total length of this record in 32 bit words.
uint32_t getEntries () const
Get the number of events or entries in index.
uint32_t getUserHeaderLength () const
Get the length of the user-defined header in bytes.
uint32_t getUserHeaderLengthWords () const
Get the length of the user-defined header in words.
uint32_t getDataLength () const
Get the length of the uncompressed data in bytes.
uint32_t getDataLengthWords () const
Get the length of the uncompressed data in words (padded).
uint32_t getIndexLength () const
Get the length of the index array in bytes.
uint32_t getCompressedDataLength () const
Get the length of the compressed data in bytes.
uint32_t getCompressedDataLengthPadding () const
Get the padding of the compressed data in bytes.
uint32_t getCompressedDataLengthWords () const
Get the length of the compressed data in words (padded).
uint32_t getHeaderLength () const
Get the length of this header in bytes (NOT including user header or index).
uint32_t getRecordNumber () const
Get the record number.
uint64_t getUserRegisterFirst () const
Get the first user-defined 64-bit register.
uint64_t getUserRegisterSecond () const
Get the second user-defined 64-bit register.
size_t getPosition () const
Get the position of this record in a file.
Compressor::CompressionType getCompressionType () const
Get the type of compression used.
uint32_t setBitInfo (bool isLastRecord, bool haveFirstEvent, bool haveDictionary)
Set the bit info word for a record header.
uint32_t getBitInfoWord () const
Get the bit info word.
void setBitInfoWord (uint32_t word)
Set the bit info word and related values.
void setBitInfoWord (std::bitset< 24 > const &set)
Set the bit info word and related values.
uint32_t hasFirstEvent (bool hasFirst)
Set the bit which says record has a first event in the user header.
uint32_t hasDictionary (bool hasFirst)
Set the bit which says record has a dictionary in the user header.
uint32_t isLastRecord (bool isLast)
Set the bit which says record is last in file/buffer.
bool isLastRecord () const
Is this the header of the last record?
bool isCompressed () const
Does this header indicate compressed data?
bool isEvioTrailer () const
Is this header an evio trailer?
bool isEvioRecord () const
Is this header an evio record?
bool isHipoTrailer () const
Is this header a hipo trailer?
bool isHipoRecord () const
Is this header a hipo record?
uint32_t setBitInfoEventType (uint32_t type)
Set the bit info of a record header for a specified CODA event type.
RecordHeader & setHeaderType (HeaderType const &type)
Set this header's type.
RecordHeader & setPosition (size_t pos)
Set the position of this record in a file.
RecordHeader & setRecordNumber (uint32_t num)
Set the record number.
RecordHeader & setLength (uint32_t length)
Set the record length in bytes & words.
RecordHeader & setDataLength (uint32_t length)
Set the uncompressed data length in bytes & words and the padding.
RecordHeader & setCompressedDataLength (uint32_t length)
Set the compressed data length in bytes & words and the padding.
RecordHeader & setIndexLength (uint32_t length)
Set the length of the index array in bytes.
RecordHeader & setCompressionType (Compressor::CompressionType type)
Set the compression type.
RecordHeader & setEntries (uint32_t n)
Set the number of events or index entries.
RecordHeader & setUserHeaderLength (uint32_t length)
Set the user-defined header's length in bytes & words and the padding.
RecordHeader & setHeaderLength (uint32_t length)
Set the this header's length in bytes & words.
RecordHeader & setUserRegisterFirst (uint64_t reg)
Set the first, 64-bit, user-defined register.
RecordHeader & setUserRegisterSecond (uint64_t reg)
Set the second, 64-bit, user-defined register.
void writeHeader (ByteBuffer &buf, size_t off=0)
Writes this header into the given byte buffer.
void writeHeader (std::shared_ptr< ByteBuffer > &buffer, size_t off=0)
Writes this header into the given byte buffer.
void writeHeader (uint8_t *array, const ByteOrder &order)
Writes this header at the given pointer.
void readHeader (ByteBuffer &buffer, size_t offset=0)
Reads the header information from a byte buffer and validates it by checking the magic word (8th word).
void readHeader (std::shared_ptr< ByteBuffer > &buffer, size_t offset=0)
Reads the header information from a byte buffer and validates it by checking the magic word (8th word).
void readHeader (uint8_t *src, ByteOrder order)
Reads the header information from a byte buffer and validates it by checking the magic word (8th word).
std::string eventTypeToString () const
Return a meaningful string associated with event type.
uint32_t getSize () override
Get the size of the record)in 32 bit words.
uint32_t getNumber () override
Get the block number for this record) In a file, this is usually sequential.
uint32_t getHeaderWords () override
Get the length of this header in words.
uint32_t getSourceId () override
Get the source ID number if in CODA online context and data is coming from ROC.
bool hasFirstEvent () override
Does this header have a first event in the user header?
uint32_t getEventType () override
Get the type of events in record (see values of DataType.
uint32_t getVersion () override
Get the Evio format version number.
uint32_t getMagicNumber () override
Get the magic number the record)header which should be 0xc0da0100.
ByteOrder & getByteOrder () override
Get the byte order of the file/buffer this header was read from.
bool hasDictionary () override
Does this record have a dictionary in the user header?
bool isLastBlock () override
Is this the last record in the file or being sent over the network?
std::string toString () override
Returns a string representation of this record.
size_t write (ByteBuffer &byteBuffer) override
Write myself out into a byte buffer.
size_t getBufferEndingPosition () override
Get the position in the buffer (bytes) of this record's last data word.
size_t getBufferStartingPosition () override
Get the starting position in the buffer (bytes) from which this header was read–if that happened.
void setBufferStartingPosition (size_t bufferStartingPosition) override
Set the starting position in the buffer (bytes) from which this header was read–if that happened.
size_t nextBufferStartingPosition () override
Determines where the start of the next record header in some buffer is located (bytes).
size_t firstEventStartingPosition () override
Determines where the start of the first event in this record is located (bytes).
size_t bytesRemaining (size_t pos) override
Gives the bytes remaining in this record given a buffer position.
int main (int argc, char **argv)
Run this class as an executable which tests the writing and reading of a record.
Static Public Member Functions
static uint32_t getWords (uint32_t length)
Returns length padded to 4-byte boundary for given length in bytes.
static uint32_t getPadding (uint32_t length)
Returns number of bytes needed to pad to 4-byte boundary for the given length.
static uint32_t generateSixthWord (std::bitset< 24 > const &set)
Calculates the sixth word of this header which has the version number (6) in the lowest 8 bits and the set in the upper 24 bits.
static uint32_t generateSixthWord (uint32_t version, bool hasDictionary, bool isEnd, uint32_t eventType)
Calculates the sixth word of this header which has the version number in the lowest 8 bits.
static uint32_t generateSixthWord (std::bitset< 24 > const &set, uint32_t version, bool hasDictionary, bool isEnd, uint32_t eventType, uint32_t headerType=0)
Calculates the sixth word of this header which has the version number (4) in the lowest 8 bits and the set in the upper 24 bits.
static bool hasDictionary (int bitInfo)
Does this bitInfo arg indicate the existence of a dictionary in the user header?
static bool isLastRecord (uint32_t bitInfo)
Does this word indicate this is the header of the last record?
static bool isEvioTrailer (uint32_t bitInfo)
Does this arg indicate its header is an evio trailer?
static bool isEvioRecord (uint32_t bitInfo)
Does this arg indicate its header is an evio record?
static bool isHipoTrailer (uint32_t bitInfo)
Does this arg indicate its header is a hipo trailer?
static bool isHipoRecord (uint32_t bitInfo)
Does this arg indicate its header is a hipo record?
static uint32_t clearLastRecordBit (uint32_t i)
Clear the bit in the given arg to indicate it is NOT the last record.
static void writeTrailer (uint8_t *array, size_t arrayLen, uint32_t recordNum, const ByteOrder &order, const std::shared_ptr< std::vector< uint32_t >> &recordLengths=nullptr)
Writes a trailer with an optional index array into the given byte array.
static void writeTrailer (std::vector< uint8_t > &array, size_t off, uint32_t recordNum, const ByteOrder &order, const std::shared_ptr< std::vector< uint32_t >> &recordLengths=nullptr)
Writes a trailer with an optional index array into the given vector.
static void writeTrailer (ByteBuffer &buf, size_t off, uint32_t recordNum, const std::shared_ptr< std::vector< uint32_t >> &recordLengths=nullptr)
Writes a trailer with an optional index array into the given buffer.
static void writeTrailer (std::shared_ptr< ByteBuffer > &buf, size_t off, uint32_t recordNum, const std::shared_ptr< std::vector< uint32_t >> &recordLengths=nullptr)
Writes a trailer with an optional index array into the given buffer.
static bool isCompressed (ByteBuffer &buffer, size_t offset)
Quickly check to see if this buffer contains compressed data or not.
static bool isCompressed (std::shared_ptr< ByteBuffer > &buffer, size_t offset)
Quickly check to see if this buffer contains compressed data or not.
Static Public Attributes
static const uint32_t HEADER_SIZE_WORDS = 14
Number of 32-bit words in a normal sized header.
static const uint32_t HEADER_SIZE_BYTES = 56
Number of bytes in a normal sized header.
static const uint32_t HEADER_MAGIC = 0xc0da0100
Magic number used to track endianness.
static const uint32_t RECORD_LENGTH_OFFSET = 0
Byte offset from beginning of header to the record length.
static const uint32_t RECORD_NUMBER_OFFSET = 4
Byte offset from beginning of header to the record number.
static const uint32_t HEADER_LENGTH_OFFSET = 8
Byte offset from beginning of header to the header length.
static const uint32_t EVENT_COUNT_OFFSET = 12
Byte offset from beginning of header to the event index count.
static const uint32_t INDEX_ARRAY_OFFSET = 16
Byte offset from beginning of header to the index array length.
static const uint32_t BIT_INFO_OFFSET = 20
Byte offset from beginning of header to bit info word.
static const uint32_t USER_LENGTH_OFFSET = 24
Byte offset from beginning of header to the user header length.
static const uint32_t MAGIC_OFFSET = 28
Byte offset from beginning of header to the magic number.
static const uint32_t UNCOMPRESSED_LENGTH_OFFSET = 32
Byte offset from beginning of header to the uncompressed data length.
static const uint32_t COMPRESSION_TYPE_OFFSET = 36
Byte offset from beginning of header to the compression type & compressed data length word.
static const uint32_t REGISTER1_OFFSET = 40
Byte offset from beginning of header to the user register #1.
static const uint32_t REGISTER2_OFFSET = 48
Byte offset from beginning of header to the user register #2.
static const uint32_t DICTIONARY_BIT = 0x100
8th bit set in bitInfo word in header means contains dictionary.
static const uint32_t FIRST_EVENT_BIT = 0x200
9th bit set in bitInfo word in header means every split file has same first event.
static const uint32_t LAST_RECORD_BIT = 0x400
10th bit set in bitInfo word in header means is last in stream or file.
static const uint32_t DATA_ROC_RAW_BITS = 0x000
11-14th bits in bitInfo word in header for CODA data type, ROC raw = 0.
static const uint32_t DATA_PHYSICS_BITS = 0x800
11-14th bits in bitInfo word in header for CODA data type, physics = 1.
static const uint32_t DATA_PARTIAL_BITS = 0x1000
11-14th bits in bitInfo word in header for CODA data type, partial physics = 2.
static const uint32_t DATA_DISENTANGLED_BITS = 0x1800
11-14th bits in bitInfo word in header for CODA data type, disentangled = 3.
static const uint32_t DATA_USER_BITS = 0x2000
11-14th bits in bitInfo word in header for CODA data type, user = 4.
static const uint32_t DATA_CONTROL_BITS = 0x2800
11-14th bits in bitInfo word in record header for CODA data type, control = 5.
static const uint32_t DATA_OTHER_BITS = 0x7800
11-14th bits in bitInfo word in record header for CODA data type, other = 15.
static const uint32_t VERSION_MASK = 0xff
Mask to get version number from 6th int in header.
static const uint32_t LAST_RECORD_MASK = 0x400
"Last record" is 11th bit in bitInfo word.
static const uint32_t MAGIC_NUMBER = 0xc0da0100
The magic number, should be the value of magicNumber.
Detailed Description
GENERAL RECORD HEADER STRUCTURE (56 bytes, 14 integers (32 bit))
   +----------------------------------+
 1 |         Record Length            | // 32bit words, inclusive
   +----------------------------------+
 2 +         Record Number            |
   +----------------------------------+
 3 +         Header Length            | // 14 (words)
   +----------------------------------+
 4 +       Event (Index) Count        |
   +----------------------------------+
 5 +      Index Array Length          | // bytes
   +-----------------------+----------+
 6 +       Bit Info        | Version  | // version (8 bits)
   +-----------------------+----------+
 7 +      User Header Length          | // bytes
   +----------------------------------+
 8 +          Magic Number            | // 0xc0da0100
   +----------------------------------+
 9 +     Uncompressed Data Length     | // bytes
   +------+---------------------------+
10 +  CT  |  Data Length Compressed   | // CT = compression type (4 bits); compressed len in words
   +----------------------------------+
11 +          User Register 1         | // UID 1st (64 bits)
   +--                              --+
12 +                                  |
   +----------------------------------+
13 +          User Register 2         | // UID 2nd (64 bits)
   +--                              --+
14 +                                  |
   +----------------------------------+
-------------------
  Compression Type
-------------------
    0  = none
    1  = LZ4 fastest
    2  = LZ4 best
    3  = gzip
-------------------
  Bit Info Word
-------------------
    0-7  = version
    8    = true if dictionary is included (relevant for first record only)
    9    = true if this record has "first" event (to be in every split file)
   10    = true if this record is the last in file or stream
   11-14 = type of events contained: 0 = ROC Raw,
                                     1 = Physics
                                     2 = PartialPhysics
                                     3 = DisentangledPhysics
                                     4 = User
                                     5 = Control
                                    15 = Other
   15-19 = reserved
   20-21 = pad 1
   22-23 = pad 2
   24-25 = pad 3
   26-27 = reserved
   28-31 = general header type: 0 = Evio record,
                                3 = Evio file trailer
                                4 = HIPO record,
                                7 = HIPO file trailer
------------------------------------------------------------
Version
6.0
Since
6.0 4/9/2019
Author
timmer
Constructor & Destructor Documentation
RecordHeader() [1/4]
evio::RecordHeader::RecordHeader ()
Default, no-arg constructor.
RecordHeader() [2/4]
evio::RecordHeader::RecordHeader (const RecordHeader & head)
Copy constructor.
Parameters
head header to copy.
RecordHeader() [3/4]
evio::RecordHeader::RecordHeader (const HeaderType & type) explicit
Constructor which sets the type of header this is.
Parameters
type type of header this is
Exceptions
EvioException if type is for file
RecordHeader() [4/4]
evio::RecordHeader::RecordHeader (size_t pos, uint32_t len, uint32_t ent)
Constructor.
Parameters
pos position in file.
len length of record in bytes
ent number of events
~RecordHeader()
evio::RecordHeader::~RecordHeader () default
Member Function Documentation
bytesRemaining()
size_t evio::RecordHeader::bytesRemaining (size_t pos) override virtual
Gives the bytes remaining in this record given a buffer position.
The position is an absolute position in a byte buffer. This assumes that the absolute position in bufferStartingPosition is being maintained properly by the reader.
Parameters
pos the absolute current position in a byte buffer.
Returns
the number of bytes remaining in this record.
Exceptions
EvioException if position out of bounds
Implements evio::IBlockHeader.
clearLastRecordBit()
uint32_t evio::RecordHeader::clearLastRecordBit (uint32_t i) static
Clear the bit in the given arg to indicate it is NOT the last record.
Parameters
i integer in which to clear the last-record bit
Returns
arg with last-record bit cleared
copy()
void evio::RecordHeader::copy (std::shared_ptr< RecordHeader > const & head)
Copy method.
Parameters
head header to copy.
eventTypeToString()
string evio::RecordHeader::eventTypeToString () const
Return a meaningful string associated with event type.
Returns
a meaningful string associated with event type.
firstEventStartingPosition()
size_t evio::RecordHeader::firstEventStartingPosition () override virtual
Determines where the start of the first event in this record is located (bytes).
This assumes the start position has been maintained by the object performing the buffer read.
Returns
where the start of the first event in this record is located (bytes). In evio format version 2, returns 0 if start is 0, signaling that this entire record is part of a logical record that spans at least three physical records.
Implements evio::IBlockHeader.
generateSixthWord() [1/3]
uint32_t evio::RecordHeader::generateSixthWord (std::bitset< 24 > const & set) static
Calculates the sixth word of this header which has the version number (6) in the lowest 8 bits and the set in the upper 24 bits.
NOT FOR GENERAL USE!
Parameters
set reference to bitset containing all bits to be set
Returns
generated sixth word of this header.
Referenced by evio::CompactEventBuilder::toFile().
generateSixthWord() [2/3]
uint32_t evio::RecordHeader::generateSixthWord (std::bitset< 24 > const & set, uint32_t version, bool hasDictionary, bool isEnd, uint32_t eventType, uint32_t headerType = 0) static
Calculates the sixth word of this header which has the version number (4) in the lowest 8 bits and the set in the upper 24 bits.
The arg isDictionary is set in the 9th bit and isEnd is set in the 10th bit. Four bits of an int (event type) are set in bits 11-14. Four bits of this header type are set in bits 28-31 (defaults to 0 which is an evio record header).
Parameters
set reference to bitset containing all bits to be set
version evio version number
hasDictionary does this block include an evio xml dictionary as the first event?
isEnd is this the last block of a file or a buffer?
eventType 4 bit type of events header is containing
headerType 4 bit type of this header (defaults to 0 which is an evio record header).
Returns
generated sixth word of this header.
generateSixthWord() [3/3]
uint32_t evio::RecordHeader::generateSixthWord (uint32_t version, bool hasDictionary, bool isEnd, uint32_t eventType) static
Calculates the sixth word of this header which has the version number in the lowest 8 bits.
The arg hasDictionary is set in the 9th bit and isEnd is set in the 10th bit. Four bits of an int (event type) are set in bits 11-14.
Parameters
version evio version number
hasDictionary does this block include an evio xml dictionary as the first event?
isEnd is this the last block of a file or a buffer?
eventType 4 bit type of events header is containing
Returns
generated sixth word of this header.
getBitInfoWord()
uint32_t evio::RecordHeader::getBitInfoWord () const
Get the bit info word.
Will initialize if not already done.
Returns
bit info word.
Referenced by evio::RecordInput::uncompressRecord().
getBufferEndingPosition()
size_t evio::RecordHeader::getBufferEndingPosition () override virtual
Get the position in the buffer (bytes) of this record's last data word.
Returns
position in the buffer (bytes) of this record's last data word.
Implements evio::IBlockHeader.
getBufferStartingPosition()
size_t evio::RecordHeader::getBufferStartingPosition () override virtual
Get the starting position in the buffer (bytes) from which this header was read–if that happened.
This is not part of the record header proper. It is a position in a memory buffer of the start of the record It is kept for convenience. It is up to the reader to set it.
Returns
starting position in buffer (bytes) from which this header was read–if that happened.
Implements evio::IBlockHeader.
getByteOrder()
ByteOrder & evio::RecordHeader::getByteOrder () override virtual
Get the byte order of the file/buffer this header was read from.
Defaults to little endian.
Returns
byte order of the file/buffer this header was read from.
Implements evio::IBlockHeader.
Referenced by evio::Reader::scanBuffer(), and evio::Reader::scanUncompressedBuffer().
getCompressedDataLength()
uint32_t evio::RecordHeader::getCompressedDataLength () const
Get the length of the compressed data in bytes.
Returns
length of the compressed data in bytes.
Referenced by evio::RecordInput::uncompressRecord().
getCompressedDataLengthPadding()
uint32_t evio::RecordHeader::getCompressedDataLengthPadding () const
Get the padding of the compressed data in bytes.
Returns
padding of the compressed data in bytes.
getCompressedDataLengthWords()
uint32_t evio::RecordHeader::getCompressedDataLengthWords () const
Get the length of the compressed data in words (padded).
Returns
length of the compressed data in words (padded).
Referenced by main().
getCompressedRecordLength()
uint32_t evio::RecordHeader::getCompressedRecordLength () const
Get the padded length in bytes of the entire compressed record.
If the data is not compressed, then this returns 0;
Returns
padded length in bytes of the entire compressed record, else 0 if not compressed.
getCompressionType()
Compressor::CompressionType evio::RecordHeader::getCompressionType () const
Get the type of compression used.
0=none, 1=LZ4 fast, 2=LZ4 best, 3=gzip.
Returns
type of compression used.
Referenced by evio::Reader::scanUncompressedBuffer(), and evio::RecordInput::uncompressRecord().
getDataLength()
uint32_t evio::RecordHeader::getDataLength () const
Get the length of the uncompressed data in bytes.
Returns
length of the uncompressed data in bytes.
getDataLengthWords()
uint32_t evio::RecordHeader::getDataLengthWords () const
Get the length of the uncompressed data in words (padded).
Returns
length of the uncompressed data in words (padded).
Referenced by evio::RecordInput::uncompressRecord().
getEntries()
uint32_t evio::RecordHeader::getEntries () const
Get the number of events or entries in index.
Returns
number of events or entries in index.
Referenced by evio::Reader::forceScanFile(), evio::Reader::scanBuffer(), and evio::Reader::scanUncompressedBuffer().
getEventType()
uint32_t evio::RecordHeader::getEventType () override virtual
Get the type of events in record (see values of DataType.
Returns
type of events in record.
Implements evio::IBlockHeader.
getHeaderLength()
uint32_t evio::RecordHeader::getHeaderLength () const
Get the length of this header in bytes (NOT including user header or index).
Returns
length of this header in bytes.
Referenced by evio::Reader::scanBuffer(), evio::Reader::scanUncompressedBuffer(), and evio::RecordInput::uncompressRecord().
getHeaderType()
const HeaderType & evio::RecordHeader::getHeaderType () const
Get the type of header this is.
Returns
type of header this is.
getHeaderWords()
uint32_t evio::RecordHeader::getHeaderWords () override virtual
Get the length of this header in words.
Returns
length of this header in words.
Implements evio::IBlockHeader.
getIndexLength()
uint32_t evio::RecordHeader::getIndexLength () const
Get the length of the index array in bytes.
Returns
length of the index array in bytes.
Referenced by evio::Reader::scanFile(), evio::Reader::scanUncompressedBuffer(), and evio::RecordInput::uncompressRecord().
getLength()
uint32_t evio::RecordHeader::getLength () const
Get the total length of this record in bytes.
Returns
total length of this record in bytes.
Referenced by evio::Reader::forceScanFile(), evio::Reader::scanBuffer(), evio::Reader::scanUncompressedBuffer(), and evio::RecordInput::uncompressRecord().
getLengthWords()
uint32_t evio::RecordHeader::getLengthWords () const
Get the total length of this record in 32 bit words.
Returns
total length of this record in 32 bit words.
getMagicNumber()
uint32_t evio::RecordHeader::getMagicNumber () override virtual
Get the magic number the record)header which should be 0xc0da0100.
Returns
magic number in the record)
Implements evio::IBlockHeader.
getNumber()
uint32_t evio::RecordHeader::getNumber () override virtual
Get the block number for this record) In a file, this is usually sequential.
Returns
the number for this record)
Implements evio::IBlockHeader.
getPadding()
uint32_t evio::RecordHeader::getPadding (uint32_t length) static
Returns number of bytes needed to pad to 4-byte boundary for the given length.
Parameters
length length in bytes.
Returns
number of bytes needed to pad to 4-byte boundary.
getPosition()
size_t evio::RecordHeader::getPosition () const
Get the position of this record in a file.
Returns
position of this record in a file.
getRecordNumber()
uint32_t evio::RecordHeader::getRecordNumber () const
Get the record number.
Returns
record number.
Referenced by evio::Reader::forceScanFile(), evio::Reader::scanBuffer(), and evio::Reader::scanUncompressedBuffer().
getSize()
uint32_t evio::RecordHeader::getSize () override virtual
Get the size of the record)in 32 bit words.
Returns
size of the record)in 32 bit words.
Implements evio::IBlockHeader.
getSourceId()
uint32_t evio::RecordHeader::getSourceId () override virtual
Get the source ID number if in CODA online context and data is coming from ROC.
Returns
source ID number if in CODA online context and data is coming from ROC.
Implements evio::IBlockHeader.
getUncompressedRecordLength()
uint32_t evio::RecordHeader::getUncompressedRecordLength () const
Get the padded length in bytes of the entire uncompressed record.
Returns
padded length in bytes of the entire uncompressed record.
Referenced by evio::Reader::scanBuffer(), and evio::RecordInput::uncompressRecord().
getUserHeaderLength()
uint32_t evio::RecordHeader::getUserHeaderLength () const
Get the length of the user-defined header in bytes.
Returns
length of the user-defined header in bytes.
getUserHeaderLengthWords()
uint32_t evio::RecordHeader::getUserHeaderLengthWords () const
Get the length of the user-defined header in words.
Returns
length of the user-defined header in words.
Referenced by evio::Reader::scanUncompressedBuffer(), and evio::RecordInput::uncompressRecord().
getUserRegisterFirst()
uint64_t evio::RecordHeader::getUserRegisterFirst () const
Get the first user-defined 64-bit register.
Returns
first user-defined 64-bit register.
getUserRegisterSecond()
uint64_t evio::RecordHeader::getUserRegisterSecond () const
Get the second user-defined 64-bit register.
Returns
second user-defined 64-bit register.
getVersion()
uint32_t evio::RecordHeader::getVersion () override virtual
Get the Evio format version number.
Returns
Evio format version number.
Implements evio::IBlockHeader.
Referenced by evio::Reader::scanBuffer(), and evio::Reader::scanUncompressedBuffer().
getWords()
uint32_t evio::RecordHeader::getWords (uint32_t length) static
Returns length padded to 4-byte boundary for given length in bytes.
Parameters
length length in bytes.
Returns
length in bytes padded to 4-byte boundary.
hasDictionary() [1/3]
bool evio::RecordHeader::hasDictionary () override virtual
Does this record have a dictionary in the user header?
Returns
true if record has a dictionary in the user header, else false.
Implements evio::IBlockHeader.
hasDictionary() [2/3]
uint32_t evio::RecordHeader::hasDictionary (bool hasFirst)
Set the bit which says record has a dictionary in the user header.
Parameters
hasFirst true if record has a dictionary in the user header.
Returns
new bitInfo word.
Referenced by evio::Writer::createRecord().
hasDictionary() [3/3]
bool evio::RecordHeader::hasDictionary (int bitInfo) static
Does this bitInfo arg indicate the existence of a dictionary in the user header?
Parameters
bitInfo bitInfo word.
Returns
true if header has a dictionary in the user header, else false.
hasFirstEvent() [1/2]
bool evio::RecordHeader::hasFirstEvent () override virtual
Does this header have a first event in the user header?
Returns
true if header has a first event in the user header, else false.
Implements evio::IBlockHeader.
hasFirstEvent() [2/2]
uint32_t evio::RecordHeader::hasFirstEvent (bool hasFirst)
Set the bit which says record has a first event in the user header.
Parameters
hasFirst true if record has a first event in the user header.
Returns
new bitInfo word.
Referenced by evio::Writer::createRecord().
isCompressed() [1/3]
bool evio::RecordHeader::isCompressed () const
Does this header indicate compressed data?
Returns
true if header indicates compressed data, else false.
Referenced by evio::Reader::scanBuffer().
isCompressed() [2/3]
bool evio::RecordHeader::isCompressed (ByteBuffer & buffer, size_t offset) static
Quickly check to see if this buffer contains compressed data or not.
The offset must point to the beginning of a valid hipo/evio record in the buffer.
Parameters
buffer buffer to read from.
offset position of record header to be read.
Returns
true if data in record is compressed, else false.
Exceptions
EvioException if buffer contains too little data, or is not in proper format.
References evio::ByteBuffer::getInt(), evio::ByteBuffer::limit(), evio::ByteBuffer::order(), and SWAP_32.
isCompressed() [3/3]
bool evio::RecordHeader::isCompressed (std::shared_ptr< ByteBuffer > & buffer, size_t offset) static
Quickly check to see if this buffer contains compressed data or not.
The offset must point to the beginning of a valid hipo/evio record in the buffer.
Parameters
buffer buffer to read from.
offset position of record header to be read.
Returns
true if data in record is compressed, else false.
Exceptions
EvioException if buffer contains too little data, or is not in proper format.
isEvioRecord() [1/2]
bool evio::RecordHeader::isEvioRecord () const
Is this header an evio record?
Returns
true if this is an evio record, else false.
isEvioRecord() [2/2]
bool evio::RecordHeader::isEvioRecord (uint32_t bitInfo) static
Does this arg indicate its header is an evio record?
Parameters
bitInfo bitInfo word.
Returns
true if arg represents an evio record, else false.
isEvioTrailer() [1/2]
bool evio::RecordHeader::isEvioTrailer () const
Is this header an evio trailer?
Returns
true if this is an evio trailer, else false.
isEvioTrailer() [2/2]
bool evio::RecordHeader::isEvioTrailer (uint32_t bitInfo) static
Does this arg indicate its header is an evio trailer?
Parameters
bitInfo bitInfo word.
Returns
true if arg represents an evio trailer, else false.
isHipoRecord() [1/2]
bool evio::RecordHeader::isHipoRecord () const
Is this header a hipo record?
Returns
true if this is a hipo record, else false.
isHipoRecord() [2/2]
bool evio::RecordHeader::isHipoRecord (uint32_t bitInfo) static
Does this arg indicate its header is a hipo record?
Parameters
bitInfo bitInfo word.
Returns
true if arg represents a hipo record, else false.
isHipoTrailer() [1/2]
bool evio::RecordHeader::isHipoTrailer () const
Is this header a hipo trailer?
Returns
true if this is a hipo trailer, else false.
isHipoTrailer() [2/2]
bool evio::RecordHeader::isHipoTrailer (uint32_t bitInfo) static
Does this arg indicate its header is a hipo trailer?
Parameters
bitInfo bitInfo word.
Returns
true if arg represents a hipo trailer, else false.
isLastBlock()
bool evio::RecordHeader::isLastBlock () override virtual
Is this the last record in the file or being sent over the network?
Returns
true if this is the last record in the file or being sent over the network, else false.
Implements evio::IBlockHeader.
isLastRecord() [1/3]
bool evio::RecordHeader::isLastRecord () const
Is this the header of the last record?
Returns
true if this is the header of the last record, else false.
isLastRecord() [2/3]
uint32_t evio::RecordHeader::isLastRecord (bool isLast)
Set the bit which says record is last in file/buffer.
Parameters
isLast true if record is last in file/buffer.
Returns
new bitInfo word.
Referenced by evio::Reader::scanBuffer().
isLastRecord() [3/3]
bool evio::RecordHeader::isLastRecord (uint32_t bitInfo) static
Does this word indicate this is the header of the last record?
Parameters
bitInfo bitInfo word.
Returns
true if this is the header of the last record, else false.
main()
int evio::RecordHeader::main (int argc, char ** argv)
Run this class as an executable which tests the writing and reading of a record.
Parameters
argc argument count
argv argument list
Returns
0.
References getCompressedDataLengthWords(), evio::ByteBuffer::order(), readHeader(), setCompressedDataLength(), setCompressionType(), setDataLength(), setEntries(), setHeaderLength(), setIndexLength(), setLength(), setRecordNumber(), setUserHeaderLength(), setUserRegisterFirst(), setUserRegisterSecond(), toString(), and writeHeader().
nextBufferStartingPosition()
size_t evio::RecordHeader::nextBufferStartingPosition () override virtual
Determines where the start of the next record header in some buffer is located (bytes).
This assumes the start position has been maintained by the object performing the buffer read.
Returns
the start of the next record header in some buffer is located (bytes).
Implements evio::IBlockHeader.
operator=()
RecordHeader & evio::RecordHeader::operator= (const RecordHeader & head)
readHeader() [1/3]
void evio::RecordHeader::readHeader (ByteBuffer & buffer, size_t offset = 0)
Reads the header information from a byte buffer and validates it by checking the magic word (8th word).
This magic word also determines the byte order.
Parameters
buffer buffer to read from.
offset position of first word to be read.
Exceptions
EvioException if buffer contains too little data, is not in proper format, or version earlier than 6.
References evio::ByteBuffer::capacity(), evio::ByteBuffer::getInt(), evio::ByteBuffer::getLong(), evio::ByteBuffer::order(), evio::ByteBuffer::printBytes(), and SWAP_32.
Referenced by evio::Reader::forceScanFile(), main(), evio::Reader::scanFile(), evio::Reader::scanUncompressedBuffer(), and evio::RecordInput::uncompressRecord().
readHeader() [2/3]
void evio::RecordHeader::readHeader (std::shared_ptr< ByteBuffer > & buffer, size_t offset = 0)
Reads the header information from a byte buffer and validates it by checking the magic word (8th word).
This magic word also determines the byte order.
Parameters
buffer buffer to read from.
offset position of first word to be read.
Exceptions
EvioException if buffer contains too little data, is not in proper format, or version earlier than 6.
readHeader() [3/3]
void evio::RecordHeader::readHeader (uint8_t * src, ByteOrder order)
Reads the header information from a byte buffer and validates it by checking the magic word (8th word).
This magic word also determines the byte order.
Parameters
src data to read from.
order byte order when reading.
Exceptions
EvioException if src arg is null, is not in proper format, or version earlier than 6.
References SWAP_32.
reset()
void evio::RecordHeader::reset ()
Reset generated data.
setBitInfo()
uint32_t evio::RecordHeader::setBitInfo (bool isLastRecord, bool haveFirstEvent, bool haveDictionary)
Set the bit info word for a record header.
Current value of bitInfo is lost.
Parameters
isLastRecord true if record is last in stream or file.
haveFirstEvent true if record has a first event in user header.
haveDictionary true if record has dictionary in user header.
Returns
new bit info word.
setBitInfoEventType()
uint32_t evio::RecordHeader::setBitInfoEventType (uint32_t type)
Set the bit info of a record header for a specified CODA event type.
Must be called AFTER setBitInfo(bool, bool, bool) or setBitInfoWord(uint32_t) in order to have change preserved.
Parameters
type event type (0=ROC raw, 1=Physics, 2=Partial Physics, 3=Disentangled, 4=User, 5=Control, 15=Other, else = nothing set).
Returns
new bit info word.
setBitInfoWord() [1/2]
void evio::RecordHeader::setBitInfoWord (std::bitset< 24 > const & set)
Set the bit info word and related values.
NOT FOR GENERAL USE!
Parameters
set reference to bitset containing all bits to be set
setBitInfoWord() [2/2]
void evio::RecordHeader::setBitInfoWord (uint32_t word)
Set the bit info word and related values.
NOT FOR GENERAL USE!
Parameters
word bit info word.
setBufferStartingPosition()
void evio::RecordHeader::setBufferStartingPosition (size_t bufferStartingPosition) override virtual
Set the starting position in the buffer (bytes) from which this header was read–if that happened.
This is not part of the record header proper. It is a position in a memory buffer of the start of the record It is kept for convenience. It is up to the reader to set it.
Parameters
bufferStartingPosition starting position in buffer from which this header was read–if that happened.
Implements evio::IBlockHeader.
setCompressedDataLength()
RecordHeader & evio::RecordHeader::setCompressedDataLength (uint32_t length)
Set the compressed data length in bytes & words and the padding.
Parameters
length length of compressed data in bytes.
Returns
this object.
Referenced by main(), and evio::RecordInput::uncompressRecord().
setCompressionType()
RecordHeader & evio::RecordHeader::setCompressionType (Compressor::CompressionType type)
Set the compression type.
0=none, 1=LZ4 fast, 2=LZ4 best, 3=gzip. No compression for other values.
Parameters
type compression type.
Returns
this object.
Referenced by main(), and evio::RecordInput::uncompressRecord().
setDataLength()
RecordHeader & evio::RecordHeader::setDataLength (uint32_t length)
Set the uncompressed data length in bytes & words and the padding.
Parameters
length length of uncompressed data in bytes.
Returns
this object.
Referenced by main().
setEntries()
RecordHeader & evio::RecordHeader::setEntries (uint32_t n)
Set the number of events or index entries.
No compression for other values.
Parameters
n number of events or index entries.
Returns
this object.
Referenced by main().
setHeaderLength()
RecordHeader & evio::RecordHeader::setHeaderLength (uint32_t length)
Set the this header's length in bytes & words.
If length is not a multiple of 4, you're on your own!
Parameters
length this header's length in bytes.
Returns
this object.
Referenced by main().
setHeaderType()
RecordHeader & evio::RecordHeader::setHeaderType (HeaderType const & type)
Set this header's type.
Normally done in constructor. Limited access.
Parameters
type type of header.
Returns
this object.
References evio::HeaderType::getValue().
setIndexLength()
RecordHeader & evio::RecordHeader::setIndexLength (uint32_t length)
Set the length of the index array in bytes.
Length is forced to be a multiple of 4!
Parameters
length length of index array in bytes.
Returns
this object.
Referenced by main().
setLength()
RecordHeader & evio::RecordHeader::setLength (uint32_t length)
Set the record length in bytes & words.
If length is not a multiple of 4, you're on your own!
Parameters
length length of record in bytes.
Returns
this object.
Referenced by main(), and evio::RecordInput::uncompressRecord().
setPosition()
RecordHeader & evio::RecordHeader::setPosition (size_t pos)
Set the position of this record in a file.
Parameters
pos position of this record in a file.
Returns
this object.
setRecordNumber()
RecordHeader & evio::RecordHeader::setRecordNumber (uint32_t num)
Set the record number.
Parameters
num record number.
Returns
this object.
Referenced by main().
setUserHeaderLength()
RecordHeader & evio::RecordHeader::setUserHeaderLength (uint32_t length)
Set the user-defined header's length in bytes & words and the padding.
Parameters
length user-defined header's length in bytes.
Returns
this object.
Referenced by main().
setUserRegisterFirst()
RecordHeader & evio::RecordHeader::setUserRegisterFirst (uint64_t reg)
Set the first, 64-bit, user-defined register.
Parameters
reg first, 64-bit, user-defined register.
Returns
this object.
Referenced by main().
setUserRegisterSecond()
RecordHeader & evio::RecordHeader::setUserRegisterSecond (uint64_t reg)
Set the second, 64-bit, user-defined register.
Parameters
reg second, 64-bit, user-defined register.
Returns
this object.
Referenced by main().
toString()
string evio::RecordHeader::toString () override virtual
Returns a string representation of this record.
Returns
a string representation of this record.
Implements evio::IBlockHeader.
Referenced by main().
write()
size_t evio::RecordHeader::write (ByteBuffer & byteBuffer) override virtual
Write myself out into a byte buffer.
This write is relative–i.e., it uses the current position of the buffer.
Parameters
byteBuffer the byteBuffer to write to.
Returns
the number of bytes written.
Implements evio::IBlockHeader.
References evio::ByteBuffer::position().
writeHeader() [1/3]
void evio::RecordHeader::writeHeader (ByteBuffer & buf, size_t off = 0)
Writes this header into the given byte buffer.
Position & limit of given buffer does NOT change.
Parameters
buf byte buffer to write header into.
off position in buffer to begin writing.
Exceptions
EvioException if buffer contains too little room.
References evio::ByteBuffer::limit(), evio::ByteBuffer::putInt(), and evio::ByteBuffer::putLong().
Referenced by main().
writeHeader() [2/3]
void evio::RecordHeader::writeHeader (std::shared_ptr< ByteBuffer > & buffer, size_t off = 0)
Writes this header into the given byte buffer.
Position & limit of given buffer does NOT change.
Parameters
buffer byte buffer to write header into.
off position in buffer to begin writing.
Exceptions
EvioException if buffer contains too little room.
writeHeader() [3/3]
void evio::RecordHeader::writeHeader (uint8_t * array, const ByteOrder & order)
Writes this header at the given pointer.
Parameters
array byte array to write header into.
order byte order of data to be written.
Exceptions
EvioException if array arg is null.
writeTrailer() [1/4]
void evio::RecordHeader::writeTrailer (ByteBuffer & buf, size_t off, uint32_t recordNum, const std::shared_ptr< std::vector< uint32_t >> & recordLengths = nullptr) static
Writes a trailer with an optional index array into the given buffer.
Parameters
buf ByteBuffer to write trailer into.
off offset into buffer to start writing.
recordNum record number of trailer.
recordLengths vector containing record lengths interspersed with event counts to be written to trailer. Null if no index array.
Exceptions
EvioException if buf too small to hold trailer + index.
References evio::ByteBuffer::array(), evio::ByteBuffer::arrayOffset(), evio::ByteBuffer::capacity(), evio::ByteBuffer::hasArray(), evio::ByteBuffer::limit(), evio::ByteBuffer::order(), evio::ByteBuffer::position(), evio::ByteBuffer::putInt(), evio::ByteBuffer::putLong(), and evio::ByteBuffer::remaining().
writeTrailer() [2/4]
void evio::RecordHeader::writeTrailer (std::shared_ptr< ByteBuffer > & buf, size_t off, uint32_t recordNum, const std::shared_ptr< std::vector< uint32_t >> & recordLengths = nullptr) static
Writes a trailer with an optional index array into the given buffer.
Parameters
buf ByteBuffer to write trailer into.
off offset into buffer to start writing.
recordNum record number of trailer.
recordLengths vector containing record lengths interspersed with event counts to be written to trailer. Null if no index array.
Exceptions
EvioException if buf too small to hold trailer + index.
writeTrailer() [3/4]
void evio::RecordHeader::writeTrailer (std::vector< uint8_t > & array, size_t off, uint32_t recordNum, const ByteOrder & order, const std::shared_ptr< std::vector< uint32_t >> & recordLengths = nullptr) static
Writes a trailer with an optional index array into the given vector.
Parameters
array vector to write trailer into.
off offset into vector's array to start writing.
recordNum record number of trailer.
order byte order of data to be written.
recordLengths vector containing record lengths interspersed with event counts to be written to trailer. Null if no index array.
writeTrailer() [4/4]
void evio::RecordHeader::writeTrailer (uint8_t * array, size_t arrayLen, uint32_t recordNum, const ByteOrder & order, const std::shared_ptr< std::vector< uint32_t >> & recordLengths = nullptr) static
Writes a trailer with an optional index array into the given byte array.
Parameters
array byte array to write trailer into.
arrayLen number of available bytes in array to write into.
recordNum record number of trailer.
order byte order of data to be written.
recordLengths vector containing record lengths interspersed with event counts to be written to trailer. Null if no index array.
Exceptions
EvioException if array arg is null, array too small to hold trailer + index.
Member Data Documentation
BIT_INFO_OFFSET
const uint32_t evio::RecordHeader::BIT_INFO_OFFSET = 20 static
Byte offset from beginning of header to bit info word.
Referenced by evio::Writer::close(), evio::Reader::findRecordInfo(), and evio::RecordInput::uncompressRecord().
COMPRESSION_TYPE_OFFSET
const uint32_t evio::RecordHeader::COMPRESSION_TYPE_OFFSET = 36 static
Byte offset from beginning of header to the compression type & compressed data length word.
Referenced by evio::Reader::findRecordInfo(), and evio::RecordInput::uncompressRecord().
DATA_CONTROL_BITS
const uint32_t evio::RecordHeader::DATA_CONTROL_BITS = 0x2800 static
11-14th bits in bitInfo word in record header for CODA data type, control = 5.
DATA_DISENTANGLED_BITS
const uint32_t evio::RecordHeader::DATA_DISENTANGLED_BITS = 0x1800 static
11-14th bits in bitInfo word in header for CODA data type, disentangled = 3.
DATA_OTHER_BITS
const uint32_t evio::RecordHeader::DATA_OTHER_BITS = 0x7800 static
11-14th bits in bitInfo word in record header for CODA data type, other = 15.
DATA_PARTIAL_BITS
const uint32_t evio::RecordHeader::DATA_PARTIAL_BITS = 0x1000 static
11-14th bits in bitInfo word in header for CODA data type, partial physics = 2.
DATA_PHYSICS_BITS
const uint32_t evio::RecordHeader::DATA_PHYSICS_BITS = 0x800 static
11-14th bits in bitInfo word in header for CODA data type, physics = 1.
DATA_ROC_RAW_BITS
const uint32_t evio::RecordHeader::DATA_ROC_RAW_BITS = 0x000 static
11-14th bits in bitInfo word in header for CODA data type, ROC raw = 0.
DATA_USER_BITS
const uint32_t evio::RecordHeader::DATA_USER_BITS = 0x2000 static
11-14th bits in bitInfo word in header for CODA data type, user = 4.
DICTIONARY_BIT
const uint32_t evio::RecordHeader::DICTIONARY_BIT = 0x100 static
8th bit set in bitInfo word in header means contains dictionary.
EVENT_COUNT_OFFSET
const uint32_t evio::RecordHeader::EVENT_COUNT_OFFSET = 12 static
Byte offset from beginning of header to the event index count.
Referenced by evio::Reader::findRecordInfo().
FIRST_EVENT_BIT
const uint32_t evio::RecordHeader::FIRST_EVENT_BIT = 0x200 static
9th bit set in bitInfo word in header means every split file has same first event.
HEADER_LENGTH_OFFSET
const uint32_t evio::RecordHeader::HEADER_LENGTH_OFFSET = 8 static
Byte offset from beginning of header to the header length.
Referenced by evio::Reader::findRecordInfo().
HEADER_MAGIC
const uint32_t evio::RecordHeader::HEADER_MAGIC = 0xc0da0100 static
Magic number used to track endianness.
Referenced by evio::CompactEventBuilder::toFile().
HEADER_SIZE_BYTES
const uint32_t evio::RecordHeader::HEADER_SIZE_BYTES = 56 static
Number of bytes in a normal sized header.
Referenced by evio::EventWriter::EventWriter(), evio::Writer::Writer(), evio::WriterMT::WriterMT(), evio::RecordOutput::build(), evio::Reader::forceScanFile(), evio::RecordOutput::getUncompressedSize(), evio::RecordInput::readRecord(), evio::RecordOutput::roomForEvent(), evio::Reader::scanBuffer(), evio::Reader::scanFile(), evio::Reader::scanUncompressedBuffer(), and evio::CompactEventBuilder::toFile().
HEADER_SIZE_WORDS
const uint32_t evio::RecordHeader::HEADER_SIZE_WORDS = 14 static
Number of 32-bit words in a normal sized header.
Referenced by evio::CompactEventBuilder::toFile().
INDEX_ARRAY_OFFSET
const uint32_t evio::RecordHeader::INDEX_ARRAY_OFFSET = 16 static
Byte offset from beginning of header to the index array length.
Referenced by evio::Reader::findRecordInfo().
LAST_RECORD_BIT
const uint32_t evio::RecordHeader::LAST_RECORD_BIT = 0x400 static
10th bit set in bitInfo word in header means is last in stream or file.
LAST_RECORD_MASK
const uint32_t evio::RecordHeader::LAST_RECORD_MASK = 0x400 static
"Last record" is 11th bit in bitInfo word.
MAGIC_NUMBER
const uint32_t evio::IBlockHeader::MAGIC_NUMBER = 0xc0da0100 static inherited
The magic number, should be the value of magicNumber.
Referenced by evio::Util::findEvioVersion(), evio::EvioReaderV4::parseFirstHeader(), evio::BlockHeaderV2::setMagicNumber(), and evio::BlockHeaderV4::setMagicNumber().
MAGIC_OFFSET
const uint32_t evio::RecordHeader::MAGIC_OFFSET = 28 static
Byte offset from beginning of header to the magic number.
RECORD_LENGTH_OFFSET
const uint32_t evio::RecordHeader::RECORD_LENGTH_OFFSET = 0 static
Byte offset from beginning of header to the record length.
Referenced by evio::Reader::findRecordInfo(), and evio::RecordInput::uncompressRecord().
RECORD_NUMBER_OFFSET
const uint32_t evio::RecordHeader::RECORD_NUMBER_OFFSET = 4 static
Byte offset from beginning of header to the record number.
REGISTER1_OFFSET
const uint32_t evio::RecordHeader::REGISTER1_OFFSET = 40 static
Byte offset from beginning of header to the user register #1.
REGISTER2_OFFSET
const uint32_t evio::RecordHeader::REGISTER2_OFFSET = 48 static
Byte offset from beginning of header to the user register #2.
UNCOMPRESSED_LENGTH_OFFSET
const uint32_t evio::RecordHeader::UNCOMPRESSED_LENGTH_OFFSET = 32 static
Byte offset from beginning of header to the uncompressed data length.
Referenced by evio::Reader::addStructure(), evio::Reader::findRecordInfo(), and evio::Reader::removeStructure().
USER_LENGTH_OFFSET
const uint32_t evio::RecordHeader::USER_LENGTH_OFFSET = 24 static
Byte offset from beginning of header to the user header length.
Referenced by evio::Reader::findRecordInfo().
VERSION_MASK
const uint32_t evio::RecordHeader::VERSION_MASK = 0xff static
Mask to get version number from 6th int in header.
The documentation for this class was generated from the following files:
RecordHeader.h
RecordHeader.cpp