evio: evio::evioSocketChannel Class Reference
evio::evioSocketChannel Class Reference
Implements evioChannel functionality for I/O to and from socket.
#include <evioSocketChannel.hxx>
Public Member Functions
evioSocketChannel (int socFd, const string &mode="r", int size=100000)
Constructor opens socket for reading or writing.
evioSocketChannel (int socFd, evioDictionary *dict, const string &mode="r", int size=100000)
Constructor opens socket for reading or writing.
virtual ~evioSocketChannel ()
Destructor closes socket, deletes internal buffer.
void open ()
Opens channel for reading or writing.
bool read ()
Reads from socket.
bool read (uint32_t *myEventBuf, int length)
Reads from socket into user-supplied event buffer.
bool readAlloc (uint32_t **buffer, uint32_t *bufLen)
Reads from socket and allocates buffer as needed.
bool readNoCopy ()
Reads from socket using no copy mechanism.
void write ()
Writes to socket from internal buffer.
void write (const uint32_t *myEventBuf)
Writes to socket from user-supplied buffer.
void write (const evioChannel &channel)
Writes to socket from internal buffer of another evioChannel object.
void write (const evioChannel *channel)
Writes from internal buffer of another evioChannel object.
void write (const evioChannelBufferizable &o)
Writes from contents of evioChannelBufferizable object.
void write (const evioChannelBufferizable *o)
Writes from contents of evioChannelBufferizable object.
void close ()
Closes channel.
int ioctl (const string &request, void *argp)
For getting and setting evIoctl parameters.
const uint32_t * getBuffer () const
Returns pointer to internal channel buffer.
int getBufSize () const
Returns internal channel buffer size.
const uint32_t * getNoCopyBuffer () const
Returns pointer to no copy buffer.
string getMode () const
Returns channel I/O mode.
int getSocketFD () const
Returns socket file descriptor.
string getSocketXMLDictionary () const
Returns XML dictionary read in from socket.
Public Member Functions inherited from evio::evioChannel
evioChannel ()
evioChannel (evioDictionary *dict)
virtual ~evioChannel ()
virtual bool readRandom (uint32_t eventNumber)
virtual const evioDictionary * getDictionary () const
virtual const uint32_t * getRandomBuffer () const
virtual void getRandomAccessTable (uint32_t ***const table, uint32_t *len) const
Additional Inherited Members
Protected Attributes inherited from evio::evioChannel
evioDictionary * dictionary
Detailed Description
Implements evioChannel functionality for I/O to and from socket.
Constructor & Destructor Documentation
evioSocketChannel() [1/2]
evioSocketChannel::evioSocketChannel (int sockFD, const string & m = "r", int size = 100000)
Constructor opens socket for reading or writing.
Parameters
sockFD Socket file descriptor
m I/O mode, "r" or "w"
size Internal event buffer size
evioSocketChannel() [2/2]
evioSocketChannel::evioSocketChannel (int sockFD, evioDictionary * dict, const string & m = "r", int size = 100000)
Constructor opens socket for reading or writing.
Parameters
sockFD Socket file descriptor
dict Dictionary
m I/O mode, "r" or "w"
size Internal event buffer size
~evioSocketChannel()
evioSocketChannel::~evioSocketChannel () virtual
Destructor closes socket, deletes internal buffer.
References close(), and evio::evioChannel::dictionary.
Member Function Documentation
close()
void evioSocketChannel::close () virtual
Closes channel.
Implements evio::evioChannel.
Referenced by ~evioSocketChannel().
getBuffer()
const uint32_t * evioSocketChannel::getBuffer () const virtual
Returns pointer to internal channel buffer.
Returns
Pointer to internal buffer
Implements evio::evioChannel.
getBufSize()
int evioSocketChannel::getBufSize () const virtual
Returns internal channel buffer size.
Returns
Internal buffer size in 4-byte words
Implements evio::evioChannel.
getMode()
string evioSocketChannel::getMode () const
Returns channel I/O mode.
Returns
String containing I/O mode
getNoCopyBuffer()
const uint32_t * evioSocketChannel::getNoCopyBuffer () const virtual
Returns pointer to no copy buffer.
Returns
Returs pointer to internal buffer since there is noCopy buffer does not exist
Implements evio::evioChannel.
getSocketFD()
int evioSocketChannel::getSocketFD () const
Returns socket file descriptor.
Returns
socket file descriptor
getSocketXMLDictionary()
string evioSocketChannel::getSocketXMLDictionary () const
Returns XML dictionary read in from socket.
Returns
XML dictionary read in from socket
ioctl()
int evioSocketChannel::ioctl (const string & request, void * argp) virtual
For getting and setting evIoctl parameters.
Parameters
request String containing evIoctl parameters
argp Additional evIoctl parameter
Implements evio::evioChannel.
open()
void evioSocketChannel::open () virtual
Opens channel for reading or writing.
For read, user-supplied dictionary overrides one received from socket.
Implements evio::evioChannel.
References evio::evioChannel::dictionary, and evio::evioDictionary::getDictionaryXML().
read() [1/2]
bool evioSocketChannel::read () virtual
Reads from socket.
Returns
true if successful, false on EOF or other evRead error condition
Implements evio::evioChannel.
read() [2/2]
bool evioSocketChannel::read (uint32_t * myBuf, int length) virtual
Reads from socket into user-supplied event buffer.
Parameters
myBuf User-supplied buffer. @parem length Length of buffer in 4-byte words.
Returns
true if successful, false on EOF or other evRead error condition
Implements evio::evioChannel.
readAlloc()
bool evioSocketChannel::readAlloc (uint32_t ** buffer, uint32_t * bufLen) virtual
Reads from socket and allocates buffer as needed.
Parameters
buffer Pointer to pointer to allocated buffer.
len Length of allocated buffer in 4-byte words.
Returns
true if successful, false on EOF, throws exception for other error.
Note: user MUST free the allocated buffer!
Implements evio::evioChannel.
readNoCopy()
bool evioSocketChannel::readNoCopy () virtual
Reads from socket using no copy mechanism.
Returns
true if successful, false on EOF, throws exception for other error.
Implements evio::evioChannel.
write() [1/6]
void evioSocketChannel::write () virtual
Writes to socket from internal buffer.
Implements evio::evioChannel.
Referenced by write().
write() [2/6]
void evioSocketChannel::write (const evioChannel & channel) virtual
Writes to socket from internal buffer of another evioChannel object.
Parameters
channel Channel object
Implements evio::evioChannel.
References evio::evioChannel::getBuffer().
write() [3/6]
void evioSocketChannel::write (const evioChannel * channel) virtual
Writes from internal buffer of another evioChannel object.
Parameters
channel Pointer to channel object
Implements evio::evioChannel.
References write().
write() [4/6]
void evioSocketChannel::write (const evioChannelBufferizable & o) virtual
Writes from contents of evioChannelBufferizable object.
Parameters
o evioChannelBufferizable object that can serialize to socket
Implements evio::evioChannel.
References evio::evioChannelBufferizable::toEVIOBuffer(), and write().
write() [5/6]
void evioSocketChannel::write (const evioChannelBufferizable * o) virtual
Writes from contents of evioChannelBufferizable object.
Parameters
o Pointer to evioChannelBufferizable object that can serialize to socket
Implements evio::evioChannel.
References write().
write() [6/6]
void evioSocketChannel::write (const uint32_t * myBuf) virtual
Writes to socket from user-supplied buffer.
Parameters
myBuf Buffer containing event
Implements evio::evioChannel.
The documentation for this class was generated from the following files:
evioSocketChannel.hxx
evioSocketChannel.cc