evio: evio::Reader Class Reference
evio::Reader Class Reference
Reader class that reads files stored in the HIPO format.
#include <Reader.h>
Public Member Functions
Reader ()
Default constructor.
Reader (std::string const &filename)
Constructor with filename.
Reader (std::string const &filename, bool forceScan)
Constructor with filename.
Reader (std::shared_ptr< ByteBuffer > &buffer, bool checkRecordNumSeq=false)
Constructor for reading buffer with evio data.
~Reader ()=default
void open (std::string const &filename, bool scan=true)
Opens an input stream in binary mode.
void close ()
This closes the file.
bool isClosed () const
Has close() been called (without reopening by calling setBuffer(std::shared_ptr<ByteBuffer> &))?
bool isFile () const
Is a file being read?
std::string getFileName () const
Get the name of the file being read.
size_t getFileSize () const
Get the size of the file being read, in bytes.
void setBuffer (std::shared_ptr< ByteBuffer > &buf)
This method can be used to avoid creating additional Reader objects by reusing this one with another buffer.
std::shared_ptr< ByteBuffer > getBuffer ()
Get the buffer being read, if any.
size_t getBufferOffset () const
Get the beginning position of the buffer being read.
FileHeader & getFileHeader ()
Get the file header from reading a file.
std::shared_ptr< RecordHeader > & getFirstRecordHeader ()
Get the first record header from reading a file/buffer.
ByteOrder & getByteOrder ()
Get the byte order of the file/buffer being read.
uint32_t getVersion () const
Get the Evio format version number of the file/buffer being read.
bool isCompressed () const
Is the data in the file/buffer compressed?
bool isEvioFormat () const
Does this file/buffer contain non-evio format events?
std::string getDictionary ()
Get the XML format dictionary if there is one.
bool hasDictionary () const
Does this evio file/buffer have an associated XML dictionary?
std::shared_ptr< uint8_t > & getFirstEvent (uint32_t *size)
Get a byte array representing the first event.
uint32_t getFirstEventSize ()
Get size, in bytes, of byte array representing the first event.
bool hasFirstEvent () const
Does this evio file/buffer have an associated first event?
uint32_t getEventCount () const
Get the number of events in file/buffer.
uint32_t getRecordCount () const
Get the number of records read from the file/buffer.
std::vector< RecordPosition > & getRecordPositions ()
Returns a reference to the list of record positions in the file.
std::vector< std::shared_ptr< EvioNode > > & getEventNodes ()
Get a reference to the list of EvioNode objects contained in the buffer being read.
bool getCheckRecordNumberSequence () const
Get whether or not record numbers are enforced to be sequential.
uint32_t getNumEventsRemaining () const
Get the number of events remaining in the file/buffer.
std::shared_ptr< uint8_t > getNextEvent (uint32_t *len)
Get a byte array representing the next event from the file/buffer while sequentially reading.
std::shared_ptr< uint8_t > getPrevEvent (uint32_t *len)
Get a byte array representing the previous event from the sequential queue.
std::shared_ptr< EvioNode > getNextEventNode ()
Get an EvioNode representing the next event from the buffer while sequentially reading.
std::shared_ptr< ByteBuffer > readUserHeader ()
Reads user header of the file header/first record header of buffer.
std::shared_ptr< uint8_t > getEvent (uint32_t index, uint32_t *len)
Get a byte array representing the specified event from the file/buffer.
ByteBuffer & getEvent (ByteBuffer &buf, uint32_t index)
Get a byte array representing the specified event from the file/buffer and place it in the given buf.
std::shared_ptr< ByteBuffer > getEvent (std::shared_ptr< ByteBuffer > &buf, uint32_t index)
Get a byte array representing the specified event from the file/buffer and place it in the given buf.
uint32_t getEventLength (uint32_t index)
Returns the length of the event with given index.
std::shared_ptr< EvioNode > getEventNode (uint32_t index)
Get an EvioNode representing the specified event from the buffer.
bool hasNext () const
Checks if the file has an event to read next.
bool hasPrev () const
Checks if the stream has previous event to be accessed through, getPrevEvent()
uint32_t getRecordEventCount () const
Get the number of events in current record.
uint32_t getCurrentRecord () const
Get the index of the current record.
RecordInput & getCurrentRecordStream ()
Get the current record stream.
bool readRecord (uint32_t index)
Reads record from the file/buffer at the given record index.
Protected Member Functions
void extractDictionaryAndFirstEvent ()
Extract dictionary and first event from file/buffer if possible, else do nothing.
void extractDictionaryFromBuffer ()
Extract dictionary and first event from buffer if possible, else do nothing.
void extractDictionaryFromFile ()
Extract dictionary and first event from file if possible, else do nothing.
std::shared_ptr< ByteBuffer > scanBuffer ()
This method scans a buffer to find all records and store their position, length, and event count.
void scanUncompressedBuffer ()
Scan buffer containing uncompressed data to find all records and store their position, length, and event count.
void forceScanFile ()
Scan file to find all records and store their position, length, and event count.
void scanFile (bool force)
Scans the file to index all the record positions.
std::shared_ptr< ByteBuffer > & addStructure (uint32_t eventNumber, ByteBuffer &addBuffer)
This method adds an evio container (bank, segment, or tag segment) as the last structure contained in an event.
std::shared_ptr< ByteBuffer > & removeStructure (std::shared_ptr< EvioNode > &removeNode)
This method removes the data, represented by the given node, from the buffer.
void show () const
Print out all record position information.
Static Protected Member Functions
static void findRecordInfo (std::shared_ptr< ByteBuffer > &buf, uint32_t offset, uint32_t *info, uint32_t infoLen)
Reads data from a record header in order to determine things like the bitInfo word, various lengths, etc.
static void findRecordInfo (ByteBuffer &buf, uint32_t offset, uint32_t *info, uint32_t infoLen)
Reads data from a record header in order to determine things like the bitInfo word, various lengths, etc.
Friends
class EvioCompactReaderV6
Detailed Description
Reader class that reads files stored in the HIPO format.
File has this structure:
   +----------------------------------+
   |      General File Header         |
   +----------------------------------+
   +----------------------------------+
   |         Index (optional)         |
   +----------------------------------+
   +----------------------------------+
   |     User Header (optional)       |
   +----------------------------------+
   +----------------------------------+
   |                                  |
   |            Record 1              |
   |                                  |
   |                                  |
   |                                  |
   +----------------------------------+
                  ...
   +----------------------------------+
   |                                  |
   |            Record N              |
   |                                  |
   |                                  |
   |                                  |
   +----------------------------------+
   +----------------------------------+
   |       Trailer (optional)         |
   +----------------------------------+
   +----------------------------------+
   |    Trailer's Index (optional)    |
   +----------------------------------+
Buffer or streamed data has this structure:
   +----------------------------------+
   |                                  |
   |            Record 1              |
   |                                  |
   |                                  |
   |                                  |
   +----------------------------------+
                  ...
   +----------------------------------+
   |                                  |
   |            Record N              |
   |                                  |
   |                                  |
   |                                  |
   +----------------------------------+
   +----------------------------------+
   |       Trailer (optional)         |
   +----------------------------------+
The important thing with a buffer or streaming is for the last header or
trailer to set the "last record" bit.
Something to keep in mind is one can intersperse sequential calls (getNextEvent, getPrevEvent, or getNextEventNode) with random access calls (getEvent or getEventNode), and the sequence remains unchanged after the random access.
Version
6.0
Since
6.0 08/10/2017
Author
gavalian (original Java)
timmer
See also
FileHeader
RecordInput
Constructor & Destructor Documentation
Reader() [1/4]
evio::Reader::Reader ()
Default constructor.
Does nothing. The open(std::string const &, bool) method has to be called to open the input stream. Also forceScanFile() needs to be called to find records.
Reader() [2/4]
evio::Reader::Reader (std::string const & filename) explicit
Constructor with filename.
Creates instance and opens the input stream with given name. Uses existing indexes in file before scanning.
Parameters
filename input file name.
Exceptions
IOException if error reading file
EvioException if file is not in the proper format or earlier than version 6
References open().
Reader() [3/4]
evio::Reader::Reader (std::string const & filename, bool forceScan)
Constructor with filename.
Creates instance and opens the input stream with given name.
Parameters
filename input file name.
forceScan if true, force a scan of file, else use existing indexes first.
Exceptions
IOException if error reading file
EvioException if file is not in the proper format or earlier than version 6
References open(), and scanFile().
Reader() [4/4]
evio::Reader::Reader (std::shared_ptr< ByteBuffer > & buffer, bool checkRecordNumSeq = false) explicit
Constructor for reading buffer with evio data.
Buffer must be ready to read with position and limit set properly. If the given buffer contains compressed data, it is uncompressed into another buffer. The buffer containing the newly uncompressed data then becomes the internal buffer of this object. It can be obtained by calling getBuffer.
Parameters
buffer buffer with evio data.
checkRecordNumSeq if true, check to see if all record numbers are in order, if not throw exception.
Exceptions
EvioException if buffer too small, not in the proper format, or earlier than version 6; if checkRecordNumSeq is true and records are out of sequence.
References scanBuffer().
~Reader()
evio::Reader::~Reader () default
Member Function Documentation
addStructure()
std::shared_ptr< ByteBuffer > & evio::Reader::addStructure (uint32_t eventNumber, ByteBuffer & addBuffer) protected
This method adds an evio container (bank, segment, or tag segment) as the last structure contained in an event.
It is the responsibility of the caller to make sure that the buffer argument contains valid evio data (only data representing the structure to be added - not in file format with record header and the like) which is compatible with the type of data stored in the given event.
To produce such evio data use EvioBank#write(ByteBuffer &), EvioSegment#write(ByteBuffer &) or EvioTagSegment#write(ByteBuffer &) depending on whether a bank, seg, or tagseg is being added.
The given buffer argument must be ready to read with its position and limit defining the limits of the data to copy.
Parameters
eventNumber number of event to which addBuffer is to be added
addBuffer buffer containing evio data to add (not evio file format, i.e. no record headers)
Returns
a new ByteBuffer object which is created and filled with all the data including what was just added.
Exceptions
EvioException if eventNumber out of bounds; if addBuffer arg is empty or has non-evio format; if addBuffer is opposite endian to current event buffer; if added data is not the proper length (i.e. multiple of 4 bytes); if the event number does not correspond to an existing event; if there is an internal programming error; if object closed
References evio::ByteBuffer::order(), evio::ByteBuffer::remaining(), scanBuffer(), and evio::RecordHeader::UNCOMPRESSED_LENGTH_OFFSET.
Referenced by evio::EvioCompactReaderV6::addStructure().
close()
void evio::Reader::close ()
This closes the file.
Referenced by setBuffer().
extractDictionaryAndFirstEvent()
void evio::Reader::extractDictionaryAndFirstEvent () protected
Extract dictionary and first event from file/buffer if possible, else do nothing.
References extractDictionaryFromBuffer(), and extractDictionaryFromFile().
Referenced by getDictionary(), getFirstEvent(), and getFirstEventSize().
extractDictionaryFromBuffer()
void evio::Reader::extractDictionaryFromBuffer () protected
Extract dictionary and first event from buffer if possible, else do nothing.
References evio::RecordInput::getEvent(), and evio::RecordInput::readRecord().
Referenced by extractDictionaryAndFirstEvent().
extractDictionaryFromFile()
void evio::Reader::extractDictionaryFromFile () protected
Extract dictionary and first event from file if possible, else do nothing.
References evio::FileHeader::getByteOrder(), evio::RecordInput::getEvent(), evio::FileHeader::getHeaderLength(), evio::FileHeader::getIndexLength(), evio::FileHeader::getUserHeaderLength(), evio::FileHeader::hasDictionary(), evio::FileHeader::hasFirstEvent(), and evio::RecordInput::readRecord().
Referenced by extractDictionaryAndFirstEvent().
findRecordInfo() [1/2]
void evio::Reader::findRecordInfo (ByteBuffer & buf, uint32_t offset, uint32_t * info, uint32_t infoLen) static protected
Reads data from a record header in order to determine things like the bitInfo word, various lengths, etc.
Does not change the position or limit of buffer.
Parameters
buf buffer containing evio header.
offset byte offset into buffer.
info array in which to store header info. Elements are:
bit info word
record length in bytes (inclusive)
compression type
header length in bytes
index array length in bytes
user header length in bytes (no padding included)
uncompressed data length in bytes (no padding, w/o record header)
infoLen len in 32-bit words of array at info.
Exceptions
underflow_error if not enough data in buffer.
EvioException null info arg or info.length < 7.
References evio::RecordHeader::BIT_INFO_OFFSET, evio::ByteBuffer::capacity(), evio::RecordHeader::COMPRESSION_TYPE_OFFSET, evio::RecordHeader::EVENT_COUNT_OFFSET, evio::ByteBuffer::getInt(), evio::RecordHeader::HEADER_LENGTH_OFFSET, evio::RecordHeader::INDEX_ARRAY_OFFSET, evio::ByteBuffer::limit(), evio::RecordHeader::RECORD_LENGTH_OFFSET, evio::RecordHeader::UNCOMPRESSED_LENGTH_OFFSET, and evio::RecordHeader::USER_LENGTH_OFFSET.
findRecordInfo() [2/2]
void evio::Reader::findRecordInfo (std::shared_ptr< ByteBuffer > & buf, uint32_t offset, uint32_t * info, uint32_t infoLen) static protected
Reads data from a record header in order to determine things like the bitInfo word, various lengths, etc.
Does not change the position or limit of buffer.
Parameters
buf buffer containing evio header.
offset byte offset into buffer.
info array in which to store header info. Elements are:
bit info word
record length in bytes (inclusive)
compression type
header length in bytes
index array length in bytes
user header length in bytes (no padding included)
uncompressed data length in bytes (no padding, w/o record header)
infoLen len in 32-bit words of array at info.
Exceptions
underflow_error if not enough data in buffer.
EvioException null info arg or info.length < 7.
forceScanFile()
void evio::Reader::forceScanFile () protected
Scan file to find all records and store their position, length, and event count.
Safe to call this method successively.
Exceptions
IOException if error reading file
EvioException if file is not in the proper format or earlier than version 6; if checkRecordNumberSequence is true and records are out of sequence.
References evio::FileEventIndex::addEventSize(), evio::FileEventIndex::clear(), evio::FileHeader::getByteOrder(), evio::RecordHeader::getEntries(), evio::FileHeader::getHeaderLength(), evio::FileHeader::getIndexLength(), evio::RecordHeader::getLength(), evio::RecordHeader::getRecordNumber(), evio::FileHeader::getUserHeaderLength(), evio::FileHeader::getUserHeaderLengthPadding(), evio::FileHeader::getVersion(), evio::RecordHeader::HEADER_SIZE_BYTES, evio::FileHeader::readHeader(), evio::RecordHeader::readHeader(), and evio::Compressor::UNCOMPRESSED.
Referenced by scanFile().
getBuffer()
std::shared_ptr< ByteBuffer > evio::Reader::getBuffer ()
Get the buffer being read, if any.
This may not be the buffer given in the constructor or in setBuffer if the original data was compressed. All data in the returned buffer is uncompressed.
Returns
buffer being read, if any.
Referenced by evio::EvioCompactReaderV6::close(), evio::EvioCompactReaderV6::getByteBuffer(), and evio::EvioCompactReaderV6::toFile().
getBufferOffset()
size_t evio::Reader::getBufferOffset () const
Get the beginning position of the buffer being read.
Returns
the beginning position of the buffer being read.
Referenced by evio::EvioCompactReaderV6::close().
getByteOrder()
ByteOrder & evio::Reader::getByteOrder ()
Get the byte order of the file/buffer being read.
Returns
byte order of the file/buffer being read.
Referenced by evio::EvioCompactReaderV6::getByteOrder(), and evio::EvioCompactReaderV6::getFileByteOrder().
getCheckRecordNumberSequence()
bool evio::Reader::getCheckRecordNumberSequence () const
Get whether or not record numbers are enforced to be sequential.
Returns
true
if record numbers are enforced to be sequential.
getCurrentRecord()
uint32_t evio::Reader::getCurrentRecord () const
Get the index of the current record.
Returns
index of the current record.
getCurrentRecordStream()
RecordInput & evio::Reader::getCurrentRecordStream ()
Get the current record stream.
Returns
current record stream.
getDictionary()
std::string evio::Reader::getDictionary ()
Get the XML format dictionary if there is one.
Returns
XML format dictionary, else null.
References extractDictionaryAndFirstEvent().
Referenced by evio::EvioCompactReaderV6::getDictionary(), and evio::EvioCompactReaderV6::getDictionaryXML().
getEvent() [1/3]
ByteBuffer & evio::Reader::getEvent (ByteBuffer & buf, uint32_t index)
Get a byte array representing the specified event from the file/buffer and place it in the given buf.
If no buf is given (arg is null), create a buffer internally and return it. If index is out of bounds, null is returned.
Parameters
buf buffer in which to place event data.
index index of specified event within the entire file/buffer, contiguous starting at 0.
Returns
buf.
Exceptions
EvioException if file/buffer not in hipo format, if buf has insufficient space to contain event (buf.capacity() < event size), or index too large.
References evio::RecordInput::getEntries(), evio::RecordInput::getEvent(), evio::FileEventIndex::getMaxEvents(), evio::FileEventIndex::getRecordEventNumber(), evio::FileEventIndex::getRecordNumber(), readRecord(), and evio::FileEventIndex::setEvent().
getEvent() [2/3]
std::shared_ptr< ByteBuffer > evio::Reader::getEvent (std::shared_ptr< ByteBuffer > & buf, uint32_t index)
Get a byte array representing the specified event from the file/buffer and place it in the given buf.
If no buf is given (arg is null), create a buffer internally and return it. If index is out of bounds, null is returned.
Parameters
buf buffer in which to place event data.
index index of specified event within the entire file/buffer, contiguous starting at 0.
Returns
buf or null if buf is null.
Exceptions
EvioException if file/buffer not in hipo format, if buf has insufficient space to contain event (buf.capacity() < event size), or index too large.
References getEvent().
getEvent() [3/3]
std::shared_ptr< uint8_t > evio::Reader::getEvent (uint32_t index, uint32_t * len)
Get a byte array representing the specified event from the file/buffer.
If index is out of bounds, null is returned.
Parameters
index index of specified event within the entire file/buffer, contiguous starting at 0.
len pointer to int that gets filled with the returned event's len in bytes.
Returns
byte array representing the specified event or null if index is out of bounds.
Exceptions
EvioException if file/buffer not in hipo format
References evio::RecordInput::getEntries(), evio::RecordInput::getEvent(), evio::FileEventIndex::getMaxEvents(), evio::FileEventIndex::getRecordEventNumber(), evio::FileEventIndex::getRecordNumber(), readRecord(), and evio::FileEventIndex::setEvent().
Referenced by getEvent(), getNextEvent(), and getPrevEvent().
getEventCount()
uint32_t evio::Reader::getEventCount () const
Get the number of events in file/buffer.
Returns
number of events in file/buffer.
References evio::FileEventIndex::getMaxEvents().
Referenced by evio::EvioCompactReaderV6::getEventCount(), and evio::EvioCompactReaderV6::searchEvent().
getEventLength()
uint32_t evio::Reader::getEventLength (uint32_t index)
Returns the length of the event with given index.
Parameters
index index of the event
Returns
length of the data in bytes or zero if index does not correspond to a valid event.
References evio::RecordInput::getEntries(), evio::RecordInput::getEventLength(), evio::FileEventIndex::getMaxEvents(), evio::FileEventIndex::getRecordEventNumber(), evio::FileEventIndex::getRecordNumber(), readRecord(), and evio::FileEventIndex::setEvent().
getEventNode()
std::shared_ptr< EvioNode > evio::Reader::getEventNode (uint32_t index)
Get an EvioNode representing the specified event from the buffer.
If index is out of bounds, nullptr is returned.
Parameters
index index of specified event within the entire buffer, starting at 0.
Returns
EvioNode representing the specified event or null if index is out of bounds, reading a file or data is compressed.
Exceptions
EvioException index too large or reading from file.
References evio::FileEventIndex::getMaxEvents().
Referenced by evio::EvioCompactReaderV6::getEvent(), evio::EvioCompactReaderV6::getEventBuffer(), and evio::EvioCompactReaderV6::removeEvent().
getEventNodes()
std::vector< std::shared_ptr< EvioNode > > & evio::Reader::getEventNodes ()
Get a reference to the list of EvioNode objects contained in the buffer being read.
To be used internally to evio.
Returns
list of EvioNode objects contained in the buffer being read.
getFileHeader()
FileHeader & evio::Reader::getFileHeader ()
Get the file header from reading a file.
Returns
file header from reading a file.
getFileName()
std::string evio::Reader::getFileName () const
Get the name of the file being read.
Returns
name of the file being read or null if none.
getFileSize()
size_t evio::Reader::getFileSize () const
Get the size of the file being read, in bytes.
Returns
size of the file being read, in bytes, or 0 if none.
Referenced by evio::EvioCompactReaderV6::fileSize().
getFirstEvent()
std::shared_ptr< uint8_t > & evio::Reader::getFirstEvent (uint32_t * size)
Get a byte array representing the first event.
Parameters
size pointer filled with the size, in bytes, of the first event (0 if none). If null, this is ignored.
Returns
byte array representing the first event. Null if none.
References extractDictionaryAndFirstEvent().
getFirstEventSize()
uint32_t evio::Reader::getFirstEventSize ()
Get size, in bytes, of byte array representing the first event.
Returns
size, in bytes, of byte array representing the first event. 0 if none.
References extractDictionaryAndFirstEvent().
getFirstRecordHeader()
std::shared_ptr< RecordHeader > & evio::Reader::getFirstRecordHeader ()
Get the first record header from reading a file/buffer.
Returns
first record header from reading a file/buffer.
Referenced by evio::EvioCompactReaderV6::getFirstBlockHeader().
getNextEvent()
std::shared_ptr< uint8_t > evio::Reader::getNextEvent (uint32_t * len)
Get a byte array representing the next event from the file/buffer while sequentially reading.
If the previous call was to getPrevEvent, this will get the event past what that returned. Once the last event is returned, this will return null.
Parameters
len pointer to int that gets filled with the returned event's len in bytes.
Returns
byte array representing the next event or null if there is none.
Exceptions
EvioException if file/buffer not in hipo format
References getEvent().
getNextEventNode()
std::shared_ptr< EvioNode > evio::Reader::getNextEventNode ()
Get an EvioNode representing the next event from the buffer while sequentially reading.
Calling this and calling getNextEvent() have the same effect in terms of advancing the same internal counter. If the previous call was to getPrevEvent, this will get the event past what that returned. Once the last event is returned, this will return null.
Returns
EvioNode representing the next event or null if no more events, reading a file or data is compressed.
References evio::FileEventIndex::getMaxEvents().
getNumEventsRemaining()
uint32_t evio::Reader::getNumEventsRemaining () const
Get the number of events remaining in the file/buffer.
Useful only if doing a sequential read.
Returns
number of events remaining in the file/buffer
References evio::FileEventIndex::getMaxEvents().
getPrevEvent()
std::shared_ptr< uint8_t > evio::Reader::getPrevEvent (uint32_t * len)
Get a byte array representing the previous event from the sequential queue.
If the previous call was to getNextEvent, this will get the event previous to what that returned. If this is called before getNextEvent, it will always return null. Once the first event is returned, this will return null.
Parameters
len pointer to int that gets filled with the returned event's len in bytes.
Returns
byte array representing the previous event or null if there is none.
Exceptions
EvioException if the file/buffer is not in HIPO format
References getEvent().
getRecordCount()
uint32_t evio::Reader::getRecordCount () const
Get the number of records read from the file/buffer.
Returns
number of records read from the file/buffer.
Referenced by evio::EvioCompactReaderV6::getBlockCount().
getRecordEventCount()
uint32_t evio::Reader::getRecordEventCount () const
Get the number of events in current record.
Returns
number of events in current record.
References evio::RecordInput::getEntries().
getRecordPositions()
std::vector< Reader::RecordPosition > & evio::Reader::getRecordPositions ()
Returns a reference to the list of record positions in the file.
Returns
getVersion()
uint32_t evio::Reader::getVersion () const
Get the Evio format version number of the file/buffer being read.
Returns
Evio format version number of the file/buffer being read.
Referenced by evio::EvioCompactReaderV6::getEvioVersion().
hasDictionary()
bool evio::Reader::hasDictionary () const
Does this evio file/buffer have an associated XML dictionary?
Returns
true if this evio file/buffer has an associated XML dictionary, else false.
References evio::FileHeader::hasDictionary().
Referenced by evio::EvioCompactReaderV6::hasDictionary().
hasFirstEvent()
bool evio::Reader::hasFirstEvent () const
Does this evio file/buffer have an associated first event?
Returns
true if this evio file/buffer has an associated first event, else false.
References evio::FileHeader::hasFirstEvent().
hasNext()
bool evio::Reader::hasNext () const
Checks if the file has an event to read next.
Returns
true if the next event is available, false otherwise
References evio::FileEventIndex::canAdvance().
hasPrev()
bool evio::Reader::hasPrev () const
Checks if the stream has previous event to be accessed through, getPrevEvent()
Returns
true if previous event is accessible, false otherwise
References evio::FileEventIndex::canRetreat().
isClosed()
bool evio::Reader::isClosed () const
Has close() been called (without reopening by calling setBuffer(std::shared_ptr<ByteBuffer> &))?
Returns
true
if this object closed, else
false
.
isCompressed()
bool evio::Reader::isCompressed () const
Is the data in the file/buffer compressed?
Returns
true if data is compressed.
Referenced by evio::EvioCompactReaderV6::isCompressed().
isEvioFormat()
bool evio::Reader::isEvioFormat () const
Does this file/buffer contain non-evio format events?
Returns
true if all events are in evio format, else false.
Referenced by evio::EvioCompactReaderV6::EvioCompactReaderV6(), and evio::EvioCompactReaderV6::setBuffer().
isFile()
bool evio::Reader::isFile () const
Is a file being read?
Returns
true
if a file is being read,
false
if it's a buffer.
Referenced by evio::EvioCompactReaderV6::isFile().
open()
void evio::Reader::open (std::string const & filename, bool scan = true)
Opens an input stream in binary mode.
Scans for records in the file and stores record information in internal array. Each record can be read from the file.
Parameters
filename input file name
scan if true, call scanFile(false).
Exceptions
EvioException if error handling file
References scanFile().
Referenced by evio::EvioCompactReaderV6::EvioCompactReaderV6(), and Reader().
readRecord()
bool evio::Reader::readRecord (uint32_t index)
Reads record from the file/buffer at the given record index.
Parameters
index record index (starting at 0).
Returns
true if valid index and successful reading record, else false.
Exceptions
EvioException if file/buffer not in hipo format
References evio::RecordInput::readRecord().
Referenced by getEvent(), and getEventLength().
readUserHeader()
std::shared_ptr< ByteBuffer > evio::Reader::readUserHeader ()
Reads user header of the file header/first record header of buffer.
The returned ByteBuffer also contains endianness of the file/buffer.
Returns
ByteBuffer containing the user header of the file/buffer.
Exceptions
IOException if error reading file
References evio::FileHeader::getByteOrder(), evio::FileHeader::getHeaderLength(), evio::FileHeader::getIndexLength(), and evio::FileHeader::getUserHeaderLength().
removeStructure()
std::shared_ptr< ByteBuffer > & evio::Reader::removeStructure (std::shared_ptr< EvioNode > & removeNode) protected
This method removes the data, represented by the given node, from the buffer.
It also marks all nodes taken from that buffer as obsolete. They must not be used anymore.
Parameters
removeNode evio structure to remove from buffer
Returns
ByteBuffer updated to reflect the node removal
Exceptions
EvioException if object closed; if node was not found in any event; if internal programming error; if buffer has compressed data;
References evio::ByteBuffer::limit(), scanBuffer(), evio::Compressor::UNCOMPRESSED, and evio::RecordHeader::UNCOMPRESSED_LENGTH_OFFSET.
Referenced by evio::EvioCompactReaderV6::removeStructure().
scanBuffer()
std::shared_ptr< ByteBuffer > evio::Reader::scanBuffer () protected
This method scans a buffer to find all records and store their position, length, and event count.
It also finds all events and creates & stores their associated EvioNode objects. The difficulty with doing this is that the buffer may contain compressed data. It must then be uncompressed into a different buffer.
Returns
buffer containing uncompressed data. This buffer is different than the internal buffer. Ready to read.
Exceptions
EvioException if buffer not in the proper format or earlier than version 6; if checkRecordNumberSequence is true and records are out of sequence.
underflow_error if not enough data in buffer.
References evio::FileEventIndex::addEventSize(), evio::ByteBuffer::array(), evio::ByteBuffer::arrayOffset(), evio::FileEventIndex::clear(), evio::HeaderType::EVIO_RECORD, evio::EvioNode::extractEventNode(), evio::RecordHeader::getByteOrder(), evio::RecordHeader::getEntries(), evio::RecordHeader::getHeaderLength(), evio::RecordHeader::getLength(), evio::RecordHeader::getRecordNumber(), evio::RecordHeader::getUncompressedRecordLength(), evio::RecordHeader::getVersion(), evio::RecordHeader::HEADER_SIZE_BYTES, evio::RecordHeader::isCompressed(), evio::RecordHeader::isLastRecord(), evio::ByteBuffer::order(), evio::ByteBuffer::position(), scanUncompressedBuffer(), and evio::RecordInput::uncompressRecord().
Referenced by Reader(), addStructure(), removeStructure(), and setBuffer().
scanFile()
void evio::Reader::scanFile (bool force) protected
Scans the file to index all the record positions.
It takes advantage of any existing indexes in file.
Parameters
force if true, force a file scan even if header or trailer have index info.
Exceptions
IOException if error reading file
EvioException if file is not in the proper format or earlier than version 6
References evio::FileEventIndex::addEventSize(), evio::FileEventIndex::clear(), forceScanFile(), evio::FileHeader::getByteOrder(), evio::FileHeader::getHeaderLength(), evio::FileHeader::getIndexLength(), evio::RecordHeader::getIndexLength(), evio::FileHeader::getLength(), evio::FileHeader::getTrailerPosition(), evio::FileHeader::getVersion(), evio::FileHeader::hasIndex(), evio::FileHeader::hasTrailerWithIndex(), evio::FileHeader::HEADER_SIZE_BYTES, evio::RecordHeader::HEADER_SIZE_BYTES, evio::FileHeader::readHeader(), evio::RecordHeader::readHeader(), evio::Util::toIntArray(), and evio::Compressor::UNCOMPRESSED.
Referenced by Reader(), and open().
scanUncompressedBuffer()
void evio::Reader::scanUncompressedBuffer () protected
Scan buffer containing uncompressed data to find all records and store their position, length, and event count.
Also finds all events and creates & stores their associated EvioNode objects.
Exceptions
EvioException if buffer too small, not in the proper format, or earlier than version 6; if checkRecordNumberSequence is true and records are out of sequence.
References evio::FileEventIndex::addEventSize(), evio::ByteBuffer::array(), evio::FileEventIndex::clear(), evio::EvioNode::extractEventNode(), evio::RecordHeader::getByteOrder(), evio::RecordHeader::getCompressionType(), evio::RecordHeader::getEntries(), evio::RecordHeader::getHeaderLength(), evio::RecordHeader::getIndexLength(), evio::RecordHeader::getLength(), evio::RecordHeader::getRecordNumber(), evio::RecordHeader::getUserHeaderLengthWords(), evio::RecordHeader::getVersion(), evio::RecordHeader::HEADER_SIZE_BYTES, evio::RecordHeader::readHeader(), and evio::Compressor::UNCOMPRESSED.
Referenced by scanBuffer().
setBuffer()
void evio::Reader::setBuffer (std::shared_ptr< ByteBuffer > & buf)
This method can be used to avoid creating additional Reader objects by reusing this one with another buffer.
If the given buffer contains compressed data, it is uncompressed into another buffer. The buffer containing the newly uncompressed data then becomes the internal buffer of this object. It can be obtained by calling getBuffer.
Parameters
buf ByteBuffer to be read
Exceptions
underflow_error if not enough data in buffer.
EvioException if buf arg is null, not in the proper format, or earlier than version 6
References evio::FileEventIndex::clear(), close(), and scanBuffer().
Referenced by evio::EvioCompactReaderV6::EvioCompactReaderV6(), and evio::EvioCompactReaderV6::setBuffer().
show()
void evio::Reader::show () const protected
Print out all record position information.
Friends And Related Function Documentation
EvioCompactReaderV6
friend class EvioCompactReaderV6 friend
The documentation for this class was generated from the following files:
Reader.h
Reader.cpp