evio: evio::EventBuilder Class Reference
evio::EventBuilder Class Reference
This class is used for creating and manipulating events.
#include <EventBuilder.h>
Public Member Functions
EventBuilder (uint16_t tag, DataType const dataType, uint8_t num)
This is the constructor to use for an EventBuilder object that will operate on a new, empty event.
EventBuilder (std::shared_ptr< EvioEvent > &event)
This is the constructor to use when you want to manipulate an existing event.
void setAllHeaderLengths ()
This goes through the event recursively, and makes sure all the length fields in the headers are properly set.
void clearData (std::shared_ptr< BaseStructure > structure)
This clears all the data fields in a structure, but not the parent or the children.
void addChild (std::shared_ptr< BaseStructure > parent, std::shared_ptr< BaseStructure > child)
Add a child to a parent structure.
void remove (std::shared_ptr< BaseStructure > child)
This removes a structure (and all its descendants) from the tree.
void setIntData (std::shared_ptr< BaseStructure > structure, int32_t *data, size_t count)
Set int data in the structure.
void setUIntData (std::shared_ptr< BaseStructure > structure, uint32_t *data, size_t count)
Set unsigned int data in the structure.
void setShortData (std::shared_ptr< BaseStructure > structure, int16_t *data, size_t count)
Set short data in the structure.
void setUShortData (std::shared_ptr< BaseStructure > structure, uint16_t *data, size_t count)
Set unsigned short data in the structure.
void setLongData (std::shared_ptr< BaseStructure > structure, int64_t *data, size_t count)
Set long data in the structure.
void setULongData (std::shared_ptr< BaseStructure > structure, uint64_t *data, size_t count)
Set unsigned long data in the structure.
void setCharData (std::shared_ptr< BaseStructure > structure, char *data, size_t count)
Set char data in the structure.
void setUCharData (std::shared_ptr< BaseStructure > structure, unsigned char *data, size_t count)
Set unsigned char data in the structure.
void setFloatData (std::shared_ptr< BaseStructure > structure, float *data, size_t count)
Set float data in the structure.
void setDoubleData (std::shared_ptr< BaseStructure > structure, double *data, size_t count)
Set double data in the structure.
void setStringData (std::shared_ptr< BaseStructure > structure, std::string *data, size_t count)
Set string data in the structure.
void setCompositeData (std::shared_ptr< BaseStructure > structure, std::shared_ptr< CompositeData > *data, size_t count)
Set composite data in the structure.
void appendIntData (std::shared_ptr< BaseStructure > structure, int32_t *data, size_t count)
Append int data to the structure.
void appendUIntData (std::shared_ptr< BaseStructure > structure, uint32_t *data, size_t count)
Append unsigned int data to the structure.
void appendShortData (std::shared_ptr< BaseStructure > structure, int16_t *data, size_t count)
Append short data to the structure.
void appendUShortData (std::shared_ptr< BaseStructure > structure, uint16_t *data, size_t count)
Append unsigned short data to the structure.
void appendLongData (std::shared_ptr< BaseStructure > structure, int64_t *data, size_t count)
Append long data to the structure.
void appendULongData (std::shared_ptr< BaseStructure > structure, uint64_t *data, size_t count)
Append unsigned long data to the structure.
void appendCharData (std::shared_ptr< BaseStructure > structure, char *data, size_t count)
Append char data to the structure.
void appendUCharData (std::shared_ptr< BaseStructure > structure, unsigned char *data, size_t count)
Append unsigned char data to the structure.
void appendFloatData (std::shared_ptr< BaseStructure > structure, float *data, size_t count)
Append float data to the structure.
void appendDoubleData (std::shared_ptr< BaseStructure > structure, double *data, size_t count)
Append double data to the structure.
void appendStringData (std::shared_ptr< BaseStructure > structure, std::string *data, size_t count)
Append string data to the structure.
void appendCompositeData (std::shared_ptr< BaseStructure > structure, std::shared_ptr< CompositeData > *data, size_t count)
Append string data to the structure.
std::shared_ptr< EvioEvent > getEvent ()
Get the underlying event.
void setEvent (std::shared_ptr< EvioEvent > &ev)
Set the underlying event.
Static Public Member Functions
static int main (int argc, char **argv)
Main program for testing.
Detailed Description
This class is used for creating and manipulating events.
One constructor is convenient for creating new events while another is useful for manipulating existing events. You can create a new EventBuilder for each event being handled; however, in many cases one can use the same EventBuilder for all events by calling the setEvent method. The only reason a singleton pattern was not used was to allow for the possibility that events will be built or manipulated on multiple threads.
Author
heddle (original java version)
timmer
Constructor & Destructor Documentation
EventBuilder() [1/2]
evio::EventBuilder::EventBuilder (uint16_t tag, DataType const dataType, uint8_t num)
This is the constructor to use for an EventBuilder object that will operate on a new, empty event.
Parameters
tag the tag for the event header (which is just a bank header).
dataType the data type for the event object–which again is just the type for the outer most bank. Often an event is a bank of banks, so typically this will be DataType.BANK, or 0xe (14).
num often an ordinal enumeration.
References evio::EvioEvent::getInstance().
EventBuilder() [2/2]
evio::EventBuilder::EventBuilder (std::shared_ptr< EvioEvent > & ev)
This is the constructor to use when you want to manipulate an existing event.
Parameters
ev the event to manipulate.
Member Function Documentation
addChild()
void evio::EventBuilder::addChild (std::shared_ptr< BaseStructure > parent, std::shared_ptr< BaseStructure > child)
Add a child to a parent structure.
Parameters
parent the parent structure.
child the child structure.
Exceptions
EvioException if parent or child is null, child has wrong byte order, is wrong structure type, or parent is not a container
References evio::DataType::ALSOBANK, evio::DataType::ALSOSEGMENT, evio::DataType::BANK, evio::DataType::getDataType(), evio::DataType::getName(), evio::DataType::isStructure(), evio::DataType::SEGMENT, setAllHeaderLengths(), evio::StructureType::STRUCT_BANK, evio::StructureType::STRUCT_SEGMENT, evio::StructureType::STRUCT_TAGSEGMENT, and evio::DataType::TAGSEGMENT.
Referenced by main().
appendCharData()
void evio::EventBuilder::appendCharData (std::shared_ptr< BaseStructure > structure, char * data, size_t count)
Append char data to the structure.
If the structure has no data, then this is the same as setting the data (except the the data type may not be changed).
Parameters
structure the structure to receive the data.
data pointer to data (array of chars) to append.
count number of chars to append.
Exceptions
EvioException if structure or data arg(s) is null, data type is not char.
References evio::DataType::CHAR8, and setAllHeaderLengths().
appendCompositeData()
void evio::EventBuilder::appendCompositeData (std::shared_ptr< BaseStructure > structure, std::shared_ptr< CompositeData > * data, size_t count)
Append string data to the structure.
If the structure has no data, then this is the same as setting the data (except the the data type may not be changed).
Parameters
structure the structure to receive the data.
data pointer to data (array of string) to append.
count number of strings to append.
Exceptions
EvioException if structure or data arg(s) is null, data type is not string.
References evio::DataType::COMPOSITE, and setAllHeaderLengths().
appendDoubleData()
void evio::EventBuilder::appendDoubleData (std::shared_ptr< BaseStructure > structure, double * data, size_t count)
Append double data to the structure.
If the structure has no data, then this is the same as setting the data (except the the data type may not be changed).
Parameters
structure the structure to receive the data.
data pointer to data (array of doubles) to append.
count number of doubles to append.
Exceptions
EvioException if structure or data arg(s) is null, data type is not double.
References evio::DataType::DOUBLE64, and setAllHeaderLengths().
Referenced by main().
appendFloatData()
void evio::EventBuilder::appendFloatData (std::shared_ptr< BaseStructure > structure, float * data, size_t count)
Append float data to the structure.
If the structure has no data, then this is the same as setting the data (except the the data type may not be changed).
Parameters
structure the structure to receive the data.
data pointer to data (array of floats) to append.
count number of floats to append.
Exceptions
EvioException if structure or data arg(s) is null, data type is not float.
References evio::DataType::FLOAT32, and setAllHeaderLengths().
appendIntData()
void evio::EventBuilder::appendIntData (std::shared_ptr< BaseStructure > structure, int32_t * data, size_t count)
Append int data to the structure.
If the structure has no data, then this is the same as setting the data (except the the data type may not be changed).
Parameters
structure the structure to receive the data.
data pointer to data (array of ints) to append.
count number of ints to append.
Exceptions
EvioException if structure or data arg(s) is null, data type is not int.
References evio::DataType::INT32, and setAllHeaderLengths().
appendLongData()
void evio::EventBuilder::appendLongData (std::shared_ptr< BaseStructure > structure, int64_t * data, size_t count)
Append long data to the structure.
If the structure has no data, then this is the same as setting the data (except the the data type may not be changed).
Parameters
structure the structure to receive the data.
data pointer to data (array of longs) to append.
count number of longs to append.
Exceptions
EvioException if structure or data arg(s) is null, data type is not long.
References evio::DataType::LONG64, and setAllHeaderLengths().
appendShortData()
void evio::EventBuilder::appendShortData (std::shared_ptr< BaseStructure > structure, int16_t * data, size_t count)
Append short data to the structure.
If the structure has no data, then this is the same as setting the data (except the the data type may not be changed).
Parameters
structure the structure to receive the data.
data pointer to data (array of shorts) to append.
count number of shorts to append.
Exceptions
EvioException if structure or data arg(s) is null, data type is not short.
References setAllHeaderLengths(), and evio::DataType::SHORT16.
appendStringData()
void evio::EventBuilder::appendStringData (std::shared_ptr< BaseStructure > structure, std::string * data, size_t count)
Append string data to the structure.
If the structure has no data, then this is the same as setting the data (except the the data type may not be changed).
Parameters
structure the structure to receive the data.
data pointer to data (array of string) to append.
count number of strings to append.
Exceptions
EvioException if structure or data arg(s) is null, data type is not string.
References evio::DataType::CHARSTAR8, and setAllHeaderLengths().
Referenced by main().
appendUCharData()
void evio::EventBuilder::appendUCharData (std::shared_ptr< BaseStructure > structure, unsigned char * data, size_t count)
Append unsigned char data to the structure.
If the structure has no data, then this is the same as setting the data (except the the data type may not be changed).
Parameters
structure the structure to receive the data.
data pointer to data (array of uchars) to append.
count number of chars to append.
Exceptions
EvioException if structure or data arg(s) is null, data type is not unsigned char.
References setAllHeaderLengths(), and evio::DataType::UCHAR8.
appendUIntData()
void evio::EventBuilder::appendUIntData (std::shared_ptr< BaseStructure > structure, uint32_t * data, size_t count)
Append unsigned int data to the structure.
If the structure has no data, then this is the same as setting the data (except the the data type may not be changed).
Parameters
structure the structure to receive the data.
data pointer to data (array of uints) to append.
count number of ints to append.
Exceptions
EvioException if structure or data arg(s) is null, data type is not unsigned int.
References setAllHeaderLengths(), and evio::DataType::UINT32.
Referenced by main().
appendULongData()
void evio::EventBuilder::appendULongData (std::shared_ptr< BaseStructure > structure, uint64_t * data, size_t count)
Append unsigned long data to the structure.
If the structure has no data, then this is the same as setting the data (except the the data type may not be changed).
Parameters
structure the structure to receive the data.
data pointer to data (array of ulongs) to append.
count number of longs to append.
Exceptions
EvioException if structure or data arg(s) is null, data type is not unsigned long.
References setAllHeaderLengths(), and evio::DataType::ULONG64.
appendUShortData()
void evio::EventBuilder::appendUShortData (std::shared_ptr< BaseStructure > structure, uint16_t * data, size_t count)
Append unsigned short data to the structure.
If the structure has no data, then this is the same as setting the data (except the the data type may not be changed).
Parameters
structure the structure to receive the data.
data pointer to data (array of ushorts) to append.
count number of shorts to append.
Exceptions
EvioException if structure or data arg(s) is null, data type is not unsigned short.
References setAllHeaderLengths(), and evio::DataType::USHORT16.
Referenced by main().
clearData()
void evio::EventBuilder::clearData (std::shared_ptr< BaseStructure > structure)
This clears all the data fields in a structure, but not the parent or the children.
This keeps the existing tree structure intact. To remove a structure (and, consequently, all its descendants) from the tree, use remove
Parameters
structure the segment to clear.
getEvent()
std::shared_ptr< EvioEvent > evio::EventBuilder::getEvent ()
Get the underlying event.
Returns
the underlying event.
Referenced by main().
main()
int evio::EventBuilder::main (int argc, char ** argv) static
Main program for testing.
Parameters
argc ignored command line count.
argv ignored command line arguments.
References addChild(), appendDoubleData(), appendStringData(), appendUIntData(), appendUShortData(), evio::DataType::BANK, evio::DataType::CHARSTAR8, evio::EventWriter::close(), evio::DataType::DOUBLE64, getEvent(), evio::EvioBank::getInstance(), evio::EvioSegment::getInstance(), evio::EvioTagSegment::getInstance(), evio::DataType::INT32, evio::DataType::SEGMENT, evio::DataType::SHORT16, evio::DataType::TAGSEGMENT, and evio::EventWriter::writeEvent().
remove()
void evio::EventBuilder::remove (std::shared_ptr< BaseStructure > child)
This removes a structure (and all its descendants) from the tree.
Parameters
child the child structure to remove.
Exceptions
EvioException if arg is null or its parent is null
References setAllHeaderLengths().
setAllHeaderLengths()
void evio::EventBuilder::setAllHeaderLengths ()
This goes through the event recursively, and makes sure all the length fields in the headers are properly set.
Referenced by addChild(), appendCharData(), appendCompositeData(), appendDoubleData(), appendFloatData(), appendIntData(), appendLongData(), appendShortData(), appendStringData(), appendUCharData(), appendUIntData(), appendULongData(), appendUShortData(), remove(), setCharData(), setCompositeData(), setDoubleData(), setFloatData(), setIntData(), setLongData(), setShortData(), setStringData(), setUCharData(), setUIntData(), setULongData(), and setUShortData().
setCharData()
void evio::EventBuilder::setCharData (std::shared_ptr< BaseStructure > structure, char * data, size_t count)
Set char data in the structure.
If the structure has data, it is overwritten even if the existing data is of a different type.
Parameters
structure the structure to receive the data.
data pointer to data (array of chars) to write.
count number of bytes to write.
Exceptions
EvioException if structure or data arg(s) is null.
References evio::DataType::CHAR8, and setAllHeaderLengths().
setCompositeData()
void evio::EventBuilder::setCompositeData (std::shared_ptr< BaseStructure > structure, std::shared_ptr< CompositeData > * data, size_t count)
Set composite data in the structure.
If the structure has data, it is overwritten even if the existing data is of a different type.
Parameters
structure the structure to receive the data.
data pointer to data (array of shared pointers of composite type) to write.
count number of (shared pointer of) composites to write.
Exceptions
EvioException if structure or data arg(s) is null.
References evio::DataType::COMPOSITE, and setAllHeaderLengths().
setDoubleData()
void evio::EventBuilder::setDoubleData (std::shared_ptr< BaseStructure > structure, double * data, size_t count)
Set double data in the structure.
If the structure has data, it is overwritten even if the existing data is of a different type.
Parameters
structure the structure to receive the data.
data pointer to data (array of doubles) to write.
count number of doubles to write.
Exceptions
EvioException if structure or data arg(s) is null.
References evio::DataType::DOUBLE64, and setAllHeaderLengths().
setEvent()
void evio::EventBuilder::setEvent (std::shared_ptr< EvioEvent > & ev)
Set the underlying event.
As far as this event builder is concerned, the previous underlying event is lost, and all subsequent calls will affect the newly supplied event.
Parameters
ev the new underlying event.
setFloatData()
void evio::EventBuilder::setFloatData (std::shared_ptr< BaseStructure > structure, float * data, size_t count)
Set float data in the structure.
If the structure has data, it is overwritten even if the existing data is of a different type.
Parameters
structure the structure to receive the data.
data pointer to data (array of floats) to write.
count number of floats to write.
Exceptions
EvioException if structure or data arg(s) is null.
References evio::DataType::FLOAT32, and setAllHeaderLengths().
setIntData()
void evio::EventBuilder::setIntData (std::shared_ptr< BaseStructure > structure, int32_t * data, size_t count)
Set int data in the structure.
If the structure has data, it is overwritten even if the existing data is of a different type.
Parameters
structure the structure to receive the data.
data pointer to data (array of ints) to write.
count number of ints to write.
Exceptions
EvioException if structure or data arg(s) is null.
References evio::DataType::INT32, and setAllHeaderLengths().
setLongData()
void evio::EventBuilder::setLongData (std::shared_ptr< BaseStructure > structure, int64_t * data, size_t count)
Set long data in the structure.
If the structure has data, it is overwritten even if the existing data is of a different type.
Parameters
structure the structure to receive the data.
data pointer to data (array of longs) to write.
count number of longs to write.
Exceptions
EvioException if structure or data arg(s) is null.
References evio::DataType::LONG64, and setAllHeaderLengths().
setShortData()
void evio::EventBuilder::setShortData (std::shared_ptr< BaseStructure > structure, int16_t * data, size_t count)
Set short data in the structure.
If the structure has data, it is overwritten even if the existing data is of a different type.
Parameters
structure the structure to receive the data.
data pointer to data (array of shorts) to write.
count number of shorts to write.
Exceptions
EvioException if structure or data arg(s) is null.
References setAllHeaderLengths(), and evio::DataType::SHORT16.
setStringData()
void evio::EventBuilder::setStringData (std::shared_ptr< BaseStructure > structure, std::string * data, size_t count)
Set string data in the structure.
If the structure has data, it is overwritten even if the existing data is of a different type.
Parameters
structure the structure to receive the data.
data pointer to data (array of strings) to write.
count number of strings to write.
Exceptions
EvioException if structure or data arg(s) is null.
References evio::DataType::CHARSTAR8, and setAllHeaderLengths().
setUCharData()
void evio::EventBuilder::setUCharData (std::shared_ptr< BaseStructure > structure, unsigned char * data, size_t count)
Set unsigned char data in the structure.
If the structure has data, it is overwritten even if the existing data is of a different type.
Parameters
structure the structure to receive the data.
data pointer to data (array of uchars) to write.
count number of bytes to write.
Exceptions
EvioException if structure or data arg(s) is null.
References setAllHeaderLengths(), and evio::DataType::UCHAR8.
setUIntData()
void evio::EventBuilder::setUIntData (std::shared_ptr< BaseStructure > structure, uint32_t * data, size_t count)
Set unsigned int data in the structure.
If the structure has data, it is overwritten even if the existing data is of a different type.
Parameters
structure the structure to receive the data.
data pointer to data (array of uints) to write.
count number of ints to write.
Exceptions
EvioException if structure or data arg(s) is null.
References setAllHeaderLengths(), and evio::DataType::UINT32.
setULongData()
void evio::EventBuilder::setULongData (std::shared_ptr< BaseStructure > structure, uint64_t * data, size_t count)
Set unsigned long data in the structure.
If the structure has data, it is overwritten even if the existing data is of a different type.
Parameters
structure the structure to receive the data.
data pointer to data (array of ulongs) to write.
count number of longs to write.
Exceptions
EvioException if structure or data arg(s) is null.
References setAllHeaderLengths(), and evio::DataType::ULONG64.
setUShortData()
void evio::EventBuilder::setUShortData (std::shared_ptr< BaseStructure > structure, uint16_t * data, size_t count)
Set unsigned short data in the structure.
If the structure has data, it is overwritten even if the existing data is of a different type.
Parameters
structure the structure to receive the data.
data pointer to data (array of ushorts) to write.
count number of shorts to write.
Exceptions
EvioException if structure or data arg(s) is null.
References setAllHeaderLengths(), and evio::DataType::USHORT16.
The documentation for this class was generated from the following files:
EventBuilder.h
EventBuilder.cpp