evio: evio::evioDictionary Class Reference
evio::evioDictionary Class Reference
This class parses XML dictionary string and contains maps for looking up dictionary information.
#include <evioDictionary.hxx>
Public Member Functions
evioDictionary ()
No-arg constructor contains empty maps.
evioDictionary (const string &dictXML, const string &sep=".")
Constructor fills dictionary maps from string.
evioDictionary (ifstream &dictIFS, const string &sep=".")
Constructor fills dictionary maps from ifstream.
virtual ~evioDictionary ()
Destructor.
bool parseDictionary (const string &dictionaryXML)
Uses Expat to parse XML dictionary string and fill maps.
evioDictEntry getEntry (const string &name) const
Gets the dictionary entry (evioDictEntry) for a given name.
string getName (evioDictEntry &entry) const
Gets the name associated with an evioDictEntry.
string getName (uint16_t tag, uint8_t num, uint16_t tagEnd=0, bool haveParent=false, uint16_t parentTag=0, uint8_t parentNum=0, uint16_t parentTagEnd=0) const
Gets the name associated with an evioDictEntry which has the given tag, num, tagEnd, and parent tag, num, and tagEnd values.
string getDictionaryXML () const
Gets dictionary XML.
void setSeparator (const string &sep)
Sets separator character.
string getSeparator () const
Gets separator character.
string toString () const
Converts dictionary into string.
Static Public Member Functions
static void startElementHandler (void *userData, const char *xmlname, const char **atts)
Expat start element handler, must be static.
static void endElementHandler (void *userData, const char *xmlname)
Expat end element handler, must be static.
static void charDataHandler (void *userData, const char *s, int len)
Expat start character data handler, must be static.
Public Attributes
map< evioDictEntry, string > getNameMap
This is the heart of the dictionary in which a key is composed of a tag/num pair and other entry data and its corresponding value is a name.
map< string, evioDictEntry > getTagNumMap
This is a map in which the key is a name and the value is its corresponding dictionary entry.
Detailed Description
This class parses XML dictionary string and contains maps for looking up dictionary information.
Constructor & Destructor Documentation
evioDictionary() [1/3]
evioDictionary::evioDictionary ()
No-arg constructor contains empty maps.
evioDictionary() [2/3]
evioDictionary::evioDictionary (const string & dictXML, const string & sep = ".") explicit
Constructor fills dictionary maps from string.
Parameters
dictionaryXML XML string parsed to create dictionary maps
References parseDictionary().
evioDictionary() [3/3]
evioDictionary::evioDictionary (ifstream & dictIFS, const string & sep = ".") explicit
Constructor fills dictionary maps from ifstream.
Parameters
dictionaryXML XML string parsed to create dictionary maps
References parseDictionary().
~evioDictionary()
evioDictionary::~evioDictionary () virtual
Destructor.
Member Function Documentation
charDataHandler()
void evioDictionary::charDataHandler (void * userData, const char * s, int len) static
Expat start character data handler, must be static.
Parameters
userData void* pointer to evioDictionary instance
s character data string which is NOT zero terminated!
len number of valid characters returned at pointer
References evio::evioDictEntry::getEntryType(), evio::TAG_NUM, evio::TAG_ONLY, and evio::TAG_RANGE.
Referenced by parseDictionary().
endElementHandler()
void evioDictionary::endElementHandler (void * userData, const char * xmlname) static
Expat end element handler, must be static.
Parameters
userData void* pointer to evioDictionary instance
xmlname Name of current element
References evio::dictEntryTag, and evio::oldDictEntryTag.
Referenced by parseDictionary().
getDictionaryXML()
string evioDictionary::getDictionaryXML () const
Gets dictionary XML.
Returns
dictionary XML
Referenced by evio::evioBufferChannel::open(), evio::evioFileChannel::open(), and evio::evioSocketChannel::open().
getEntry()
evioDictEntry evioDictionary::getEntry (const string & name) const
Gets the dictionary entry (evioDictEntry) for a given name.
Parameters
name name of dictionary entry
Returns
dictionary entry
Exceptions
evioException if entry not found
References getTagNumMap.
Referenced by evio::evioDOMTree::addBank(), evio::evioDOMNode::createEvioDOMNode(), evio::evioDOMNode::createUnknownEvioDOMNode(), evio::evioDOMNode::evioDOMNode(), and evio::evioDOMTree::evioDOMTree().
getName() [1/2]
string evioDictionary::getName (evioDictEntry & entry) const
Gets the name associated with an evioDictEntry.
Since
5.2
Parameters
entry dictionary entry
Returns
name associated with entry
Exceptions
evioException if entry not found
References getNameMap, evio::evioDictEntry::getNum(), evio::evioDictEntry::getTag(), and evio::evioDictEntry::getTagEnd().
getName() [2/2]
string evioDictionary::getName (uint16_t tag, uint8_t num, uint16_t tagEnd = 0, bool haveParent = false, uint16_t parentTag = 0, uint8_t parentNum = 0, uint16_t parentTagEnd = 0) const
Gets the name associated with an evioDictEntry which has the given tag, num, tagEnd, and parent tag, num, and tagEnd values.
Since
5.2
Parameters
tag dictionary entry's tag value.
num dictionary entry's num value.
tagEnd dictionary entry's tagEnd value (ending value of a range of tags and > tag). Defaults to 0.
haveParent true if entry has a parent entry, else false. Defaults to false.
parentTag parent entry's tag value. Defaults to 0.
parentNum parent entry's num value. Defaults to 0.
parentTagEnd parent entry's tagEnd value. Defaults to 0.
Returns
name associated with arguments
Exceptions
evioException if entry not found
References evio::EVIO_UNKNOWN32, evio::evioDictEntry::getEntryType(), evio::evioDictEntry::inRange(), evio::TAG_NUM, evio::TAG_ONLY, and evio::TAG_RANGE.
getSeparator()
string evioDictionary::getSeparator () const
Gets separator character.
Returns
Separator character
parseDictionary()
bool evioDictionary::parseDictionary (const string & dictionaryXML)
Uses Expat to parse XML dictionary string and fill maps.
Parameters
dictionaryXML XML string
Returns
True if parsing succeeded
References charDataHandler(), endElementHandler(), and startElementHandler().
Referenced by evioDictionary().
setSeparator()
void evioDictionary::setSeparator (const string & sep)
Sets separator character.
Parameters
sep Separator character
startElementHandler()
void evioDictionary::startElementHandler (void * userData, const char * xmlname, const char ** atts) static
Expat start element handler, must be static.
Parameters
userData void* pointer to evioDictionary instance
xmlname Name of current element
atts Array of attributes for this element
References evio::dictEntryTag, evio::EVIO_UNKNOWN32, evio::evioDictEntry::getDataType(), evio::evioDictEntry::getEntryType(), evio::oldDictEntryTag, evio::TAG_NUM, evio::TAG_ONLY, and evio::TAG_RANGE.
Referenced by parseDictionary().
toString()
string evioDictionary::toString () const
Converts dictionary into string.
Returns
String containing dictionary keys and values
References evio::evioDictEntry::getDescription(), evio::evioDictEntry::getFormat(), evio::evioDictEntry::getNum(), evio::evioDictEntry::getTag(), and getTagNumMap.
Member Data Documentation
getNameMap
map<evioDictEntry, string> evio::evioDictionary::getNameMap
This is the heart of the dictionary in which a key is composed of a tag/num pair and other entry data and its corresponding value is a name.
This map contains all entries whether tag/num, tag-only, or tag-range. Gets node name given tag/num.
Referenced by evio::evioDOMContainerNode::getFooter(), evio::evioDOMContainerNode::getHeader(), and getName().
getTagNumMap
map<string, evioDictEntry> evio::evioDictionary::getTagNumMap
This is a map in which the key is a name and the value is its corresponding dictionary entry.
It's the reverse of the getNameMap map. This map contains all entries whether tag/num, tag-only, or tag-range. Gets tag/num given node name.
Referenced by getEntry(), evio::evioDOMTree::getNodeList(), and toString().
The documentation for this class was generated from the following files:
evioDictionary.hxx
evioDictionary.cc