evio: evio::RecordOutput Class Reference
evio::RecordOutput Class Reference
Class which handles the creation and use of Evio & HIPO Records.
#include <RecordOutput.h>
Public Member Functions
RecordOutput ()
Default, no-arg constructor.
RecordOutput (const ByteOrder &order, uint32_t maxEventCount=1000000, uint32_t maxBufferSize=8 *ONE_MEG, Compressor::CompressionType compressionType=Compressor::UNCOMPRESSED, HeaderType hType=HeaderType::EVIO_RECORD)
Constructor with arguments.
RecordOutput (std::shared_ptr< ByteBuffer > &buffer, uint32_t maxEventCount, Compressor::CompressionType compressionType, HeaderType hType)
Constructor with arguments.
RecordOutput (const RecordOutput &srcRec)
Copy constructor.
RecordOutput (RecordOutput &&srcBuf) noexcept
Move constructor.
RecordOutput & operator= (RecordOutput &&other) noexcept
Move assignment operator.
RecordOutput & operator= (const RecordOutput &other)
Assignment operator.
~RecordOutput ()=default
void setBuffer (std::shared_ptr< ByteBuffer > &buf)
Reset internal buffers and set the buffer in which to build this record.
void transferDataForReading (const RecordOutput &rec)
Copy the contents of the arg into this object and get data buffer ready for reading.
uint32_t getUserBufferSize () const
Get the number of initially available bytes to be written into in the user-given buffer, that goes from position to limit.
uint32_t getUncompressedSize () const
Get the current uncompressed size of the record in bytes.
uint32_t getInternalBufferCapacity () const
Get the capacity of the internal buffer in bytes.
uint32_t getMaxEventCount () const
Get the maximum number of events allowed in this record.
uint32_t getEventCount () const
Get the number of events written so far into the buffer.
std::shared_ptr< RecordHeader > & getHeader ()
Get the general header of this record.
const ByteOrder & getByteOrder () const
Get the byte order of the record to be built.
const std::shared_ptr< ByteBuffer > getBinaryBuffer () const
Get the internal ByteBuffer used to construct binary representation of this record.
const Compressor::CompressionType getCompressionType () const
Get the compression type of the contained record.
const HeaderType getHeaderType () const
Get the header type of the contained record.
bool hasUserProvidedBuffer () const
Was the internal buffer provided by the user?
bool roomForEvent (uint32_t length) const
Is there room in this record's memory for an additional event of the given length in bytes (length NOT including accompanying index).
bool oneTooMany () const
Does adding one more event exceed the event count limit?
bool addEvent (const uint8_t *event, uint32_t eventLen, uint32_t extraDataLen=0)
Adds an event's ByteBuffer into the record.
bool addEvent (const std::vector< uint8_t > &event)
Adds an event's ByteBuffer into the record.
bool addEvent (const std::vector< uint8_t > &event, size_t offset, uint32_t eventLen, uint32_t extraDataLen=0)
Adds an event's ByteBuffer into the record.
bool addEvent (const ByteBuffer &event, uint32_t extraDataLen=0)
Adds an event's ByteBuffer into the record.
bool addEvent (const std::shared_ptr< ByteBuffer > &event, uint32_t extraDataLen=0)
Adds an event's ByteBuffer into the record.
bool addEvent (EvioNode &node, uint32_t extraDataLen=0)
Adds an event's ByteBuffer into the record.
bool addEvent (std::shared_ptr< EvioNode > &node, uint32_t extraDataLen=0)
Adds an event's ByteBuffer into the record.
bool addEvent (EvioBank &event, uint32_t extraDataLen)
Adds an event's ByteBuffer into the record.
bool addEvent (std::shared_ptr< EvioBank > &event, uint32_t extraDataLen=0)
Adds an event's ByteBuffer into the record.
void reset ()
Reset internal buffers.
void setStartingBufferPosition (size_t pos)
Set the starting position of the user-given buffer being written into.
void build ()
Builds the record.
void build (std::shared_ptr< ByteBuffer > userHeader)
Builds the record.
void build (const ByteBuffer &userHeader)
Builds the record.
Public Attributes
uint32_t MAX_EVENT_COUNT = 1000000
Maximum number of events per record.
uint32_t MAX_BUFFER_SIZE = 8*ONE_MEG
Size of some internal buffers in bytes.
uint32_t RECORD_BUFFER_SIZE = 9*ONE_MEG
Size of buffer holding built record in bytes.
uint32_t userBufferSize = 0
The number of initially available bytes to be written into in the user-given buffer, that go from position to limit.
uint32_t eventCount = 0
Number of events written to this Record.
uint32_t indexSize = 0
Number of valid bytes in recordIndex buffer.
uint32_t eventSize = 0
Number of valid bytes in recordEvents buffer.
size_t startingPosition = 0
The starting position of a user-given buffer.
std::shared_ptr< ByteBuffer > recordIndex
This buffer stores event lengths (in bytes) ONLY.
std::shared_ptr< ByteBuffer > recordEvents
This buffer stores event data ONLY.
std::shared_ptr< ByteBuffer > recordData
This buffer stores data that will be compressed.
std::shared_ptr< ByteBuffer > recordBinary
Buffer in which to put constructed (& compressed) binary record.
std::shared_ptr< RecordHeader > header
Header of this Record.
ByteOrder byteOrder {ByteOrder::ENDIAN_LOCAL}
Byte order of record byte arrays to build.
bool userProvidedBuffer = false
Is recordBinary a user provided buffer?
Static Public Attributes
static constexpr int ONE_MEG = 1024*1024
Maximum number of events per record.
Detailed Description
Class which handles the creation and use of Evio & HIPO Records.
RECORD STRUCTURE:
              Uncompressed                                      Compressed
   +----------------------------------+            +----------------------------------+
   |       General Record Header      |            |       General Record Header      |
   +----------------------------------+            +----------------------------------+
   +----------------------------------+ ---------> +----------------------------------+
   |      Index Array (bytes)         |            |        Compressed Data           |
   +----------------------------------+            |             Record               |
                                                   |                                  |
   +----------------------------------+            |                                  |
   |           User Header            |            |                  ----------------|
   |           (Optional)             |            |                  |    Pad 3      |
   |                  ----------------|            +----------------------------------+
   |                  |    Pad 1      |           ^
   +----------------------------------+          /
                                                /
   +----------------------------------+        /
   |           Data Record            |       /
   |                                  |      /
   |                  ----------------|     /
   |                  |    Pad 2      |    /
   +----------------------------------+----
GENERAL RECORD HEADER STRUCTURE (see RecordHeader.java)
   +----------------------------------+
 1 |         Record Length            | // 32bit words, inclusive
   +----------------------------------+
 2 +         Record Number            |
   +----------------------------------+
 3 +         Header Length            | // 14 (words)
   +----------------------------------+
 4 +       Event (Index) Count        |
   +----------------------------------+
 5 +      Index Array Length          | // bytes
   +-----------------------+---------+
 6 +       Bit Info        | Version  | // version (8 bits)
   +-----------------------+----------+
 7 +      User Header Length          | // bytes
   +----------------------------------+
 8 +          Magic Number            | // 0xc0da0100
   +----------------------------------+
 9 +     Uncompressed Data Length     | // bytes
   +------+---------------------------+
10 +  CT  |  Data Length Compressed   | // CT = compression type (4 bits)
   +----------------------------------+
11 +        General Register 1        | // UID 1st (64 bits)
   +--                              --+
12 +                                  |
   +----------------------------------+
13 +        General Register 2        | // UID 2nd (64 bits)
   +--                              --+
14 +                                  |
   +----------------------------------+
Version
6.0
Since
6.0 4/9/2019
Author
timmer
Constructor & Destructor Documentation
RecordOutput() [1/5]
evio::RecordOutput::RecordOutput ()
Default, no-arg constructor.
Little endian. No compression.
RecordOutput() [2/5]
evio::RecordOutput::RecordOutput (const ByteOrder & order, uint32_t maxEventCount = 1000000, uint32_t maxBufferSize = 8*ONE_MEG, Compressor::CompressionType compressionType = Compressor::UNCOMPRESSED, HeaderType hType = HeaderType::EVIO_RECORD) explicit
Constructor with arguments.
Parameters
order byte order of built record byte arrays.
maxEventCount max number of events this record can hold. Value <= O means use default (1M).
maxBufferSize max number of uncompressed data bytes this record can hold. Value of < 8MB results in default of 8MB.
compressionType type of data compression to do (0=none, 1=lz4 fast, 2=lz4 best, 3=gzip).
hType type of record header to use.
References byteOrder, evio::HeaderType::EVIO_RECORD, evio::HeaderType::EVIO_TRAILER, header, evio::HeaderType::HIPO_RECORD, evio::HeaderType::HIPO_TRAILER, evio::HeaderType::isEvioFileHeader(), evio::HeaderType::isHipoFileHeader(), MAX_BUFFER_SIZE, MAX_EVENT_COUNT, RECORD_BUFFER_SIZE, and recordIndex.
RecordOutput() [3/5]
evio::RecordOutput::RecordOutput (std::shared_ptr< ByteBuffer > & buffer, uint32_t maxEventCount, Compressor::CompressionType compressionType, HeaderType hType)
Constructor with arguments.
Parameters
buffer buffer in which to put constructed (& compressed) binary record. Must have position and limit set to accept new data.
maxEventCount max number of events this record can hold. Value <= O means use default (1M).
compressionType type of data compression to do (0=none, 1=lz4 fast, 2=lz4 best, 3=gzip).
hType type of record header to use.
References byteOrder, evio::HeaderType::EVIO_RECORD, evio::HeaderType::EVIO_TRAILER, header, evio::HeaderType::HIPO_RECORD, evio::HeaderType::HIPO_TRAILER, evio::HeaderType::isEvioFileHeader(), evio::HeaderType::isHipoFileHeader(), MAX_BUFFER_SIZE, MAX_EVENT_COUNT, RECORD_BUFFER_SIZE, recordBinary, recordIndex, startingPosition, userBufferSize, and userProvidedBuffer.
RecordOutput() [4/5]
evio::RecordOutput::RecordOutput (const RecordOutput & rec)
Copy constructor.
Parameters
rec RecordOutput to copy.
Exceptions
EvioException if trying to copy bigger record and internal buffer was provided by user.
References recordBinary, recordEvents, and recordIndex.
RecordOutput() [5/5]
evio::RecordOutput::RecordOutput (RecordOutput && rec) noexcept
Move constructor.
Parameters
rec RecordOutput object to move.
~RecordOutput()
evio::RecordOutput::~RecordOutput () default
Member Function Documentation
addEvent() [1/9]
bool evio::RecordOutput::addEvent (const ByteBuffer & event, uint32_t extraDataLen = 0)
Adds an event's ByteBuffer into the record.
Can specify the length of additional data to follow the event (such as an evio trailer record) to see if by adding this event everything will fit in the available memory.
If a single event is too large for the internal buffers, more memory is allocated. On the other hand, if the buffer was provided by the user, then obviously the buffer cannot be expanded and false is returned.
The byte order of event must match the byte order given in constructor!
Parameters
event event's ByteBuffer object.
extraDataLen additional data bytes to follow event (e.g. trailer length).
Returns
true if event was added; false if the event was not added because the count limit would be exceeded or the buffer is full and cannot be expanded since it's user-provided.
References evio::ByteBuffer::array(), evio::ByteBuffer::arrayOffset(), eventCount, eventSize, indexSize, MAX_BUFFER_SIZE, ONE_MEG, oneTooMany(), evio::ByteBuffer::position(), RECORD_BUFFER_SIZE, recordEvents, recordIndex, reset(), roomForEvent(), and userProvidedBuffer.
addEvent() [2/9]
bool evio::RecordOutput::addEvent (const std::shared_ptr< ByteBuffer > & event, uint32_t extraDataLen = 0)
Adds an event's ByteBuffer into the record.
Can specify the length of additional data to follow the event (such as an evio trailer record) to see if by adding this event everything will fit in the available memory.
If a single event is too large for the internal buffers, more memory is allocated. On the other hand, if the buffer was provided by the user, then obviously the buffer cannot be expanded and false is returned.
The byte order of event must match the byte order given in constructor!
Parameters
event event's ByteBuffer object.
extraDataLen additional data bytes to follow event (e.g. trailer length).
Returns
true if event was added; false if the event was not added because the count limit would be exceeded or the buffer is full and cannot be expanded since it's user-provided.
References addEvent().
addEvent() [3/9]
bool evio::RecordOutput::addEvent (const std::vector< uint8_t > & event)
Adds an event's ByteBuffer into the record.
If a single event is too large for the internal buffers, more memory is allocated. On the other hand, if the buffer was provided by the user, then obviously the buffer cannot be expanded and false is returned.
The byte order of event must match the byte order given in constructor!
Parameters
event event's data in vector.
Returns
true if event was added; false if the event was not added because the count limit would be exceeded or the buffer is full and cannot be expanded since it's user-provided.
References addEvent().
addEvent() [4/9]
bool evio::RecordOutput::addEvent (const std::vector< uint8_t > & event, size_t offset, uint32_t eventLen, uint32_t extraDataLen = 0)
Adds an event's ByteBuffer into the record.
Can specify the length of additional data to follow the event (such as an evio trailer record) to see if by adding this event everything will fit in the available memory.
If a single event is too large for the internal buffers, more memory is allocated. On the other hand, if the buffer was provided by the user, then obviously the buffer cannot be expanded and false is returned.
The byte order of event must match the byte order given in constructor!
Parameters
event event's data in vector.
offset offset into vector's elements from which to begin reading.
eventLen number of bytes from vector to add.
extraDataLen additional data bytes to follow event (e.g. trailer length).
Returns
true if event was added; false if the event was not added because the count limit would be exceeded or the buffer is full and cannot be expanded since it's user-provided.
References addEvent().
addEvent() [5/9]
bool evio::RecordOutput::addEvent (const uint8_t * event, uint32_t eventLen, uint32_t extraDataLen = 0)
Adds an event's ByteBuffer into the record.
Can specify the length of additional data to follow the event (such as an evio trailer record) to see if by adding this event everything will fit in the available memory.
If a single event is too large for the internal buffers, more memory is allocated. On the other hand, if the buffer was provided by the user, then obviously the buffer cannot be expanded and false is returned.
The byte order of event must match the byte order given in constructor!
Parameters
event event's byte array.
eventLen number of bytes from byte array to add.
extraDataLen additional data bytes to follow event (e.g. trailer length).
Returns
true if event was added; false if the event was not added because the count limit would be exceeded or the buffer is full and cannot be expanded since it's user-provided.
References eventCount, eventSize, indexSize, MAX_BUFFER_SIZE, ONE_MEG, oneTooMany(), RECORD_BUFFER_SIZE, recordEvents, recordIndex, reset(), roomForEvent(), and userProvidedBuffer.
Referenced by addEvent(), and evio::Writer::createRecord().
addEvent() [6/9]
bool evio::RecordOutput::addEvent (EvioBank & event, uint32_t extraDataLen)
Adds an event's ByteBuffer into the record.
Can specify the length of additional data to follow the event (such as an evio trailer record) to see if by adding this event everything will fit in the available memory.
If a single event is too large for the internal buffers, more memory is allocated. On the other hand, if the buffer was provided by the user, then obviously the buffer cannot be expanded and false is returned.
The byte order of event must match the byte order given in constructor!
Parameters
event event's EvioBank object.
extraDataLen additional data bytes to follow event (e.g. trailer length).
Returns
true if event was added; false if the event was not added because the count limit would be exceeded or the buffer is full and cannot be expanded since it's user-provided.
References eventCount, eventSize, indexSize, MAX_BUFFER_SIZE, ONE_MEG, oneTooMany(), RECORD_BUFFER_SIZE, recordEvents, recordIndex, reset(), roomForEvent(), and userProvidedBuffer.
addEvent() [7/9]
bool evio::RecordOutput::addEvent (EvioNode & node, uint32_t extraDataLen = 0)
Adds an event's ByteBuffer into the record.
Can specify the length of additional data to follow the event (such as an evio trailer record) to see if by adding this event everything will fit in the available memory.
If a single event is too large for the internal buffers, more memory is allocated. On the other hand, if the buffer was provided by the user, then obviously the buffer cannot be expanded and false is returned.
The byte order of event must match the byte order given in constructor! This method is not thread-safe with respect to the node as it's backing ByteBuffer's limit and position may be concurrently changed.
Parameters
node event's EvioNode object
extraDataLen additional data bytes to follow event (e.g. trailer length).
Returns
true if event was added; false if the event was not added because the count limit would be exceeded or the buffer is full and cannot be expanded since it's user-provided.
Exceptions
EvioException if node does not correspond to a bank.
References evio::ByteBuffer::array(), evio::ByteBuffer::arrayOffset(), eventCount, eventSize, evio::EvioNode::getStructureBuffer(), evio::EvioNode::getTotalBytes(), evio::EvioNode::getTypeObj(), indexSize, evio::DataType::isBank(), MAX_BUFFER_SIZE, ONE_MEG, oneTooMany(), evio::ByteBuffer::position(), RECORD_BUFFER_SIZE, recordEvents, recordIndex, reset(), roomForEvent(), evio::DataType::toString(), and userProvidedBuffer.
addEvent() [8/9]
bool evio::RecordOutput::addEvent (std::shared_ptr< EvioBank > & event, uint32_t extraDataLen = 0)
Adds an event's ByteBuffer into the record.
Can specify the length of additional data to follow the event (such as an evio trailer record) to see if by adding this event everything will fit in the available memory.
If a single event is too large for the internal buffers, more memory is allocated. On the other hand, if the buffer was provided by the user, then obviously the buffer cannot be expanded and false is returned.
The byte order of event must match the byte order given in constructor!
Parameters
event event's EvioBank object.
extraDataLen additional data bytes to follow event (e.g. trailer length).
Returns
true if event was added; false if the event was not added because the count limit would be exceeded or the buffer is full and cannot be expanded since it's user-provided.
References addEvent().
addEvent() [9/9]
bool evio::RecordOutput::addEvent (std::shared_ptr< EvioNode > & node, uint32_t extraDataLen = 0)
Adds an event's ByteBuffer into the record.
Can specify the length of additional data to follow the event (such as an evio trailer record) to see if by adding this event everything will fit in the available memory.
If a single event is too large for the internal buffers, more memory is allocated. On the other hand, if the buffer was provided by the user, then obviously the buffer cannot be expanded and false is returned.
The byte order of event must match the byte order given in constructor! This method is not thread-safe with respect to the node as it's backing ByteBuffer's limit and position may be concurrently changed.
Parameters
node event's EvioNode object
extraDataLen additional data bytes to follow event (e.g. trailer length).
Returns
true if event was added; false if the event was not added because the count limit would be exceeded or the buffer is full and cannot be expanded since it's user-provided.
Exceptions
EvioException if node does not correspond to a bank.
References addEvent().
build() [1/3]
void evio::RecordOutput::build ()
Builds the record.
Compresses data, header is constructed, then header & data written into internal buffer. This method may be called multiple times in succession without any problem.
References evio::Compressor::compressLZ4(), evio::Compressor::compressLZ4Best(), eventCount, eventSize, evio::Compressor::getInstance(), header, evio::RecordHeader::HEADER_SIZE_BYTES, indexSize, recordBinary, recordData, recordEvents, recordIndex, startingPosition, and evio::Compressor::UNCOMPRESSED.
Referenced by build(), evio::Writer::createRecord(), and evio::Writer::writeRecord().
build() [2/3]
void evio::RecordOutput::build (const ByteBuffer & userHeader)
Builds the record.
Compresses data, header is constructed, then header & data written into internal buffer. If user header is not padded to 4-byte boundary, it's done here. This method may be called multiple times in succession without any problem.
Parameters
userHeader user's ByteBuffer which must be READY-TO-READ!
References evio::ByteBuffer::array(), build(), evio::Compressor::compressLZ4(), evio::Compressor::compressLZ4Best(), eventCount, eventSize, evio::Compressor::getInstance(), header, evio::RecordHeader::HEADER_SIZE_BYTES, indexSize, evio::ByteBuffer::position(), recordBinary, recordData, recordEvents, recordIndex, evio::ByteBuffer::remaining(), startingPosition, and evio::Compressor::UNCOMPRESSED.
build() [3/3]
void evio::RecordOutput::build (std::shared_ptr< ByteBuffer > userHeader)
Builds the record.
Compresses data, header is constructed, then header & data written into internal buffer. If user header is not padded to 4-byte boundary, it's done here. This method may be called multiple times in succession without any problem.
Parameters
userHeader user's ByteBuffer which must be READY-TO-READ!
References build().
getBinaryBuffer()
const std::shared_ptr< ByteBuffer > evio::RecordOutput::getBinaryBuffer () const
Get the internal ByteBuffer used to construct binary representation of this record.
Returns
internal ByteBuffer used to construct binary representation of this record.
References recordBinary.
Referenced by evio::Writer::createRecord(), and evio::Writer::writeRecord().
getByteOrder()
const ByteOrder & evio::RecordOutput::getByteOrder () const
Get the byte order of the record to be built.
Returns
byte order of the record to be built.
References byteOrder.
Referenced by evio::Writer::writeRecord(), and evio::WriterMT::writeRecord().
getCompressionType()
const Compressor::CompressionType evio::RecordOutput::getCompressionType () const
Get the compression type of the contained record.
Implemented to allow "const" in RecordRingItem equal operator and copy constructor.
Returns
compression type of the contained record.
References header.
getEventCount()
uint32_t evio::RecordOutput::getEventCount () const
Get the number of events written so far into the buffer.
Returns
number of events written so far into the buffer
References eventCount.
getHeader()
std::shared_ptr< RecordHeader > & evio::RecordOutput::getHeader ()
Get the general header of this record.
Returns
general header of this record.
References header.
Referenced by evio::Writer::writeRecord().
getHeaderType()
const HeaderType evio::RecordOutput::getHeaderType () const
Get the header type of the contained record.
Implemented to allow "const" in RecordRingItem equal operator and copy constructor.
Returns
compression type of the contained record.
References header.
getInternalBufferCapacity()
uint32_t evio::RecordOutput::getInternalBufferCapacity () const
Get the capacity of the internal buffer in bytes.
This is the upper limit of the memory needed to store this uncompressed record.
Returns
capacity of the internal buffer in bytes.
References MAX_BUFFER_SIZE.
Referenced by evio::Writer::createRecord().
getMaxEventCount()
uint32_t evio::RecordOutput::getMaxEventCount () const
Get the maximum number of events allowed in this record.
Returns
maximum number of events allowed in this record.
References MAX_EVENT_COUNT.
getUncompressedSize()
uint32_t evio::RecordOutput::getUncompressedSize () const
Get the current uncompressed size of the record in bytes.
This does NOT count any user header.
Returns
current uncompressed size of the record in bytes.
References eventSize, evio::RecordHeader::HEADER_SIZE_BYTES, and indexSize.
getUserBufferSize()
uint32_t evio::RecordOutput::getUserBufferSize () const
Get the number of initially available bytes to be written into in the user-given buffer, that goes from position to limit.
The user-given buffer is referenced by recordBinary.
Returns
umber of initially available bytes to be written into in the user-given buffer.
References userBufferSize.
hasUserProvidedBuffer()
bool evio::RecordOutput::hasUserProvidedBuffer () const
Was the internal buffer provided by the user?
Returns
true if internal buffer provided by user.
References userProvidedBuffer.
oneTooMany()
bool evio::RecordOutput::oneTooMany () const
Does adding one more event exceed the event count limit?
Returns
true
if one more event exceeds count limit, else
false
.
References eventCount, and MAX_EVENT_COUNT.
Referenced by addEvent().
operator=() [1/2]
RecordOutput & evio::RecordOutput::operator= (const RecordOutput & other)
Assignment operator.
Parameters
other right side object.
Returns
left side object.
Exceptions
EvioException if trying to copy bigger record and internal buffer was provided by user.
References recordBinary, recordEvents, and recordIndex.
operator=() [2/2]
RecordOutput & evio::RecordOutput::operator= (RecordOutput && other) noexcept
Move assignment operator.
Parameters
other right side object.
Returns
left side object.
References eventCount.
reset()
void evio::RecordOutput::reset ()
Reset internal buffers.
The buffer is ready to receive new data. Also resets the header including removing any compression. If data buffer externally provided, the starting position is set to 0.
References eventCount, eventSize, header, indexSize, recordBinary, recordData, recordEvents, recordIndex, and startingPosition.
Referenced by addEvent(), and setBuffer().
roomForEvent()
bool evio::RecordOutput::roomForEvent (uint32_t length) const
Is there room in this record's memory for an additional event of the given length in bytes (length NOT including accompanying index).
Parameters
length length of data to add in bytes
Returns
true
if room in record, else
false
.
References eventSize, evio::RecordHeader::HEADER_SIZE_BYTES, indexSize, and MAX_BUFFER_SIZE.
Referenced by addEvent().
setBuffer()
void evio::RecordOutput::setBuffer (std::shared_ptr< ByteBuffer > & buf)
Reset internal buffers and set the buffer in which to build this record.
The given buffer should be made ready to receive new data by setting its position and limit properly. Its byte order is set to the same as this writer's. The argument ByteBuffer can be retrieved by calling getBinaryBuffer().
Parameters
buf buffer in which to build this record.
References byteOrder, MAX_BUFFER_SIZE, RECORD_BUFFER_SIZE, recordBinary, reset(), startingPosition, userBufferSize, and userProvidedBuffer.
setStartingBufferPosition()
void evio::RecordOutput::setStartingBufferPosition (size_t pos)
Set the starting position of the user-given buffer being written into.
Calling this may be necessary from EventWriter(Unsync) when a common record (dictionary + first event) is written after the constructor for this object has been called, but before any events have been written. This method should not be called in general as it will MESS UP THE WRITING OF DATA!
Parameters
pos position in buffer to start writing.
References recordBinary, and startingPosition.
transferDataForReading()
void evio::RecordOutput::transferDataForReading (const RecordOutput & rec)
Copy the contents of the arg into this object and get data buffer ready for reading.
If the arg has more data than will fit, increase buffer sizes. If the arg has more events than our allowed max, increase the max.
Parameters
rec object to copy, must be ready to read
Exceptions
EvioException if we cannot replace internal buffer if it needs to be expanded since it was provided by the user.
References eventSize, indexSize, recordBinary, recordEvents, and recordIndex.
Member Data Documentation
byteOrder
ByteOrder evio::RecordOutput::byteOrder {ByteOrder::ENDIAN_LOCAL}
Byte order of record byte arrays to build.
Referenced by RecordOutput(), getByteOrder(), and setBuffer().
eventCount
uint32_t evio::RecordOutput::eventCount = 0
Number of events written to this Record.
Referenced by addEvent(), build(), getEventCount(), oneTooMany(), operator=(), and reset().
eventSize
uint32_t evio::RecordOutput::eventSize = 0
Number of valid bytes in recordEvents buffer.
Referenced by addEvent(), build(), getUncompressedSize(), reset(), roomForEvent(), and transferDataForReading().
header
std::shared_ptr<RecordHeader> evio::RecordOutput::header
Header of this Record.
Referenced by RecordOutput(), build(), getCompressionType(), getHeader(), getHeaderType(), and reset().
indexSize
uint32_t evio::RecordOutput::indexSize = 0
Number of valid bytes in recordIndex buffer.
Will always be multiple of 4 since indexes are ints.
Referenced by addEvent(), build(), getUncompressedSize(), reset(), roomForEvent(), and transferDataForReading().
MAX_BUFFER_SIZE
uint32_t evio::RecordOutput::MAX_BUFFER_SIZE = 8*ONE_MEG
Size of some internal buffers in bytes.
If the recordBinary buffer is passed into the constructor or given through setBuffer(std::shared_ptr<ByteBuffer> &), then this value is 91% of the its size (from position to capacity). This allows some margin for compressed data to be larger than the uncompressed - which may happen if data is random. It also allows other records to have been previously stored in the given buffer (eg. common record) since it starts writing at the buffer position which may not be 0.
Referenced by RecordOutput(), addEvent(), getInternalBufferCapacity(), roomForEvent(), and setBuffer().
MAX_EVENT_COUNT
uint32_t evio::RecordOutput::MAX_EVENT_COUNT = 1000000
Maximum number of events per record.
Referenced by RecordOutput(), getMaxEventCount(), and oneTooMany().
ONE_MEG
constexpr int evio::RecordOutput::ONE_MEG = 1024*1024 static constexpr
Maximum number of events per record.
Referenced by addEvent().
RECORD_BUFFER_SIZE
uint32_t evio::RecordOutput::RECORD_BUFFER_SIZE = 9*ONE_MEG
Size of buffer holding built record in bytes.
If the recordBinary buffer is passed into the constructor or given through setBuffer(std::shared_ptr<ByteBuffer> &), then this value is set to be 10% bigger than MAX_BUFFER_SIZE. This allows some margin for compressed data to be larger than the uncompressed - which may happen if data is random.
Referenced by RecordOutput(), addEvent(), and setBuffer().
recordBinary
std::shared_ptr<ByteBuffer> evio::RecordOutput::recordBinary
Buffer in which to put constructed (& compressed) binary record.
May be provided by user.
Referenced by RecordOutput(), build(), getBinaryBuffer(), operator=(), reset(), setBuffer(), setStartingBufferPosition(), and transferDataForReading().
recordData
std::shared_ptr<ByteBuffer> evio::RecordOutput::recordData
This buffer stores data that will be compressed.
Referenced by build(), and reset().
recordEvents
std::shared_ptr<ByteBuffer> evio::RecordOutput::recordEvents
This buffer stores event data ONLY.
Referenced by RecordOutput(), addEvent(), build(), operator=(), reset(), and transferDataForReading().
recordIndex
std::shared_ptr<ByteBuffer> evio::RecordOutput::recordIndex
This buffer stores event lengths (in bytes) ONLY.
Referenced by RecordOutput(), addEvent(), build(), operator=(), reset(), and transferDataForReading().
startingPosition
size_t evio::RecordOutput::startingPosition = 0
The starting position of a user-given buffer.
No data will be written before this position.
Referenced by RecordOutput(), build(), reset(), setBuffer(), and setStartingBufferPosition().
userBufferSize
uint32_t evio::RecordOutput::userBufferSize = 0
The number of initially available bytes to be written into in the user-given buffer, that go from position to limit.
The user-given buffer is stored in recordBinary.
Referenced by RecordOutput(), getUserBufferSize(), and setBuffer().
userProvidedBuffer
bool evio::RecordOutput::userProvidedBuffer = false
Is recordBinary a user provided buffer?
Referenced by RecordOutput(), addEvent(), hasUserProvidedBuffer(), and setBuffer().
The documentation for this class was generated from the following files:
RecordOutput.h
RecordOutput.cpp