# scons build file for evio
Import('env', 'incDir', 'binDir', 'archDir', 'execLibs', 'debugSuffix')
import re
import os
from os import sep

 # lists of all C and C++ files
cfileList  = Glob('*.c',  strings=True)
ccfileList = Glob('*.cc', strings=True)
if(os.getenv('ETROOT')==None):
        ccfileList.remove('etTest.cc')           


# For each C file, create executable of the same name,
# and install that executable if "scons examples" is command
for fileName in cfileList:
    compiledFile = env.Program(source  = fileName,
                               LIBS    = ['evio'+debugSuffix] + execLibs,
                               LIBPATH = ['#src/libsrc/'+archDir],
                               CPPPATH = ['.', '#src/libsrc', incDir])
    env.Alias('examples', env.Install(target = binDir, source = compiledFile))


# If we store all compiled programs in a list and then
# install the list itself, for some unknown reason the
# whole variant library is copied into the install directory.
# So we do things individual file by individual file.

# compile and install
for fileName in ccfileList:
    if(os.getenv('ETROOT')!=None):
        libList  = ['evio'+debugSuffix, 'evioxx'+debugSuffix, 'et'+debugSuffix] + execLibs
        libpList = ['#src/libsrc/'+archDir,'#src/libsrc++/'+archDir,os.getenv('ETROOT')+'/'+archDir[1:]+'/lib'],
    else:
        libList    = ['evio'+debugSuffix, 'evioxx'+debugSuffix] + execLibs
        libpList = ['#src/libsrc/'+archDir,'#src/libsrc++/'+archDir],
    compiledFile = env.Program(source  = fileName,
                               LIBS    = libList,
                               LIBPATH = libpList,
                               CPPPATH = ['.', '#src/libsrc', '#src/libsrc++', incDir])
    env.Alias('examples', env.Install(target = binDir, source = compiledFile))
