evio: evio.h File Reference
evio.h File Reference
#include <stdint.h>
#include <stdio.h>
#include <pthread.h>
#include <stddef.h>
Data Structures
struct evfilestruct
This structure contains information about file opened for either reading or writing.
struct evioBlockHeaderV4_t
Structure for Sergei Boiarinov's use.
Macros
#define EV_VERSION 6
Evio format version, not the evio package version #.
#define EV_HDSIZ 8
Size of block header in 32 bit words.
#define EV_HDSIZ_V6 14
#define EV_HDSIZ_BYTES 32
#define EV_HDSIZ_BYTES_V6 56
#define S_SUCCESS 0
#define S_FAILURE (-1)
#define evio_err_abort(code, text)
#define S_EVFILE 0x00730000
evfile.msg Event File I/O
#define S_EVFILE_TRUNC 0x40730001
Event truncated on read/write.
#define S_EVFILE_BADBLOCK 0x40730002
Bad block number encountered.
#define S_EVFILE_BADHANDLE 0x80730001
Bad handle (file/stream not open)
#define S_EVFILE_ALLOCFAIL 0x80730002
Failed to allocate memory.
#define S_EVFILE_BADFILE 0x80730003
File format error.
#define S_EVFILE_UNKOPTION 0x80730004
Unknown option specified.
#define S_EVFILE_UNXPTDEOF 0x80730005
Unexpected end of file while reading event.
#define S_EVFILE_BADSIZEREQ 0x80730006
Invalid buffer size request to evIoct.
#define S_EVFILE_BADARG 0x80730007
Invalid function argument.
#define S_EVFILE_BADMODE 0x80730008
Wrong mode used in evOpen for this operation.
#define EVIO_SWAP64(x)
Macro for swapping 64 bit ints.
#define EVIO_SWAP32(x)
Macro for swapping 32 bit ints.
#define EVIO_SWAP16(x)
Macro for swapping 16 bit ints.
#define EVIO_TO_64_BITS(low, high)
Calculate a 64 bit result from 2 32 bit inputs.
#define EVIO_BH_LEN_OFFSET 0
Offset in bytes from beginning of block header to block length.
#define EVIO_BH_BLKNUM_OFFSET 32
Offset in bytes from beginning of block header to block number.
#define EVIO_BH_HDRLEN_OFFSET 64
Offset in bytes from beginning of block header to header length.
#define EVIO_BH_EVCOUNT_OFFSET 96
Offset in bytes from beginning of block header to event count.
#define EVIO_BH_BITINFO_OFFSET 160
Offset in bytes from beginning of block header to bitInfo.
#define EVIO_BH_MAGNUM_OFFSET 224
Offset in bytes from beginning of block header to magic number.
Typedefs
typedef struct evfilestruct EVFILE
This structure contains information about file opened for either reading or writing.
typedef struct evioBlockHeaderV4_t evioBlockHeaderV4
Structure for Sergei Boiarinov's use.
Functions
void set_user_frag_select_func (int32_t(*f)(int32_t tag))
int evioIsLocalHostBigEndian ()
Is the local host big endian?
uint64_t evioToLongWord (uint32_t word1, uint32_t word2, int needToSwap)
Take 2, 32 bit words and change that into a 64 bit word, taking endianness and swapping into account.
void evioswap (uint32_t *buffer, int tolocal, uint32_t *dest)
Routine to swap the endianness of an evio event (bank).
void evioSwapFileHeaderV6 (uint32_t *header)
Swap an evio version 6 file header in place (but not the following index arrary, etc).
void evioSwapRecordHeaderV6 (uint32_t *header)
Swap an evio version 6 record header in place (but not the following index arrary, etc).
uint16_t * swap_int16_t (uint16_t *data, unsigned int length, uint16_t *dest)
This routine swaps a buffer of 16 bit integers.
uint32_t * swap_int32_t (uint32_t *data, unsigned int length, uint32_t *dest)
This routine swaps a buffer of 32 bit integers.
uint64_t * swap_int64_t (uint64_t *data, unsigned int length, uint64_t *dest)
This routine swaps a buffer of 64 bit integers.
void evFileStructInit (EVFILE *a)
Routine to intialize an EVFILE structure for writing.
int evOpen (char *filename, char *flags, int *handle)
This function opens a file for either reading or writing evio format data.
int evOpenBuffer (char *buffer, uint32_t bufLen, char *flags, int *handle)
This function allows for either reading or writing evio format data from a buffer.
int evOpenSocket (int sockFd, char *flags, int *handle)
This function allows for either reading or writing evio format data from a TCP socket.
int evRead (int handle, uint32_t *buffer, uint32_t size)
This routine reads from an evio format file/socket/buffer opened with routines evOpen, evOpenBuffer, or evOpenSocket and returns the next event in the buffer arg.
int evReadAlloc (int handle, uint32_t **buffer, uint32_t *buflen)
This routine reads an evio bank from an evio format file/socket/buffer opened with routines evOpen, evOpenBuffer, or evOpenSocket, allocates a buffer and fills it with the bank.
int evReadNoCopy (int handle, const uint32_t **buffer, uint32_t *buflen)
This routine reads from an evio format file/buffer/socket opened with routines evOpen, evOpenBuffer, or evOpenSocket and returns a pointer to the next event residing in an internal buffer.
int evReadRandom (int handle, const uint32_t **pEvent, uint32_t *buflen, uint32_t eventNumber)
This routine does a random access read from an evio format file/buffer opened with routines evOpen or evOpenBuffer.
int evGetRandomAccessTable (int handle, uint32_t ***const table, uint32_t *len)
This routine gets an array of event pointers if the handle was opened in random access mode.
int evWrite (int handle, const uint32_t *buffer)
This routine writes an evio event to an internal buffer containing evio data.
int evIoctl (int handle, char *request, void *argp)
This routine changes various evio parameters used in reading and writing.
int evFlush (int handle)
This function flushes any remaining internally buffered data to file/socket.
int evClose (int handle)
This routine flushes any existing evio format data in an internal buffer (written to with evWrite) to the final destination file/socket/buffer opened with routines evOpen, evOpenBuffer, or evOpenSocket.
int evGetBufferLength (int handle, uint32_t *length)
This routine returns the number of bytes written into a buffer so far when given a handle provided by calling evOpenBuffer.
int evGetFileName (int handle, char *name, size_t maxLength)
This routine gets the name of the file currently being written to and opened with evOpen, Returned string may NOT be written into.
int evIsLastBlock (uint32_t sixthWord)
Routine to take the 6th word of a block header and tell whether it's the last block or not.
int evGetDictionary (int handle, char **dictionary, uint32_t *len)
This routine gets the dictionary associated with this handle if there is any.
int evStringsToBuf (uint32_t *buffer, int bufLen, char **strings, int stringCount, int *dataLen)
This routine writes an array of strings, in evio format, into the given buffer.
int evBufToStrings (char *buffer, int bufLen, char ***pStrArray, int *strCount)
This routine unpacks/parses an evio format buffer containing strings into an array of strings.
int evIsContainer (int type)
This routine return true (1) if given type is a container, else returns false (0).
const char * evGetTypename (int type)
This routine returns a string representation of an evio type.
char * evPerror (int error)
This routine returns a string describing the given error value.
void evPrintBuffer (uint32_t *p, uint32_t len, int swap)
Routine to print the contents of a buffer.
char * evStrReplace (char *orig, const char *replace, const char *with)
This routine substitutes a given string for a specified substring.
char * evStrReplaceEnvVar (const char *orig)
This routine finds constructs of the form and replaces it with the value of the ENV environmental variable if it exists or with nothing if it doesn't.
char * evStrFindSpecifiers (const char *orig, int *specifierCount)
This routine checks a string for C-style printing integer format specifiers.
char * evStrRemoveSpecifiers (const char *orig, int skip)
This routine checks a string for C-style printing integer format specifiers.
int evStrInsertBeforeSpecifier (char *str, uint32_t n, const char *insert, char *result, size_t result_size)
Inserts a string just before the first occurrence of a format specifier that starts with '' and ends with a conversion specifier of 'd' or 'x'.
int evGenerateBaseFileName (const char *origName, char **baseName, int *count)
char * evGenerateFileName (EVFILE *a, int specifierCount, uint32_t runNumber, int splitting, uint32_t splitNumber, char *runType, uint32_t streamId, uint32_t streamCount, int debug)
Macro Definition Documentation
EV_HDSIZ
#define EV_HDSIZ 8
Size of block header in 32 bit words.
Must never be smaller than 8, but can be set larger.
EV_HDSIZ_BYTES
#define EV_HDSIZ_BYTES 32
EV_HDSIZ_BYTES_V6
#define EV_HDSIZ_BYTES_V6 56
EV_HDSIZ_V6
#define EV_HDSIZ_V6 14
EV_VERSION
#define EV_VERSION 6
Evio format version, not the evio package version #.
EVIO_BH_BITINFO_OFFSET
#define EVIO_BH_BITINFO_OFFSET 160
Offset in bytes from beginning of block header to bitInfo.
EVIO_BH_BLKNUM_OFFSET
#define EVIO_BH_BLKNUM_OFFSET 32
Offset in bytes from beginning of block header to block number.
EVIO_BH_EVCOUNT_OFFSET
#define EVIO_BH_EVCOUNT_OFFSET 96
Offset in bytes from beginning of block header to event count.
EVIO_BH_HDRLEN_OFFSET
#define EVIO_BH_HDRLEN_OFFSET 64
Offset in bytes from beginning of block header to header length.
EVIO_BH_LEN_OFFSET
#define EVIO_BH_LEN_OFFSET 0
Offset in bytes from beginning of block header to block length.
EVIO_BH_MAGNUM_OFFSET
#define EVIO_BH_MAGNUM_OFFSET 224
Offset in bytes from beginning of block header to magic number.
evio_err_abort
#define evio_err_abort (code, text)
Value:
    do { \
    fprintf (stderr, "%s at \"%s\":%d: %s\n", \
        text, __FILE__, __LINE__, strerror (code)); \
    exit (-1); \
} while (0)
S_EVFILE
#define S_EVFILE 0x00730000
evfile.msg Event File I/O
S_EVFILE_ALLOCFAIL
#define S_EVFILE_ALLOCFAIL 0x80730002
Failed to allocate memory.
S_EVFILE_BADARG
#define S_EVFILE_BADARG 0x80730007
Invalid function argument.
S_EVFILE_BADBLOCK
#define S_EVFILE_BADBLOCK 0x40730002
Bad block number encountered.
S_EVFILE_BADFILE
#define S_EVFILE_BADFILE 0x80730003
File format error.
S_EVFILE_BADHANDLE
#define S_EVFILE_BADHANDLE 0x80730001
Bad handle (file/stream not open)
S_EVFILE_BADMODE
#define S_EVFILE_BADMODE 0x80730008
Wrong mode used in evOpen for this operation.
S_EVFILE_BADSIZEREQ
#define S_EVFILE_BADSIZEREQ 0x80730006
Invalid buffer size request to evIoct.
S_EVFILE_TRUNC
#define S_EVFILE_TRUNC 0x40730001
Event truncated on read/write.
S_EVFILE_UNKOPTION
#define S_EVFILE_UNKOPTION 0x80730004
Unknown option specified.
S_EVFILE_UNXPTDEOF
#define S_EVFILE_UNXPTDEOF 0x80730005
Unexpected end of file while reading event.
S_FAILURE
#define S_FAILURE (-1)
S_SUCCESS
#define S_SUCCESS 0
Typedef Documentation
EVFILE
typedef struct evfilestruct EVFILE
This structure contains information about file opened for either reading or writing.
evioBlockHeaderV4
typedef struct evioBlockHeaderV4_t evioBlockHeaderV4
Structure for Sergei Boiarinov's use.
Function Documentation
evFileStructInit()
void evFileStructInit (EVFILE * a)
Routine to intialize an EVFILE structure for writing.
If reading, relevant stuff gets overwritten anyway.
Parameters
a pointer to structure being inititalized
References evfilestruct::append, evfilestruct::baseFileName, evfilestruct::bigEndian, evfilestruct::blkEvCount, evfilestruct::blkEvMax, evfilestruct::blknum, evfilestruct::blkNumDiff, evfilestruct::blksiz, evfilestruct::blkSizeTarget, evfilestruct::blocksToParse, evfilestruct::buf, evfilestruct::bufRealSize, evfilestruct::bufSize, evfilestruct::byte_swapped, evfilestruct::bytesToBuf, evfilestruct::bytesToDataBuf, evfilestruct::bytesToFile, evfilestruct::commonBlkCount, evfilestruct::curRecordIndexArrayLen, evfilestruct::curRecordUserHeaderLen, evfilestruct::currentHeader, evfilestruct::dataBuf, evfilestruct::dataLeft, evfilestruct::dataNext, evfilestruct::dictBuf, evfilestruct::dictionary, evfilestruct::dictLength, EV_BLOCKSIZE, EV_EVENTS_MAX_DEF, EV_HDSIZ, EV_HDSIZ_BYTES, EV_HDSIZ_BYTES_V6, EV_HDSIZ_V6, EV_MAGIC, EV_SPLIT_SIZE, EV_VERSION, evfilestruct::eventCount, evfilestruct::eventLengths, evfilestruct::eventLengthsLen, evfilestruct::eventsToBuf, evfilestruct::eventsToFile, evioIsLocalHostBigEndian(), evfilestruct::file, evfilestruct::fileIndexArrayLen, evfilestruct::fileName, evfilestruct::filePosition, evfilestruct::fileSize, evfilestruct::fileUserHeaderLen, evfilestruct::firstEventBuf, evfilestruct::firstEventLength, evfilestruct::handle, evfilestruct::hasAppendDictionary, evfilestruct::isLastBlock, evfilestruct::lastEmptyBlockHeaderExists, evfilestruct::left, evfilestruct::lockingOn, evfilestruct::magic, evfilestruct::mmapFile, evfilestruct::mmapFileSize, evfilestruct::next, evfilestruct::pBuf, evfilestruct::pTable, evfilestruct::randomAccess, evfilestruct::runNumber, evfilestruct::runType, evfilestruct::rw, evfilestruct::rwBuf, evfilestruct::rwBufSize, evfilestruct::rwBytesIn, evfilestruct::rwBytesOut, evfilestruct::rwFirstWrite, evfilestruct::sockFd, evfilestruct::specifierCount, evfilestruct::split, evfilestruct::splitNumber, evfilestruct::splitting, evfilestruct::streamCount, evfilestruct::streamId, evfilestruct::trailerPosition, evfilestruct::version, and evfilestruct::wroteDictionary.
Referenced by evOpenFake().
evGenerateBaseFileName()
int evGenerateBaseFileName (const char * origName, char ** baseName, int * count)
This routine generates a (base) file name from a name containing format specifiers and enviromental variables.
The file name may contain characters of the form $(ENV_VAR) which will be substituted with the value of the associated environmental variable or a blank string if none is found.
The given name may contain up to 3, C-style integer format specifiers (such as %03d, or x). If more than 3 are found, an error is returned. If no "0" precedes any integer between the "%" and the "d" or "x" of the format specifier, it will be added automatically in order to avoid spaces in the final, generated file name.
See the doc for evGenerateFileName. The details of what is substituted for the int specifiers is given there.
Parameters
origName file name to modify
baseName pointer which gets filled with resulting file name
count pointer to int filled with number of format specifiers found
Returns
S_SUCCESS if successful
S_FAILURE if bad format specifiers or more that 3 specifiers found
S_EVFILE_BADARG if args are null or origName is invalid
S_EVFILE_ALLOCFAIL if out-of-memory
References evStrFindSpecifiers(), evStrReplaceEnvVar(), S_EVFILE_ALLOCFAIL, S_EVFILE_BADARG, S_FAILURE, and S_SUCCESS.
evGenerateFileName()
char* evGenerateFileName (EVFILE * a, int specifierCount, uint32_t runNumber, int splitting, uint32_t splitNumber, char * runType, uint32_t streamId, uint32_t streamCount, int debug)
This method generates a complete file name from the previously determined baseFileName obtained from calling evGenerateBaseFileName(char *, char **, int *) and stored in the evOpen handle.
All occurrences of the string "%s" in the baseFileName will be substituted with the value of the runType arg or nothing if the runType is null.
The given fileName may contain uyp to 3, C-style int format specifiers which will be substituted with runNumber, splitNumber and streamId in the manner described below.
If file is to be split:
If no specifiers:
for one stream, splitNumber is tacked onto the end of the file name as .<splitNumber>
for multiple streams, streamId and splitNumber are tacked onto the end of the file name as .<streamId>.<splitNumber>
No run numbers are ever tacked on without a specifier
If 1 specifier:
add runNumber according to specifier
for one stream, splitNumber is tacked onto the end of the file name as .<splitNumber>
for multiple streams, streamId and splitNumber are tacked onto the end of the file name as .<streamId>.<splitNumber>
If 2 specifiers:
add runNumber according to first specifier
for one stream, add splitNumber according to second specifier
for multiple streams, add splitNumber according to second specifier, but place <streamId>. just before the splitNumber
If 3 specifiers:
add runNumber according to first specifier
add streamId according to second specifier add splitNumber according to third specifier
If file is NOT split:
If no specifiers:
streamId is tacked onto the end of the file name as .<streamId>
No run numbers are ever tacked on without a specifier.
If 1 specifier:
add runNumber according to specifier
for multiple streams, streamId is tacked onto the end of the file name as ..<streamId>
If 2 specifiers:
add runNumber according to first specifier
remove second specifier
for multiple streams, streamId is tacked onto the end of the file name as .<streamId>
If 3 specifiers:
add runNumber according to first specifier
add streamId according to second specifier
remove third specifier
If there are more than 3 specifiers, NO SUBSTITUTIONS ARE DONE on the extra specifiers.
Parameters
a evio handle (contains file name to use as a basis for the generated file name)
specifierCount number of C-style int format specifiers in file name arg
runNumber CODA run number
splitting is file being split (split > 0)? 1 - yes, 0 - no
splitNumber number of the split file
runType run type name
streamId streamId number (100 > id > -1)
streamCount total number of streams in DAQ (100 > id > 0)
debug if = 0, no debug output
Returns
NULL if error
generated file name (free if non-NULL)
If we're not splitting files, then CODA isn't being used and stream id is probably meaningless.
evIsLastBlock()
int evIsLastBlock (uint32_t sixthWord)
Routine to take the 6th word of a block header and tell whether it's the last block or not.
Parameters
sixthWord 6th word of an evio block header
Returns
1 of this is the last block, else 0
References EV_LASTBLOCK_MASK.
evPrintBuffer()
void evPrintBuffer (uint32_t * p, uint32_t len, int swap)
Routine to print the contents of a buffer.
Parameters
p pointer to buffer
len number of 32-bit words to print out
swap swap if true
References EVIO_SWAP32.
evStrFindSpecifiers()
char* evStrFindSpecifiers (const char * orig, int * specifierCount)
This routine checks a string for C-style printing integer format specifiers.
More specifically, it checks for nd and nx where n can be multiple digits. It makes sure that there is at least one digit between % and x/d and that the first digit is a "0" so that generated filenames contain no white space. It returns the modified string or NULL if error. Free the result if non-NULL. It also returns the number of valid specifiers found in the orig argument.
Parameters
orig string to be checked/modified
specifierCount pointer to int which gets filled with the number of valid format specifiers in the orig arg
Returns
resulting string which is NULL if there is a problem and needs to be freed if not NULL.
Referenced by evGenerateBaseFileName().
evStrInsertBeforeSpecifier()
int evStrInsertBeforeSpecifier (char * str, uint32_t n, const char * insert, char * result, size_t result_size)
Inserts a string just before the first occurrence of a format specifier that starts with '' and ends with a conversion specifier of 'd' or 'x'.
The existing format specifier can include flags made of ints indicating width (ie %03x). This function partly courtesy of ChatGPT. Remember, when this is called, the substitution for s with runType will have already been made.
Parameters
str string to scan
n number of "%"s to skip over before making the insert
insert string to insert before the int specifier
result resulting string
result_size size of result string
Returns
1 if specifier successfully inserted, 0 if nothing done, -1 if result is too small. If 1 is not returned, result is not written into.
evStrRemoveSpecifiers()
char* evStrRemoveSpecifiers (const char * orig, int skip)
This routine checks a string for C-style printing integer format specifiers.
More specifically, it checks for nd and nx where n can be multiple digits. It removes all such specifiers and returns the modified string or NULL if error. Skips over given # of int specifiers. Free the result if non-NULL.
Parameters
orig string to be checked/modified
skip # of int specifiers to skip
Returns
resulting string which is NULL if there is a problem and needs to be freed if not NULL.
How many int specifiers skipped so far.
Referenced by evGenerateFileNameOld().
evStrReplace()
char* evStrReplace (char * orig, const char * replace, const char * with)
This routine substitutes a given string for a specified substring.
Free the result if non-NULL.
Parameters
orig string to modify
replace substring in orig arg to replace
with string to substitute for replace arg
Returns
resulting string which is NULL if there is a problem and needs to be freed if not NULL.
Referenced by evGenerateFileNameOld(), and evStrReplaceEnvVar().
evStrReplaceEnvVar()
char* evStrReplaceEnvVar (const char * orig)
This routine finds constructs of the form and replaces it with the value of the ENV environmental variable if it exists or with nothing if it doesn't.
Simple enough to do without regular expressions. Free the result if non-NULL.
Parameters
orig string to modify
Returns
resulting string which is NULL if there is a problem and needs to be freed if not NULL.
References evStrReplace().
Referenced by evGenerateBaseFileName().
set_user_frag_select_func()
void set_user_frag_select_func (int32_t(*)(int32_t tag) f)