evio: evio::StructureFinder Class Reference
evio::StructureFinder Class Reference
This is a set of convenient static methods used to find lists of structures within an event, bank, segment, or tagsegment that match certain criteria.
#include <StructureFinder.h>
Static Public Member Functions
static void getMatchingStructures (std::shared_ptr< BaseStructure > structure, std::shared_ptr< IEvioFilter > filter, std::vector< std::shared_ptr< BaseStructure >> &vec)
Collect all the structures in an event that pass a filter.
static void getMatchingBanks (std::shared_ptr< BaseStructure > structure, uint16_t tag, uint8_t num, std::vector< std::shared_ptr< BaseStructure >> &vec)
Collect all the banks in an event that match a provided tag and number in their header.
static void getMatchingStructures (std::shared_ptr< BaseStructure > structure, uint16_t tag, std::vector< std::shared_ptr< BaseStructure >> &vec)
Collect all the structures in an event that match a provided tag in their header.
static void getMatchingNonBanks (std::shared_ptr< BaseStructure > structure, uint16_t tag, std::vector< std::shared_ptr< BaseStructure >> &vec)
Collect all the non-banks (i.e., Segments and TagSegments) in an event that match a provided tag in their header.
static void getMatchingStructures (std::shared_ptr< BaseStructure > structure, std::string name, EvioXMLDictionary &dictionary, std::vector< std::shared_ptr< BaseStructure >> &vec)
Collect all structures in an event that match the given dictionary name.
static void getMatchingParent (std::shared_ptr< BaseStructure > structure, std::string parentName, EvioXMLDictionary &dictionary, std::vector< std::shared_ptr< BaseStructure >> &vec)
Collect all structures in an event whose parent has the given dictionary name.
static void getMatchingChild (std::shared_ptr< BaseStructure > structure, std::string childName, EvioXMLDictionary &dictionary, std::vector< std::shared_ptr< BaseStructure >> &vec)
Collect all structures in an event who has a child with the given dictionary name.
Detailed Description
This is a set of convenient static methods used to find lists of structures within an event, bank, segment, or tagsegment that match certain criteria.
For the most part it uses the BaseStructure#getMatchingStructures() method on the provided EvioEvent object by constructing the appropriate filter.
Author
heddle
timmer
Member Function Documentation
getMatchingBanks()
static void evio::StructureFinder::getMatchingBanks (std::shared_ptr< BaseStructure > structure, uint16_t tag, uint8_t num, std::vector< std::shared_ptr< BaseStructure >> & vec) inline static
Collect all the banks in an event that match a provided tag and number in their header.
Only Banks are returned, because only Banks have a number field.
Parameters
structure the event/bank/seg/tagseg being queried.
tag the tag to match.
num the number to match.
vec vector provided to contain all Banks that are accepted by the filter for the provided event.
References getMatchingStructures(), and evio::StructureType::STRUCT_BANK.
getMatchingChild()
static void evio::StructureFinder::getMatchingChild (std::shared_ptr< BaseStructure > structure, std::string childName, EvioXMLDictionary & dictionary, std::vector< std::shared_ptr< BaseStructure >> & vec) inline static
Collect all structures in an event who has a child with the given dictionary name.
Parameters
structure the event/bank/seg/tagseg being queried.
childName dictionary name of a child of structures to be returned.
dictionary dictionary to be used; if null, an existing global dictionary will be used.
vec vector provided to contain BaseStructures who have a child with the given name in the given dictionary.
References getMatchingStructures(), and evio::EvioXMLDictionary::getName().
getMatchingNonBanks()
static void evio::StructureFinder::getMatchingNonBanks (std::shared_ptr< BaseStructure > structure, uint16_t tag, std::vector< std::shared_ptr< BaseStructure >> & vec) inline static
Collect all the non-banks (i.e., Segments and TagSegments) in an event that match a provided tag in their header.
No Banks are returned.
Parameters
structure the event/bank/seg/tagseg being queried.
tag the tag to match.
vec vector provided to contain all non-bank structures that are accepted by the filter for the provided event.
References getMatchingStructures(), and evio::StructureType::STRUCT_BANK.
getMatchingParent()
static void evio::StructureFinder::getMatchingParent (std::shared_ptr< BaseStructure > structure, std::string parentName, EvioXMLDictionary & dictionary, std::vector< std::shared_ptr< BaseStructure >> & vec) inline static
Collect all structures in an event whose parent has the given dictionary name.
Parameters
structure the event/bank/seg/tagseg being queried.
parentName dictionary name of parent of structures to be returned.
dictionary dictionary to be used.
vec vector provided to contain BaseStructures whose parent has the given name in the given dictionary.
References getMatchingStructures(), and evio::EvioXMLDictionary::getName().
getMatchingStructures() [1/3]
static void evio::StructureFinder::getMatchingStructures (std::shared_ptr< BaseStructure > structure, std::shared_ptr< IEvioFilter > filter, std::vector< std::shared_ptr< BaseStructure >> & vec) inline static
Collect all the structures in an event that pass a filter.
Parameters
structure the event/bank/seg/tagseg being queried.
filter the filter that must be passed. If null, this will return all the structures.
vec vector provided to contain all structures that are accepted by the filter for the provided event.
Referenced by getMatchingBanks(), getMatchingChild(), getMatchingNonBanks(), getMatchingParent(), and getMatchingStructures().
getMatchingStructures() [2/3]
static void evio::StructureFinder::getMatchingStructures (std::shared_ptr< BaseStructure > structure, std::string name, EvioXMLDictionary & dictionary, std::vector< std::shared_ptr< BaseStructure >> & vec) inline static
Collect all structures in an event that match the given dictionary name.
Parameters
structure the event/bank/seg/tagseg being queried.
name dictionary name of structures to be returned.
dictionary dictionary to be used.
vec vector provided to contain BaseStructures that have the given name in the given dictionary.
References getMatchingStructures(), and evio::EvioXMLDictionary::getName().
getMatchingStructures() [3/3]
static void evio::StructureFinder::getMatchingStructures (std::shared_ptr< BaseStructure > structure, uint16_t tag, std::vector< std::shared_ptr< BaseStructure >> & vec) inline static
Collect all the structures in an event that match a provided tag in their header.
Parameters
structure the event/bank/seg/tagseg being queried.
tag the tag to match.
vec vector provided to contain all structures that are accepted by the filter for the provided event.
References getMatchingStructures().
The documentation for this class was generated from the following file:
StructureFinder.h