evio: evio::EvioTagSegment Class Reference
evio::EvioTagSegment Class Reference
This holds a CODA TagSegment structure.
#include <EvioTagSegment.h>
Public Types
typedef size_t size_type
typedef std::ptrdiff_t difference_type
typedef std::input_iterator_tag iterator_category
typedef std::shared_ptr< BaseStructure > value_type
typedef std::shared_ptr< BaseStructure > reference
typedef std::shared_ptr< BaseStructure > pointer
typedef nodeIterator< std::shared_ptr< BaseStructure > > iterator
typedef nodeBreadthIterator< std::shared_ptr< BaseStructure > > breadth_iterator
Public Member Functions
StructureType getStructureType () const override
This implements the virtual method from BaseStructure.
iterator begin ()
Get the beginning depth-first iterator.
iterator end ()
Get the end depth-first iterator.
breadth_iterator bbegin ()
Get the beginning breadth-first iterator.
breadth_iterator bend ()
Get the end breadth-first iterator.
std::shared_ptr< BaseStructure > getThis ()
std::shared_ptr< const BaseStructure > getThisConst () const
void insert (const std::shared_ptr< BaseStructure > newChild, size_t childIndex)
Removes newChild from its present parent (if it has a parent), sets the child's parent to this node, and then adds the child to this node's child array at index childIndex.
void remove (size_t childIndex)
Removes the child at the specified index from this node's children and sets that node's parent to null.
void remove (const std::shared_ptr< BaseStructure > aChild)
Removes aChild from this node's child vector, giving it a null parent.
std::shared_ptr< BaseStructure > getParent () const
Returns this node's parent or null if this node has no parent.
std::vector< std::shared_ptr< BaseStructure > > getChildren () const
Get the children of this structure.
std::shared_ptr< BaseStructure > getChildAt (size_t index) const
Returns the child at the specified index in this node's child vector.
size_t getChildCount () const
Returns the number of children of this node.
ssize_t getIndex (const std::shared_ptr< BaseStructure > aChild)
Returns the index of the specified child in this node's child vector.
std::vector< std::shared_ptr< BaseStructure > >::iterator childrenBegin ()
Creates and returns a forward-order begin iterator of this node's children.
std::vector< std::shared_ptr< BaseStructure > >::iterator childrenEnd ()
Creates and returns a forward-order end iterator of this node's children.
void setAllowsChildren (bool allows)
Determines whether or not this node is allowed to have children.
bool getAllowsChildren () const
Returns true if this node is allowed to have children.
void removeFromParent ()
Removes the subtree rooted at this node from the tree, giving this node a null parent.
void removeAllChildren ()
Removes all of this node's children, setting their parents to null.
void add (std::shared_ptr< BaseStructure > newChild)
Removes newChild from its parent and makes it a child of this node by adding it to the end of this node's child array.
bool isNodeAncestor (const std::shared_ptr< BaseStructure > anotherNode) const
Returns true if anotherNode is an ancestor of this node – if it is this node, this node's parent, or an ancestor of this node's parent.
bool isNodeDescendant (std::shared_ptr< BaseStructure > anotherNode)
Returns true if anotherNode is a descendant of this node – if it is this node, one of this node's children, or a descendant of one of this node's children.
std::shared_ptr< BaseStructure > getSharedAncestor (std::shared_ptr< BaseStructure > aNode)
Returns the nearest common ancestor to this node and aNode.
bool isNodeRelated (std::shared_ptr< BaseStructure > aNode)
Returns true if and only if aNode is in the same tree as this node.
uint32_t getDepth ()
Returns the depth of the tree rooted at this node – the longest distance from this node to a leaf.
uint32_t getLevel () const
Returns the number of levels above this node – the distance from the root to this node.
std::vector< std::shared_ptr< BaseStructure > > getPath ()
Returns the path from the root, to get to this node.
std::shared_ptr< BaseStructure > getRoot ()
Returns the root of the tree that contains this node.
bool isRoot () const
Returns true if this node is the root of the tree.
std::shared_ptr< BaseStructure > getNextNode ()
Returns the node that follows this node in a preorder traversal of this node's tree (return left nodes all the way down before coming back and doing siblings from bottom up).
std::shared_ptr< BaseStructure > getPreviousNode ()
Returns the node that precedes this node in a preorder traversal of this node's tree (return left nodes all the way down before coming back and doing siblings from bottom up).
bool isNodeChild (const std::shared_ptr< BaseStructure > aNode) const
Returns true if aNode is a child of this node.
std::shared_ptr< BaseStructure > getFirstChild () const
Returns this node's first child.
std::shared_ptr< BaseStructure > getLastChild () const
Returns this node's last child.
std::shared_ptr< BaseStructure > getChildAfter (const std::shared_ptr< BaseStructure > aChild)
Returns the child in this node's child vector that immediately follows aChild, which must be a child of this node.
std::shared_ptr< BaseStructure > getChildBefore (const std::shared_ptr< BaseStructure > aChild)
Returns the child in this node's child vector that immediately precedes aChild, which must be a child of this node.
bool isNodeSibling (const std::shared_ptr< BaseStructure > anotherNode) const
Returns true if anotherNode is a sibling of (has the same parent as) this node.
size_t getSiblingCount () const
Returns the number of siblings of this node.
std::shared_ptr< BaseStructure > getNextSibling ()
Returns the next sibling of this node in the parent's children vector.
std::shared_ptr< BaseStructure > getPreviousSibling ()
Returns the previous sibling of this node in the parent's children vector.
bool isLeaf () const
Returns true if this node has no children.
std::shared_ptr< BaseStructure > getFirstLeaf ()
Finds and returns the first leaf that is a descendant of this node – either this node or its first child's first leaf.
std::shared_ptr< BaseStructure > getLastLeaf ()
Finds and returns the last leaf that is a descendant of this node – either this node or its last child's last leaf.
std::shared_ptr< BaseStructure > getNextLeaf ()
Returns the leaf after this node or null if this node is the last leaf in the tree.
std::shared_ptr< BaseStructure > getPreviousLeaf ()
Returns the leaf before this node or null if this node is the first leaf in the tree.
ssize_t getLeafCount ()
Returns the total number of leaves that are descendants of this node.
void visitAllStructures (std::shared_ptr< IEvioListener > listener)
Visit all the structures in this structure (including the structure itself – which is considered its own descendant).
void visitAllStructures (std::shared_ptr< IEvioListener > listener, std::shared_ptr< IEvioFilter > filter)
Visit all the structures in this structure (including the structure itself – which is considered its own descendant) in a depth first manner.
void getMatchingStructures (std::shared_ptr< IEvioFilter > filter, std::vector< std::shared_ptr< BaseStructure >> &vec)
Visit all the descendant structures, and collect those that pass a filter.
void transform (std::shared_ptr< BaseStructure > const &structure)
This method does a partial copy and is designed to help convert between banks, segments,and tagsegments in the StructureTransformer class (hence the name "transform").
ByteOrder getByteOrder ()
What is the byte order of this data?
void setByteOrder (ByteOrder const &order)
Set the byte order of this data.
bool needSwap () const
Is a byte swap required (i.e.
virtual std::string toString () const
Obtain a string representation of the structure.
std::string treeToString (std::string const &indent) const
Recursive method to obtain a string representation of the entire tree structure rooted at this structure.
std::shared_ptr< BaseStructureHeader > getHeader () const
Return the header for this structure.
size_t write (ByteBuffer &dest)
Write myself out into a byte buffer with fastest algorithm I could find.
size_t write (uint8_t *dest, ByteOrder const &order)
Write myself out to a pointer.
size_t writeQuick (uint8_t *dest)
Write myself out as evio format data in the data's current byte order given by getByteOrder() at the given pointer.
size_t writeQuick (ByteBuffer &dest)
Write myself into a ByteBuffer as evio format data in the data's current byte order given by getByteOrder().
uint32_t getNumberDataItems ()
Get the number of stored data items like number of banks, ints, floats, etc.
uint32_t setAllHeaderLengths ()
Compute and set length of all header fields for this structure and all its descendants.
bool isContainer () const
Checks whether this structure is a container, i.e.
uint32_t getTotalBytes () const
Get the length of this structure in bytes, including the header.
std::vector< uint8_t > & getRawBytes ()
Get the raw data of the structure.
std::vector< int16_t > & getShortData ()
Gets the raw data as an int16_t vector if the content type as indicated by the header is appropriate.
std::vector< uint16_t > & getUShortData ()
Gets the raw data as an uint16_t vector if the content type as indicated by the header is appropriate.
std::vector< int32_t > & getIntData ()
Gets the raw data as an int32_t vector if the content type as indicated by the header is appropriate.
std::vector< uint32_t > & getUIntData ()
Gets the raw data as an uint32_t vector if the content type as indicated by the header is appropriate.
std::vector< int64_t > & getLongData ()
Gets the raw data as an int64_t vector if the content type as indicated by the header is appropriate.
std::vector< uint64_t > & getULongData ()
Gets the raw data as an uint64_t vector if the content type as indicated by the header is appropriate.
std::vector< float > & getFloatData ()
Gets the raw data as a float vector if the content type as indicated by the header is appropriate.
std::vector< double > & getDoubleData ()
Gets the raw data as a double vector if the content type as indicated by the header is appropriate.
std::vector< signed char > & getCharData ()
Gets the raw data as an signed char vector, if the contents type as indicated by the header is appropriate.
std::vector< unsigned char > & getUCharData ()
Gets the raw data as an unsigned char vector, if the contents type as indicated by the header is appropriate.
std::vector< std::shared_ptr< CompositeData > > & getCompositeData ()
Gets the composite data as an vector of CompositeData objects, if the content type as indicated by the header is appropriate.
std::vector< std::string > & getStringData ()
Gets the raw data (ascii) as an vector of string objects, if the contents type as indicated by the header is appropriate.
uint32_t unpackRawBytesToStrings ()
Extract string data from rawBytes array.
void updateIntData ()
If data in this structure was changed by modifying the vector returned from getIntData(), then this method needs to be called in order to make this object internally consistent.
void updateUIntData ()
If data in this structure was changed by modifying the vector returned from getUIntData(), then this method needs to be called in order to make this object internally consistent.
void updateShortData ()
If data in this structure was changed by modifying the vector returned from getShortData(), then this method needs to be called in order to make this object internally consistent.
void updateUShortData ()
If data in this structure was changed by modifying the vector returned from getUShortData(), then this method needs to be called in order to make this object internally consistent.
void updateLongData ()
If data in this structure was changed by modifying the vector returned from getLongData(), then this method needs to be called in order to make this object internally consistent.
void updateULongData ()
If data in this structure was changed by modifying the vector returned from getULongData(), then this method needs to be called in order to make this object internally consistent.
void updateCharData ()
If data in this structure was changed by modifying the vector returned from getCharData(), then this method needs to be called in order to make this object internally consistent.
void updateUCharData ()
If data in this structure was changed by modifying the vector returned from getUCharData(), then this method needs to be called in order to make this object internally consistent.
void updateFloatData ()
If data in this structure was changed by modifying the vector returned from getFloatData(), then this method needs to be called in order to make this object internally consistent.
void updateDoubleData ()
If data in this structure was changed by modifying the vector returned from getDoubleData(), then this method needs to be called in order to make this object internally consistent.
void updateStringData ()
If data in this structure was changed by modifying the vector returned from getStringData(), then this method needs to be called in order to make this object internally consistent.
void updateCompositeData ()
If data in this structure was changed by modifying the vector returned from getCompositeData(), then this method needs to be called in order to make this object internally consistent.
Static Public Member Functions
static std::shared_ptr< EvioTagSegment > getInstance (std::shared_ptr< TagSegmentHeader > const &head)
Method to return a shared pointer to a constructed object of this class.
static std::shared_ptr< EvioTagSegment > getInstance (uint16_t tag, DataType const &typ)
Method to return a shared pointer to a constructed object of this class.
static void stringsToRawBytes (std::vector< std::string > &strings, std::vector< uint8_t > &bytes)
This method transforms a vector of strings into raw evio format data, not including header.
static void unpackRawBytesToStrings (std::vector< uint8_t > &bytes, size_t offset, std::vector< std::string > &strData)
This method extracts a vector of strings from bytes of raw evio string data.
static void unpackRawBytesToStrings (std::vector< uint8_t > &bytes, size_t offset, size_t maxLength, std::vector< std::string > &strData)
This method extracts a vector of strings from bytes of raw evio string data.
static void unpackRawBytesToStrings (uint8_t *bytes, size_t length, std::vector< std::string > &strData)
This method extracts a vector of strings from bytes of raw evio string data.
static void unpackRawBytesToStrings (ByteBuffer &buffer, size_t pos, size_t length, std::vector< std::string > &strData)
This method extracts a vector of strings from buffer containing raw evio string data.
static uint32_t stringToRawSize (const std::string &str)
This method returns the number of bytes in a raw evio format of the given string vector, not including header.
static uint32_t stringsToRawSize (std::vector< std::string > const &strings)
This method returns the number of bytes in a raw evio format of the given string vector, not including header.
Protected Member Functions
void setParent (const std::shared_ptr< BaseStructure > &newParent)
Sets this node's parent to newParent but does not change the parent's child array.
std::vector< std::shared_ptr< BaseStructure > > getPathToRoot (const std::shared_ptr< BaseStructure > &aNode, int depth) const
Builds the parents of node up to and including the root node, where the original node is the last element in the returned vector.
bool getLengthsUpToDate () const
Get whether the lengths of all header fields for this structure and all it descendants are up to date or not.
void setLengthsUpToDate (bool lengthsUpToDate)
Set whether the lengths of all header fields for this structure and all it descendants are up to date or not.
uint32_t dataLength ()
Compute the dataLength in 32-bit words.
void stringsToRawBytes ()
This method transforms the internal vector of strings into internal rawBytes vector of evio format data not including header.
void setRawBytes (uint8_t *bytes, uint32_t len)
Set the data for the structure.
void setRawBytes (std::vector< uint8_t > &bytes)
Set the data for the structure.
Protected Attributes
std::shared_ptr< BaseStructure > parent = nullptr
This node's parent, or null if this node has no parent.
std::vector< std::shared_ptr< BaseStructure > > children
Array of children, may be null if this node has no children.
bool allowsChildren = true
True if the node is able to have children.
std::shared_ptr< BaseStructureHeader > header
Holds the header of the bank as a shared pointer.
std::vector< uint8_t > rawBytes
The raw data of the structure.
std::vector< int16_t > shortData
Used if raw data should be interpreted as shorts.
std::vector< uint16_t > ushortData
Used if raw data should be interpreted as unsigned shorts.
std::vector< int32_t > intData
Used if raw data should be interpreted as ints.
std::vector< uint32_t > uintData
Used if raw data should be interpreted as unsigned ints.
std::vector< int64_t > longData
Used if raw data should be interpreted as longs.
std::vector< uint64_t > ulongData
Used if raw data should be interpreted as unsigned longs.
std::vector< double > doubleData
Used if raw data should be interpreted as doubles.
std::vector< float > floatData
Used if raw data should be interpreted as floats.
std::vector< std::shared_ptr< CompositeData > > compositeData
Used if raw data should be interpreted as composite type.
std::vector< signed char > charData
Used if raw data should be interpreted as signed chars.
std::vector< unsigned char > ucharData
Used if raw data should be interpreted as unsigned chars.
std::vector< std::string > stringList
Used if raw data should be interpreted as a string.
int stringEnd = 0
Keep track of end of the last string added to stringData (including null but not padding).
bool badStringFormat = false
True if char data has non-ascii or non-printable characters, or has too little data to be in proper format.
size_t numberDataItems = 0
The number of stored data items like number of banks, ints, floats, etc.
ByteOrder byteOrder {ByteOrder::ENDIAN_LOCAL}
Endianness of the raw data if appropriate.
bool lengthsUpToDate = false
Keep track of whether header length data is up-to-date or not.
Detailed Description
This holds a CODA TagSegment structure.
Mostly it has a header (a TagSegementHeader) and the raw data stored as a vector.
Author
heddle
timmer
Member Typedef Documentation
breadth_iterator
typedef nodeBreadthIterator<std::shared_ptr<BaseStructure> > evio::BaseStructure::breadth_iterator inherited
difference_type
typedef std::ptrdiff_t evio::BaseStructure::difference_type inherited
iterator
typedef nodeIterator<std::shared_ptr<BaseStructure> > evio::BaseStructure::iterator inherited
iterator_category
typedef std::input_iterator_tag evio::BaseStructure::iterator_category inherited
pointer
typedef std::shared_ptr<BaseStructure> evio::BaseStructure::pointer inherited
reference
typedef std::shared_ptr<BaseStructure> evio::BaseStructure::reference inherited
size_type
typedef size_t evio::BaseStructure::size_type inherited
value_type
typedef std::shared_ptr<BaseStructure> evio::BaseStructure::value_type inherited
Member Function Documentation
add()
void evio::BaseStructure::add (std::shared_ptr< BaseStructure > newChild) inherited
Removes newChild from its parent and makes it a child of this node by adding it to the end of this node's child array.
Originally part of java's DefaultMutableTreeNode.
See also
insert
Parameters
newChild node to add as a child of this node.
Exceptions
EvioException if newChild is null, or this node does not allow children.
References evio::BaseStructure::getChildCount(), evio::BaseStructure::getThis(), and evio::BaseStructure::insert().
bbegin()
breadth_iterator evio::BaseStructure::bbegin () inline inherited
Get the beginning breadth-first iterator.
Returns
beginning breadth-first iterator.
Referenced by evio::BaseStructure::getDepth(), and evio::BaseStructure::getLeafCount().
begin()
iterator evio::BaseStructure::begin () inline inherited
Get the beginning depth-first iterator.
Returns
beginning depth-first iterator.
bend()
breadth_iterator evio::BaseStructure::bend () inline inherited
Get the end breadth-first iterator.
Returns
end breadth-first iterator.
Referenced by evio::BaseStructure::getDepth(), and evio::BaseStructure::getLeafCount().
childrenBegin()
std::vector< std::shared_ptr< BaseStructure > >::iterator evio::BaseStructure::childrenBegin () inherited
Creates and returns a forward-order begin iterator of this node's children.
Modifying this node's child array invalidates any child iterators created before the modification. Originally part of java's DefaultMutableTreeNode.
Returns
a begin iterator of this node's children.
References evio::BaseStructure::children.
childrenEnd()
std::vector< std::shared_ptr< BaseStructure > >::iterator evio::BaseStructure::childrenEnd () inherited
Creates and returns a forward-order end iterator of this node's children.
Modifying this node's child array invalidates any child iterators created before the modification. Originally part of java's DefaultMutableTreeNode.
Returns
an end iterator of this node's children.
References evio::BaseStructure::children.
dataLength()
uint32_t evio::BaseStructure::dataLength () protected inherited
Compute the dataLength in 32-bit words.
This is the amount of data needed by a leaf of primitives. For non-leafs (structures of structures) this returns 0. For data types smaller than an int, e.g. a short, it computes assuming padding to an integer number of ints. For example, if we are writing a byte array of length 3 or 4, the it would return 1. If the byte array is 5,6,7 or 8 it would return 2;
Returns
the amount of 32-bit words (ints) needed by a leaf of primitives, else 0.
References evio::DataType::CHAR8, evio::DataType::CHARSTAR8, evio::DataType::COMPOSITE, evio::DataType::getBytes(), evio::BaseStructure::getNumberDataItems(), evio::BaseStructure::header, evio::BaseStructure::isLeaf(), evio::BaseStructure::rawBytes, evio::DataType::UCHAR8, and evio::DataType::UNKNOWN32.
Referenced by evio::BaseStructure::setAllHeaderLengths().
end()
iterator evio::BaseStructure::end () inline inherited
Get the end depth-first iterator.
Returns
end depth-first iterator.
Referenced by evio::BaseStructure::getIndex(), and evio::BaseStructure::remove().
getAllowsChildren()
bool evio::BaseStructure::getAllowsChildren () const inherited
Returns true if this node is allowed to have children.
Originally part of java's DefaultMutableTreeNode.
Returns
true if this node allows children, else false.
References evio::BaseStructure::allowsChildren.
getByteOrder()
ByteOrder evio::BaseStructure::getByteOrder () inherited
What is the byte order of this data?
Returns
ByteOrder#ENDIAN_BIG or ByteOrder#ENDIAN_LITTLE.
References evio::BaseStructure::byteOrder.
Referenced by evio::BaseStructure::writeQuick().
getCharData()
std::vector< signed char > & evio::BaseStructure::getCharData () inherited
Gets the raw data as an signed char vector, if the contents type as indicated by the header is appropriate.
If the returned vector's data is modified, then updateCharData MUST be called!
Returns
the data as an signed char vector, or null if this makes no sense for the given contents type.
References evio::DataType::CHAR8, evio::BaseStructure::charData, evio::BaseStructure::header, and evio::BaseStructure::rawBytes.
getChildAfter()
std::shared_ptr< BaseStructure > evio::BaseStructure::getChildAfter (const std::shared_ptr< BaseStructure > aChild) inherited
Returns the child in this node's child vector that immediately follows aChild, which must be a child of this node.
If aChild is the last child, returns null. This method performs a linear search of this node's children for aChild and is O(n) where n is the number of children; to traverse the entire vector of children, use an iterator instead. Originally part of java's DefaultMutableTreeNode.
See also
children
Parameters
aChild child of this node which immediately precedes the returned child structure.
Exceptions
EvioException if aChild is null or is not a child of this node.
Returns
the child of this node that immediately follows aChild.
References evio::BaseStructure::getChildAt(), evio::BaseStructure::getChildCount(), and evio::BaseStructure::getIndex().
getChildAt()
std::shared_ptr< BaseStructure > evio::BaseStructure::getChildAt (size_t index) const inherited
Returns the child at the specified index in this node's child vector.
Originally part of java's DefaultMutableTreeNode.
Parameters
index an index into this node's child array.
Exceptions
std::out_of_range if index is out of bounds.
Returns
the BaseStructure in this node's child array at the specified index.
References evio::BaseStructure::children.
Referenced by evio::BaseStructure::getChildAfter(), evio::BaseStructure::getChildBefore(), evio::BaseStructure::getFirstChild(), evio::BaseStructure::getLastChild(), evio::BaseStructure::getNextNode(), and evio::BaseStructure::remove().
getChildBefore()
std::shared_ptr< BaseStructure > evio::BaseStructure::getChildBefore (const std::shared_ptr< BaseStructure > aChild) inherited
Returns the child in this node's child vector that immediately precedes aChild, which must be a child of this node.
If aChild is the first child, returns null. This method performs a linear search of this node's children for aChild and is O(n) where n is the number of children. Originally part of java's DefaultMutableTreeNode.
Parameters
aChild child of this node which comes immediately after the returned child structure.
Exceptions
EvioException if aChild is null or is not a child of this node.
Returns
the child of this node that immediately precedes aChild.
References evio::BaseStructure::getChildAt(), and evio::BaseStructure::getIndex().
getChildCount()
size_t evio::BaseStructure::getChildCount () const inherited
Returns the number of children of this node.
Originally part of java's DefaultMutableTreeNode.
Returns
the number of children of this node.
References evio::BaseStructure::children.
Referenced by evio::BaseStructure::add(), evio::BaseStructure::getChildAfter(), evio::BaseStructure::getFirstChild(), evio::BaseStructure::getLastChild(), evio::BaseStructure::getNextNode(), evio::BaseStructure::isLeaf(), evio::BaseStructure::isNodeChild(), evio::BaseStructure::removeAllChildren(), and evio::BaseStructure::treeToString().
getChildren()
std::vector< std::shared_ptr< BaseStructure > > evio::BaseStructure::getChildren () const inherited
Get the children of this structure.
Returns
the children of this structure.
References evio::BaseStructure::children.
getCompositeData()
std::vector< std::shared_ptr< CompositeData > > & evio::BaseStructure::getCompositeData () inherited
Gets the composite data as an vector of CompositeData objects, if the content type as indicated by the header is appropriate.
Returns
the data as a vector of CompositeData objects, or null if this makes no sense for the given content type.
Exceptions
EvioException if the data is internally inconsistent.
References evio::BaseStructure::byteOrder, evio::DataType::COMPOSITE, evio::BaseStructure::compositeData, evio::BaseStructure::header, evio::CompositeData::parse(), and evio::BaseStructure::rawBytes.
getDepth()
uint32_t evio::BaseStructure::getDepth () inherited
Returns the depth of the tree rooted at this node – the longest distance from this node to a leaf.
If this node has no children, returns 0. This operation is much more expensive than getLevel() because it must effectively traverse the entire tree rooted at this node. Originally part of java's DefaultMutableTreeNode.
See also
getLevel
Exceptions
EvioException if internal logic error.
Returns
the depth of the tree whose root is this node.
References evio::BaseStructure::bbegin(), evio::BaseStructure::bend(), and evio::BaseStructure::getLevel().
getDoubleData()
std::vector< double > & evio::BaseStructure::getDoubleData () inherited
Gets the raw data as a double vector if the content type as indicated by the header is appropriate.
If the returned vector's data is modified, then updateDoubleData MUST be called!
Returns
a reference to the data as a double vector.
Exceptions
EvioException if contained data type is not double.
References evio::DataType::DOUBLE64, evio::BaseStructure::doubleData, evio::BaseStructure::header, evio::BaseStructure::needSwap(), evio::BaseStructure::rawBytes, and SWAP_64.
getFirstChild()
std::shared_ptr< BaseStructure > evio::BaseStructure::getFirstChild () const inherited
Returns this node's first child.
If this node has no children, throws EvioException. Originally part of java's DefaultMutableTreeNode.
Returns
the first child of this node
Exceptions
EvioException if this node has no children.
References evio::BaseStructure::getChildAt(), and evio::BaseStructure::getChildCount().
getFirstLeaf()
std::shared_ptr< BaseStructure > evio::BaseStructure::getFirstLeaf () inherited
Finds and returns the first leaf that is a descendant of this node – either this node or its first child's first leaf.
Returns this node if it is a leaf. Originally part of java's DefaultMutableTreeNode.
See also
isLeaf
isNodeDescendant
Returns
the first leaf in the subtree rooted at this node.
References evio::BaseStructure::getThis().
getFloatData()
std::vector< float > & evio::BaseStructure::getFloatData () inherited
Gets the raw data as a float vector if the content type as indicated by the header is appropriate.
If the returned vector's data is modified, then updateFloatData MUST be called!
Returns
a reference to the data as a float vector.
Exceptions
EvioException if contained data type is not float.
References evio::DataType::FLOAT32, evio::BaseStructure::floatData, evio::BaseStructure::header, evio::BaseStructure::needSwap(), evio::BaseStructure::rawBytes, and SWAP_32.
getHeader()
std::shared_ptr< BaseStructureHeader > evio::BaseStructure::getHeader () const inherited
Return the header for this structure.
Returns
the header for this structure.
References evio::BaseStructure::header.
getIndex()
ssize_t evio::BaseStructure::getIndex (const std::shared_ptr< BaseStructure > aChild) inherited
Returns the index of the specified child in this node's child vector.
If the specified node is not a child of this node, returns -1. This method performs a linear search and is O(n) where n is the number of children. Originally part of java's DefaultMutableTreeNode.
Parameters
aChild the BaseStructure to search for among this node's children.
Exceptions
EvioException if aChild is null.
Returns
an int giving the index of the node in this node's child array, or -1 if the specified node is a not a child of this node.
References evio::BaseStructure::children, evio::BaseStructure::end(), and evio::BaseStructure::isNodeChild().
Referenced by evio::BaseStructure::getChildAfter(), evio::BaseStructure::getChildBefore(), and evio::BaseStructure::remove().
getInstance() [1/2]
static std::shared_ptr<EvioTagSegment> evio::EvioTagSegment::getInstance (std::shared_ptr< TagSegmentHeader > const & head) inline static
Method to return a shared pointer to a constructed object of this class.
Parameters
head tagsegment header.
Returns
shared pointer to new EvioTagSegment.
Referenced by evio::EventBuilder::main(), and evio::StructureTransformer::transform().
getInstance() [2/2]
static std::shared_ptr<EvioTagSegment> evio::EvioTagSegment::getInstance (uint16_t tag, DataType const & typ) inline static
Method to return a shared pointer to a constructed object of this class.
Parameters
tag tagsegment tag.
typ tagsegment data type.
Returns
shared pointer to new EvioTagSegment.
getIntData()
std::vector< int32_t > & evio::BaseStructure::getIntData () inherited
Gets the raw data as an int32_t vector if the content type as indicated by the header is appropriate.
If the returned vector's data is modified, then updateIntData MUST be called!
Returns
a reference to the data as an int32_t vector.
Exceptions
EvioException if contained data type is not int32_t.
References evio::BaseStructure::header, evio::DataType::INT32, evio::BaseStructure::intData, evio::BaseStructure::needSwap(), evio::BaseStructure::rawBytes, and SWAP_32.
getLastChild()
std::shared_ptr< BaseStructure > evio::BaseStructure::getLastChild () const inherited
Returns this node's last child.
If this node has no children, throws EvioException. Originally part of java's DefaultMutableTreeNode.
Returns
the last child of this node.
Exceptions
EvioException if this node has no children.
References evio::BaseStructure::getChildAt(), and evio::BaseStructure::getChildCount().
getLastLeaf()
std::shared_ptr< BaseStructure > evio::BaseStructure::getLastLeaf () inherited
Finds and returns the last leaf that is a descendant of this node – either this node or its last child's last leaf.
Returns this node if it is a leaf. Originally part of java's DefaultMutableTreeNode.
See also
isLeaf
isNodeDescendant
Returns
the last leaf in the subtree rooted at this node.
References evio::BaseStructure::getThis().
getLeafCount()
ssize_t evio::BaseStructure::getLeafCount () inherited
Returns the total number of leaves that are descendants of this node.
If this node is a leaf, returns 1. This method is O(n) where n is the number of descendants of this node. Originally part of java's DefaultMutableTreeNode.
See also
isNodeAncestor
Exceptions
EvioException if tree has zero leaves.
Returns
the number of leaves beneath this node.
References evio::BaseStructure::bbegin(), and evio::BaseStructure::bend().
getLengthsUpToDate()
bool evio::BaseStructure::getLengthsUpToDate () const protected inherited
Get whether the lengths of all header fields for this structure and all it descendants are up to date or not.
Returns
whether the lengths of all header fields for this structure and all it descendants are up to date or not.
References evio::BaseStructure::lengthsUpToDate.
getLevel()
uint32_t evio::BaseStructure::getLevel () const inherited
Returns the number of levels above this node – the distance from the root to this node.
If this node is the root, returns 0. Originally part of java's DefaultMutableTreeNode.
See also
getDepth
Returns
the number of levels above this node.
References evio::BaseStructure::getThisConst().
Referenced by evio::BaseStructure::getDepth(), and evio::BaseStructure::getSharedAncestor().
getLongData()
std::vector< int64_t > & evio::BaseStructure::getLongData () inherited
Gets the raw data as an int64_t vector if the content type as indicated by the header is appropriate.
If the returned vector's data is modified, then updateLongData MUST be called!
Returns
a reference to the data as an int64_t vector.
Exceptions
EvioException if contained data type is not int64_t.
References evio::BaseStructure::header, evio::DataType::LONG64, evio::BaseStructure::longData, evio::BaseStructure::needSwap(), evio::BaseStructure::rawBytes, and SWAP_64.
getMatchingStructures()
void evio::BaseStructure::getMatchingStructures (std::shared_ptr< IEvioFilter > filter, std::vector< std::shared_ptr< BaseStructure >> & vec) inherited
Visit all the descendant structures, and collect those that pass a filter.
Parameters
filter the filter that must be passed. If null, this will return all the structures.
vec vector provided to contain all structures that are accepted by the filter.
References evio::BaseStructure::visitAllStructures().
getNextLeaf()
std::shared_ptr< BaseStructure > evio::BaseStructure::getNextLeaf () inherited
Returns the leaf after this node or null if this node is the last leaf in the tree.
This operation is very inefficient. In order to determine the next node, this method first performs a linear search in the parent's child-list in order to find the current node.
This implementation makes the operation suitable for short traversals from a known position. But to traverse all of the leaves in the tree, you should use A depth-first iterator of the nodes in the tree and use isLeaf on each node to determine which are leaves. Originally part of java's DefaultMutableTreeNode.
See also
nodeIterator
isLeaf
Returns
returns the next leaf past this node.
References evio::BaseStructure::getNextSibling(), and evio::BaseStructure::getParent().
getNextNode()
std::shared_ptr< BaseStructure > evio::BaseStructure::getNextNode () inherited
Returns the node that follows this node in a preorder traversal of this node's tree (return left nodes all the way down before coming back and doing siblings from bottom up).
Returns null if this node is the last node of the traversal. This is an inefficient way to traverse the entire tree; use an iterator instead. Originally part of java's DefaultMutableTreeNode.
Returns
the node that follows this node in a preorder traversal, or null if this node is last.
References evio::BaseStructure::getChildAt(), evio::BaseStructure::getChildCount(), evio::BaseStructure::getNextSibling(), and evio::BaseStructure::getParent().
getNextSibling()
std::shared_ptr< BaseStructure > evio::BaseStructure::getNextSibling () inherited
Returns the next sibling of this node in the parent's children vector.
Returns null if this node has no parent or is the parent's last child. This method performs a linear search that is O(n) where n is the number of children; to traverse the entire array, use the parent's child iterator instead. Originally part of java's DefaultMutableTreeNode.
See also
children.
Exceptions
EvioException if child of parent is not a sibling.
Returns
the sibling of this node that immediately follows this node.
References evio::BaseStructure::getParent(), evio::BaseStructure::getThis(), and evio::BaseStructure::isNodeSibling().
Referenced by evio::BaseStructure::getNextLeaf(), and evio::BaseStructure::getNextNode().
getNumberDataItems()
uint32_t evio::BaseStructure::getNumberDataItems () inherited
Get the number of stored data items like number of banks, ints, floats, etc.
(not the size in ints or bytes). Some items may be padded such as shorts and bytes. This will tell the meaningful number of such data items. In the case of containers, returns number of 32-bit words not in header.
Returns
number of stored data items (not size or length), or number of words if container.
References evio::DataType::CHARSTAR8, evio::DataType::COMPOSITE, evio::BaseStructure::compositeData, evio::DataType::getBytes(), evio::BaseStructure::getStringData(), evio::BaseStructure::header, evio::BaseStructure::isContainer(), evio::BaseStructure::numberDataItems, and evio::BaseStructure::rawBytes.
Referenced by evio::BaseStructure::dataLength().
getParent()
std::shared_ptr< BaseStructure > evio::BaseStructure::getParent () const inherited
Returns this node's parent or null if this node has no parent.
Originally part of java's DefaultMutableTreeNode.
Returns
this node's parent BaseStructure, or null if this node has no parent.
References evio::BaseStructure::parent.
Referenced by evio::BaseStructure::getNextLeaf(), evio::BaseStructure::getNextNode(), evio::BaseStructure::getNextSibling(), evio::BaseStructure::getPreviousLeaf(), evio::BaseStructure::getPreviousNode(), evio::BaseStructure::getPreviousSibling(), evio::BaseStructure::getSiblingCount(), evio::BaseStructure::isNodeSibling(), evio::BaseStructure::isRoot(), and evio::BaseStructure::removeFromParent().
getPath()
std::vector< std::shared_ptr< BaseStructure > > evio::BaseStructure::getPath () inherited
Returns the path from the root, to get to this node.
The last element in the path is this node. Originally part of java's DefaultMutableTreeNode.
Returns
an vector of BaseStructure shared pointer giving the path, where the first element in the path is the root and the last element is this node.
References evio::BaseStructure::getPathToRoot(), and evio::BaseStructure::getThis().
getPathToRoot()
std::vector< std::shared_ptr< BaseStructure > > evio::BaseStructure::getPathToRoot (const std::shared_ptr< BaseStructure > & aNode, int depth) const protected inherited
Builds the parents of node up to and including the root node, where the original node is the last element in the returned vector.
The length of the returned array gives the node's depth in the tree. Originally part of java's DefaultMutableTreeNode.
Parameters
aNode the BaseStructure to get the path for.
depth an int giving the number of steps already taken towards the root (on recursive calls), used to size the returned vector.
Returns
a vector of BaseStructure shared pointer giving the path from the root to the specified node.
Referenced by evio::BaseStructure::getPath().
getPreviousLeaf()
std::shared_ptr< BaseStructure > evio::BaseStructure::getPreviousLeaf () inherited
Returns the leaf before this node or null if this node is the first leaf in the tree.
This operation is very inefficient. In order to determine the previous node, this method first performs a linear search in the parent's child-list in order to find the current node.
This implementation makes the operation suitable for short traversals from a known position. But to traverse all of the leaves in the tree, you should use A depth-first iterator of the nodes in the tree and use isLeaf on each node to determine which are leaves. Originally part of java's DefaultMutableTreeNode.
See also
nodeIterator
isLeaf
Returns
returns the leaf before this node.
References evio::BaseStructure::getParent(), and evio::BaseStructure::getPreviousSibling().
getPreviousNode()
std::shared_ptr< BaseStructure > evio::BaseStructure::getPreviousNode () inherited
Returns the node that precedes this node in a preorder traversal of this node's tree (return left nodes all the way down before coming back and doing siblings from bottom up).
Returns null if this node is the first node of the traversal – the root of the tree. This is an inefficient way to traverse the entire tree; use an iterator instead. Originally part of java's DefaultMutableTreeNode.
Returns
the node that precedes this node in a preorder traversal, or null if this node is the first.
References evio::BaseStructure::getParent(), and evio::BaseStructure::getPreviousSibling().
getPreviousSibling()
std::shared_ptr< BaseStructure > evio::BaseStructure::getPreviousSibling () inherited
Returns the previous sibling of this node in the parent's children vector.
Returns null if this node has no parent or is the parent's first child. This method performs a linear search that is O(n) where n is the number of children. Originally part of java's DefaultMutableTreeNode.
Exceptions
EvioException if child of parent is not a sibling.
Returns
the sibling of this node that immediately precedes this node.
References evio::BaseStructure::getParent(), evio::BaseStructure::getThis(), and evio::BaseStructure::isNodeSibling().
Referenced by evio::BaseStructure::getPreviousLeaf(), and evio::BaseStructure::getPreviousNode().
getRawBytes()
std::vector< uint8_t > & evio::BaseStructure::getRawBytes () inherited
Get the raw data of the structure.
Returns
the raw data of the structure.
References evio::BaseStructure::rawBytes.
getRoot()
std::shared_ptr< BaseStructure > evio::BaseStructure::getRoot () inherited
Returns the root of the tree that contains this node.
The root is the ancestor with a null parent. Originally part of java's DefaultMutableTreeNode.
See also
isNodeAncestor
Returns
the root of the tree that contains this node.
References evio::BaseStructure::getThis().
Referenced by evio::BaseStructure::isNodeRelated().
getSharedAncestor()
std::shared_ptr< BaseStructure > evio::BaseStructure::getSharedAncestor (std::shared_ptr< BaseStructure > aNode) inherited
Returns the nearest common ancestor to this node and aNode.
Returns null if no such ancestor exists – if this node and aNode are in different trees or if aNode is null. A node is considered an ancestor of itself. Originally part of java's DefaultMutableTreeNode.
See also
isNodeAncestor
isNodeDescendant
Parameters
aNode node to find common ancestor with.
Exceptions
EvioException if internal logic error.
Returns
nearest ancestor common to this node and aNode, or null if none.
References evio::BaseStructure::getLevel(), and evio::BaseStructure::getThis().
getShortData()
std::vector< int16_t > & evio::BaseStructure::getShortData () inherited
Gets the raw data as an int16_t vector if the content type as indicated by the header is appropriate.
If the returned vector's data is modified, then updateShortData MUST be called!
Returns
a reference to the data as an int16_t vector.
Exceptions
EvioException if contained data type is not int16_t.
References evio::BaseStructure::header, evio::BaseStructure::needSwap(), evio::BaseStructure::rawBytes, evio::DataType::SHORT16, evio::BaseStructure::shortData, and SWAP_16.
getSiblingCount()
size_t evio::BaseStructure::getSiblingCount () const inherited
Returns the number of siblings of this node.
A node is its own sibling (if it has no parent or no siblings, this method returns 1). Originally part of java's DefaultMutableTreeNode.
Returns
the number of siblings of this node.
References evio::BaseStructure::getParent().
getStringData()
std::vector< std::string > & evio::BaseStructure::getStringData () inherited
Gets the raw data (ascii) as an vector of string objects, if the contents type as indicated by the header is appropriate.
For any other behavior, the user should retrieve the data as a bytes and manipulate it in the exact manner desired. If there are non ascii or non-printing ascii chars or the bytes or not in evio format, a single string containing everything is returned.
Originally, in evio versions 1, 2 and 3, only one string was stored. Subsequent changes allowed a vector of strings to be stored and retrieved. The changes are backwards compatible.
The following is true about the string raw data format:
Each string IS immediately followed by an ending null (0).
All string data are further padded/ended with at least one 0x4 valued ASCII char (up to 4 possible).
The presence of 1 to 4 ending 4's distinguishes the recent string array version from the original, single string version.
The original version string may be padded with anything after its ending null.
Returns
the data as a vector of string objects if DataType is CHARSTAR8, or null if this makes no sense for the given type.
References evio::DataType::CHARSTAR8, evio::BaseStructure::header, evio::BaseStructure::rawBytes, evio::BaseStructure::stringList, and evio::BaseStructure::unpackRawBytesToStrings().
Referenced by evio::BaseStructure::getNumberDataItems().
getStructureType()
StructureType evio::EvioTagSegment::getStructureType () const inline override virtual
This implements the virtual method from BaseStructure.
This returns the type of this structure, not the type of data this structure holds.
Returns
the StructureType of this structure, which is a StructureType::STRUCT_TAGSEGMENT.
See also
StructureType
Reimplemented from evio::BaseStructure.
References evio::StructureType::STRUCT_TAGSEGMENT.
getThis()
std::shared_ptr<BaseStructure> evio::BaseStructure::getThis () inline inherited
Referenced by evio::BaseStructure::add(), evio::BaseStructure::getFirstLeaf(), evio::BaseStructure::getLastLeaf(), evio::BaseStructure::getNextSibling(), evio::BaseStructure::getPath(), evio::BaseStructure::getPreviousSibling(), evio::BaseStructure::getRoot(), evio::BaseStructure::getSharedAncestor(), evio::BaseStructure::insert(), evio::BaseStructure::isNodeDescendant(), evio::BaseStructure::removeFromParent(), and evio::BaseStructure::visitAllStructures().
getThisConst()
std::shared_ptr<const BaseStructure> evio::BaseStructure::getThisConst () const inline inherited
Referenced by evio::BaseStructure::getLevel(), evio::BaseStructure::isNodeAncestor(), evio::BaseStructure::isNodeChild(), and evio::BaseStructure::isNodeSibling().
getTotalBytes()
uint32_t evio::BaseStructure::getTotalBytes () const inherited
Get the length of this structure in bytes, including the header.
Returns
the length of this structure in bytes, including the header.
References evio::BaseStructure::header.
Referenced by evio::BaseStructure::write().
getUCharData()
std::vector< unsigned char > & evio::BaseStructure::getUCharData () inherited
Gets the raw data as an unsigned char vector, if the contents type as indicated by the header is appropriate.
If the returned vector's data is modified, then updateCharData MUST be called!
Returns
the data as an unsigned char vector, or null if this makes no sense for the given contents type.
References evio::BaseStructure::header, evio::BaseStructure::rawBytes, evio::DataType::UCHAR8, and evio::BaseStructure::ucharData.
getUIntData()
std::vector< uint32_t > & evio::BaseStructure::getUIntData () inherited
Gets the raw data as an uint32_t vector if the content type as indicated by the header is appropriate.
If the returned vector's data is modified, then updateUIntData MUST be called!
Returns
a reference to the data as an uint32_t vector.
Exceptions
EvioException if contained data type is not uint32_t.
References evio::BaseStructure::header, evio::BaseStructure::needSwap(), evio::BaseStructure::rawBytes, SWAP_32, evio::DataType::UINT32, and evio::BaseStructure::uintData.
getULongData()
std::vector< uint64_t > & evio::BaseStructure::getULongData () inherited
Gets the raw data as an uint64_t vector if the content type as indicated by the header is appropriate.
If the returned vector's data is modified, then updateULongData MUST be called!
Returns
a reference to the data as an uint64_t vector.
Exceptions
EvioException if contained data type is not uint64_t.
References evio::BaseStructure::header, evio::BaseStructure::needSwap(), evio::BaseStructure::rawBytes, SWAP_64, evio::DataType::ULONG64, and evio::BaseStructure::ulongData.
getUShortData()
std::vector< uint16_t > & evio::BaseStructure::getUShortData () inherited
Gets the raw data as an uint16_t vector if the content type as indicated by the header is appropriate.
If the returned vector's data is modified, then updateUShortData MUST be called!
Returns
a reference to the data as an uint16_t vector.
Exceptions
EvioException if contained data type is not uint16_t.
References evio::BaseStructure::header, evio::BaseStructure::needSwap(), evio::BaseStructure::rawBytes, SWAP_16, evio::DataType::USHORT16, and evio::BaseStructure::ushortData.
insert()
void evio::BaseStructure::insert (const std::shared_ptr< BaseStructure > newChild, size_t childIndex) inherited
Removes newChild from its present parent (if it has a parent), sets the child's parent to this node, and then adds the child to this node's child array at index childIndex.
newChild must not be null and must not be an ancestor of this node. Originally part of java's DefaultMutableBaseStructure.
Parameters
newChild the BaseStructure to insert under this node.
childIndex the index in this node's child array. where this node is to be inserted.
Exceptions
std::out_of_range if childIndex is out of bounds.
EvioException if newChild is null, is an ancestor of this node, or this node does not allow children.
See also
isNodeDescendant
References evio::BaseStructure::allowsChildren, evio::BaseStructure::children, evio::BaseStructure::getThis(), evio::BaseStructure::isNodeAncestor(), and evio::BaseStructure::setLengthsUpToDate().
Referenced by evio::BaseStructure::add().
isContainer()
bool evio::BaseStructure::isContainer () const inherited
Checks whether this structure is a container, i.e.
a structure of structures.
Returns
true if this structure is a container. This is the same check as getAllowsChildren.
References evio::BaseStructure::header.
Referenced by evio::BaseStructure::getNumberDataItems().
isLeaf()
bool evio::BaseStructure::isLeaf () const inherited
Returns true if this node has no children.
To distinguish between nodes that have no children and nodes that cannot have children (e.g. to distinguish files from empty directories), use this method in conjunction with getAllowsChildren. Originally part of java's DefaultMutableBaseStructure.
See also
getAllowsChildren
Returns
true if this node has no children.
References evio::BaseStructure::getChildCount().
Referenced by evio::BaseStructure::dataLength(), evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::treeToString(), and evio::BaseStructure::write().
isNodeAncestor()
bool evio::BaseStructure::isNodeAncestor (const std::shared_ptr< BaseStructure > anotherNode) const inherited
Returns true if anotherNode is an ancestor of this node – if it is this node, this node's parent, or an ancestor of this node's parent.
(Note that a node is considered an ancestor of itself.) If anotherNode is null, this method returns false. This operation is at worst O(h) where h is the distance from the root to this node. Originally part of java's DefaultMutableTreeNode.
See also
isNodeDescendant
getSharedAncestor
Parameters
anotherNode node to test as an ancestor of this node
Returns
true if this node is a descendant of anotherNode
References evio::BaseStructure::getThisConst().
Referenced by evio::BaseStructure::insert().
isNodeChild()
bool evio::BaseStructure::isNodeChild (const std::shared_ptr< BaseStructure > aNode) const inherited
Returns true if aNode is a child of this node.
If aNode is null, this method returns false. Originally part of java's DefaultMutableTreeNode.
Parameters
aNode structure to test if it's a child of this one.
Returns
true if aNode is a child of this node; false if aNode is null.
References evio::BaseStructure::getChildCount(), and evio::BaseStructure::getThisConst().
Referenced by evio::BaseStructure::getIndex(), and evio::BaseStructure::remove().
isNodeDescendant()
bool evio::BaseStructure::isNodeDescendant (std::shared_ptr< BaseStructure > anotherNode) inherited
Returns true if anotherNode is a descendant of this node – if it is this node, one of this node's children, or a descendant of one of this node's children.
Note that a node is considered a descendant of itself. If anotherNode is null, returns false. This operation is at worst O(h) where h is the distance from the root to anotherNode. Originally part of java's DefaultMutableTreeNode.
See also
isNodeAncestor
getSharedAncestor
Parameters
anotherNode node to test as descendant of this node
Returns
true if this node is an ancestor of anotherNode
References evio::BaseStructure::getThis().
isNodeRelated()
bool evio::BaseStructure::isNodeRelated (std::shared_ptr< BaseStructure > aNode) inherited
Returns true if and only if aNode is in the same tree as this node.
Returns false if aNode is null. Originally part of java's DefaultMutableTreeNode.
See also
getSharedAncestor
getRoot
Parameters
aNode structure to test if it's in the same tree as this one.
Returns
true if aNode is in the same tree as this node; false if aNode is null
References evio::BaseStructure::getRoot().
isNodeSibling()
bool evio::BaseStructure::isNodeSibling (const std::shared_ptr< BaseStructure > anotherNode) const inherited
Returns true if anotherNode is a sibling of (has the same parent as) this node.
A node is its own sibling. If anotherNode is null, returns false. Originally part of java's DefaultMutableTreeNode.
Parameters
anotherNode node to test as sibling of this node.
Exceptions
EvioException if sibling has different parent.
Returns
true if anotherNode is a sibling of this node.
References evio::BaseStructure::getParent(), and evio::BaseStructure::getThisConst().
Referenced by evio::BaseStructure::getNextSibling(), and evio::BaseStructure::getPreviousSibling().
isRoot()
bool evio::BaseStructure::isRoot () const inherited
Returns true if this node is the root of the tree.
The root is the only node in the tree with a null parent; every tree has exactly one root. Originally part of java's DefaultMutableTreeNode.
Returns
true if this node is the root of its tree.
References evio::BaseStructure::getParent().
needSwap()
bool evio::BaseStructure::needSwap () const inherited
Is a byte swap required (i.e.
is the data endian opposite of local endian)?
Returns
true if byte swapping is required.
References evio::BaseStructure::byteOrder, and evio::ByteOrder::ENDIAN_LOCAL.
Referenced by evio::BaseStructure::getDoubleData(), evio::BaseStructure::getFloatData(), evio::BaseStructure::getIntData(), evio::BaseStructure::getLongData(), evio::BaseStructure::getShortData(), evio::BaseStructure::getUIntData(), evio::BaseStructure::getULongData(), and evio::BaseStructure::getUShortData().
remove() [1/2]
void evio::BaseStructure::remove (const std::shared_ptr< BaseStructure > aChild) inherited
Removes aChild from this node's child vector, giving it a null parent.
Originally part of java's DefaultMutableTreeNode.
Parameters
aChild a child of this node to remove
Exceptions
EvioException if aChild is not a child of this node
References evio::BaseStructure::getIndex(), evio::BaseStructure::isNodeChild(), and evio::BaseStructure::remove().
remove() [2/2]
void evio::BaseStructure::remove (size_t childIndex) inherited
Removes the child at the specified index from this node's children and sets that node's parent to null.
The child node to remove must be a BaseStructure. Originally part of java's DefaultMutableTreeNode.
Parameters
childIndex the index of the child to remove
Exceptions
std::out_of_range if childIndex is out of bounds
References evio::BaseStructure::children, evio::BaseStructure::end(), evio::BaseStructure::getChildAt(), and evio::BaseStructure::setLengthsUpToDate().
Referenced by evio::BaseStructure::remove(), and evio::BaseStructure::removeAllChildren().
removeAllChildren()
void evio::BaseStructure::removeAllChildren () inherited
Removes all of this node's children, setting their parents to null.
If this node has no children, this method does nothing. Originally part of java's DefaultMutableTreeNode.
References evio::BaseStructure::getChildCount(), and evio::BaseStructure::remove().
Referenced by evio::BaseStructure::setAllowsChildren().
removeFromParent()
void evio::BaseStructure::removeFromParent () inherited
Removes the subtree rooted at this node from the tree, giving this node a null parent.
Does nothing if this node is the root of its tree. Originally part of java's DefaultMutableTreeNode.
References evio::BaseStructure::getParent(), and evio::BaseStructure::getThis().
setAllHeaderLengths()
uint32_t evio::BaseStructure::setAllHeaderLengths () inherited
Compute and set length of all header fields for this structure and all its descendants.
For writing events, this will be crucial for setting the values in the headers.
Returns
the length that would go in the header field (for a leaf).
Exceptions
EvioException if the length is too large.
References evio::BaseStructure::children, evio::BaseStructure::dataLength(), evio::BaseStructure::header, evio::BaseStructure::isLeaf(), evio::BaseStructure::lengthsUpToDate, and evio::BaseStructure::setLengthsUpToDate().
Referenced by evio::BaseStructure::updateCharData(), evio::BaseStructure::updateCompositeData(), evio::BaseStructure::updateDoubleData(), evio::BaseStructure::updateFloatData(), evio::BaseStructure::updateIntData(), evio::BaseStructure::updateLongData(), evio::BaseStructure::updateShortData(), evio::BaseStructure::updateStringData(), evio::BaseStructure::updateUCharData(), evio::BaseStructure::updateUIntData(), evio::BaseStructure::updateULongData(), and evio::BaseStructure::updateUShortData().
setAllowsChildren()
void evio::BaseStructure::setAllowsChildren (bool allows) inherited
Determines whether or not this node is allowed to have children.
If allows is false, all of this node's children are removed. Originally part of java's DefaultMutableTreeNode.
Note: By default, a node allows children.
Parameters
allows true if this node is allowed to have children.
References evio::BaseStructure::allowsChildren, and evio::BaseStructure::removeAllChildren().
setByteOrder()
void evio::BaseStructure::setByteOrder (ByteOrder const & order) inherited
Set the byte order of this data.
This method cannot be used to swap data. It is only used to describe the endianness of the rawdata contained.
Parameters
order ByteOrder#ENDIAN_BIG or ByteOrder#ENDIAN_LITTLE.
References evio::BaseStructure::byteOrder.
setLengthsUpToDate()
void evio::BaseStructure::setLengthsUpToDate (bool lenUpToDate) protected inherited
Set whether the lengths of all header fields for this structure and all it descendants are up to date or not.
Parameters
lenUpToDate are the lengths of all header fields for this structure and all it descendants up to date or not.
References evio::BaseStructure::lengthsUpToDate, and evio::BaseStructure::parent.
Referenced by evio::BaseStructure::insert(), evio::BaseStructure::remove(), evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::updateCharData(), evio::BaseStructure::updateCompositeData(), evio::BaseStructure::updateDoubleData(), evio::BaseStructure::updateFloatData(), evio::BaseStructure::updateIntData(), evio::BaseStructure::updateLongData(), evio::BaseStructure::updateShortData(), evio::BaseStructure::updateStringData(), evio::BaseStructure::updateUCharData(), evio::BaseStructure::updateUIntData(), evio::BaseStructure::updateULongData(), and evio::BaseStructure::updateUShortData().
setParent()
void evio::BaseStructure::setParent (const std::shared_ptr< BaseStructure > & newParent) protected inherited
Sets this node's parent to newParent but does not change the parent's child array.
This method is called from insert and remove to reassign a child's parent, it should not be messaged from anywhere else. Originally part of java's DefaultMutableBaseStructure.
Parameters
newParent this node's new parent.
References evio::BaseStructure::parent.
setRawBytes() [1/2]
void evio::BaseStructure::setRawBytes (std::vector< uint8_t > & bytes) protected inherited
Set the data for the structure.
Parameters
bytes vector of data to be copied.
References evio::BaseStructure::rawBytes.
setRawBytes() [2/2]
void evio::BaseStructure::setRawBytes (uint8_t * bytes, uint32_t len) protected inherited
Set the data for the structure.
Parameters
bytes pointer to the data to be copied.
len number of bytes to be copied.
References evio::BaseStructure::rawBytes.
stringsToRawBytes() [1/2]
void evio::BaseStructure::stringsToRawBytes () protected inherited
This method transforms the internal vector of strings into internal rawBytes vector of evio format data not including header.
References evio::BaseStructure::header, evio::BaseStructure::numberDataItems, evio::BaseStructure::rawBytes, evio::BaseStructure::stringList, and evio::Util::stringsToRawSize().
Referenced by evio::BaseStructure::updateStringData().
stringsToRawBytes() [2/2]
void evio::BaseStructure::stringsToRawBytes (std::vector< std::string > & strings, std::vector< uint8_t > & bytes) static inherited
This method transforms a vector of strings into raw evio format data, not including header.
Parameters
strings vector of strings to transform.
bytes vector of bytes to contain evio formatted strings.
References evio::BaseStructure::stringsToRawSize().
stringsToRawSize()
uint32_t evio::BaseStructure::stringsToRawSize (std::vector< std::string > const & strings) static inherited
This method returns the number of bytes in a raw evio format of the given string vector, not including header.
Parameters
strings vector of strings to size.
Returns
the number of bytes in a raw evio format of the given strings.
0 if vector empty.
Referenced by evio::BaseStructure::stringsToRawBytes().
stringToRawSize()
uint32_t evio::BaseStructure::stringToRawSize (const std::string & str) static inherited
This method returns the number of bytes in a raw evio format of the given string vector, not including header.
Parameters
str vector of strings to size.
Returns
the number of bytes in a raw evio format of the given strings.
0 if vector empty.
toString()
std::string evio::BaseStructure::toString () const virtual inherited
Obtain a string representation of the structure.
Returns
a string representation of the structure.
Reimplemented in evio::EvioEvent.
References evio::BaseStructure::children, evio::BaseStructure::getStructureType(), evio::BaseStructure::header, evio::BaseStructure::rawBytes, evio::StructureType::STRUCT_BANK, evio::StructureType::toString(), and evio::DataType::toString().
Referenced by evio::BaseStructure::treeToString().
transform()
void evio::BaseStructure::transform (std::shared_ptr< BaseStructure > const & structure) inherited
This method does a partial copy and is designed to help convert between banks, segments,and tagsegments in the StructureTransformer class (hence the name "transform").
It copies all the data from another BaseStructure object. Children are not copied in the deep clone way, but their references are added to this structure. It does not copy header data or the parent either.
Parameters
structure BaseStructure from which to copy data.
References evio::BaseStructure::children, evio::DataType::getDataType(), evio::DataType::isStructure(), and evio::BaseStructure::lengthsUpToDate.
treeToString()
std::string evio::BaseStructure::treeToString (std::string const & indent) const inherited
Recursive method to obtain a string representation of the entire tree structure rooted at this structure.
Parameters
indent string containing indentation for this structure. Generally called with "".
Returns
a string representation of the entire tree structure rooted at this structure.
References evio::BaseStructure::children, evio::BaseStructure::getChildCount(), evio::BaseStructure::isLeaf(), and evio::BaseStructure::toString().
unpackRawBytesToStrings() [1/5]
uint32_t evio::BaseStructure::unpackRawBytesToStrings () inherited
Extract string data from rawBytes array.
Returns
number of strings extracted from bytes.
References evio::BaseStructure::badStringFormat, evio::BaseStructure::rawBytes, evio::BaseStructure::stringEnd, and evio::BaseStructure::stringList.
Referenced by evio::BaseStructure::getStringData(), and evio::BaseStructure::unpackRawBytesToStrings().
unpackRawBytesToStrings() [2/5]
void evio::BaseStructure::unpackRawBytesToStrings (ByteBuffer & buffer, size_t pos, size_t length, std::vector< std::string > & strData) static inherited
This method extracts a vector of strings from buffer containing raw evio string data.
Parameters
buffer buffer containing evio string data.
pos position of string data in buffer.
length length of string data in buffer in bytes.
strData vector in which to place extracted strings.
References evio::ByteBuffer::array(), and evio::ByteBuffer::arrayOffset().
unpackRawBytesToStrings() [3/5]
void evio::BaseStructure::unpackRawBytesToStrings (std::vector< uint8_t > & bytes, size_t offset, size_t maxLength, std::vector< std::string > & strData) static inherited
This method extracts a vector of strings from bytes of raw evio string data.
Don't go beyond the specified max character limit and stop at the first non-character value.
Parameters
bytes raw evio string data.
offset offset into raw data vector.
maxLength max length in bytes of valid data in bytes vector.
strData vector in which to place extracted strings.
unpackRawBytesToStrings() [4/5]
void evio::BaseStructure::unpackRawBytesToStrings (std::vector< uint8_t > & bytes, size_t offset, std::vector< std::string > & strData) static inherited
This method extracts a vector of strings from bytes of raw evio string data.
Parameters
bytes raw evio string data.
offset offset into raw data array.
strData vector in which to place extracted strings.
References evio::BaseStructure::unpackRawBytesToStrings().
unpackRawBytesToStrings() [5/5]
void evio::BaseStructure::unpackRawBytesToStrings (uint8_t * bytes, size_t length, std::vector< std::string > & strData) static inherited
This method extracts a vector of strings from bytes of raw evio string data.
Don't go beyond the specified max character limit and stop at the first non-character value.
Parameters
bytes raw evio string data.
length length in bytes of valid data at bytes pointer.
strData vector in which to place extracted strings.
updateCharData()
void evio::BaseStructure::updateCharData () inherited
If data in this structure was changed by modifying the vector returned from getCharData(), then this method needs to be called in order to make this object internally consistent.
Exceptions
EvioException if this object corresponds to a different data type.
References evio::DataType::CHAR8, evio::BaseStructure::charData, evio::BaseStructure::header, evio::BaseStructure::numberDataItems, evio::BaseStructure::rawBytes, evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), and evio::DataType::toString().
updateCompositeData()
void evio::BaseStructure::updateCompositeData () inherited
If data in this structure was changed by modifying the vector returned from getCompositeData(), then this method needs to be called in order to make this object internally consistent.
Exceptions
EvioException if this object corresponds to a different data type.
References evio::BaseStructure::byteOrder, evio::DataType::COMPOSITE, evio::BaseStructure::compositeData, evio::CompositeData::generateRawBytes(), evio::BaseStructure::header, evio::BaseStructure::numberDataItems, evio::BaseStructure::rawBytes, evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), and evio::DataType::toString().
updateDoubleData()
void evio::BaseStructure::updateDoubleData () inherited
If data in this structure was changed by modifying the vector returned from getDoubleData(), then this method needs to be called in order to make this object internally consistent.
Exceptions
EvioException if this object corresponds to a different data type.
References evio::BaseStructure::byteOrder, evio::ByteOrder::byteSwap64(), evio::DataType::DOUBLE64, evio::BaseStructure::doubleData, evio::BaseStructure::header, evio::ByteOrder::needToSwap(), evio::BaseStructure::numberDataItems, evio::BaseStructure::rawBytes, evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), and evio::DataType::toString().
updateFloatData()
void evio::BaseStructure::updateFloatData () inherited
If data in this structure was changed by modifying the vector returned from getFloatData(), then this method needs to be called in order to make this object internally consistent.
Exceptions
EvioException if this object corresponds to a different data type.
References evio::BaseStructure::byteOrder, evio::ByteOrder::byteSwap32(), evio::DataType::FLOAT32, evio::BaseStructure::floatData, evio::BaseStructure::header, evio::ByteOrder::needToSwap(), evio::BaseStructure::numberDataItems, evio::BaseStructure::rawBytes, evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), and evio::DataType::toString().
updateIntData()
void evio::BaseStructure::updateIntData () inherited
If data in this structure was changed by modifying the vector returned from getIntData(), then this method needs to be called in order to make this object internally consistent.
Exceptions
EvioException if this object corresponds to a different data type.
References evio::BaseStructure::byteOrder, evio::ByteOrder::byteSwap32(), evio::BaseStructure::header, evio::DataType::INT32, evio::BaseStructure::intData, evio::ByteOrder::needToSwap(), evio::BaseStructure::numberDataItems, evio::BaseStructure::rawBytes, evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), and evio::DataType::toString().
updateLongData()
void evio::BaseStructure::updateLongData () inherited
If data in this structure was changed by modifying the vector returned from getLongData(), then this method needs to be called in order to make this object internally consistent.
Exceptions
EvioException if this object corresponds to a different data type.
References evio::BaseStructure::byteOrder, evio::ByteOrder::byteSwap64(), evio::BaseStructure::header, evio::DataType::LONG64, evio::BaseStructure::longData, evio::ByteOrder::needToSwap(), evio::BaseStructure::numberDataItems, evio::BaseStructure::rawBytes, evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), and evio::DataType::toString().
updateShortData()
void evio::BaseStructure::updateShortData () inherited
If data in this structure was changed by modifying the vector returned from getShortData(), then this method needs to be called in order to make this object internally consistent.
Exceptions
EvioException if this object corresponds to a different data type.
References evio::BaseStructure::byteOrder, evio::ByteOrder::byteSwap16(), evio::BaseStructure::header, evio::ByteOrder::needToSwap(), evio::BaseStructure::numberDataItems, evio::BaseStructure::rawBytes, evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), evio::DataType::SHORT16, evio::BaseStructure::shortData, and evio::DataType::toString().
updateStringData()
void evio::BaseStructure::updateStringData () inherited
If data in this structure was changed by modifying the vector returned from getStringData(), then this method needs to be called in order to make this object internally consistent.
Exceptions
EvioException if this object corresponds to a different data type.
References evio::DataType::CHARSTAR8, evio::BaseStructure::header, evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), evio::BaseStructure::stringsToRawBytes(), and evio::DataType::toString().
updateUCharData()
void evio::BaseStructure::updateUCharData () inherited
If data in this structure was changed by modifying the vector returned from getUCharData(), then this method needs to be called in order to make this object internally consistent.
Exceptions
EvioException if this object corresponds to a different data type.
References evio::BaseStructure::header, evio::BaseStructure::numberDataItems, evio::BaseStructure::rawBytes, evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), evio::DataType::toString(), evio::DataType::UCHAR8, and evio::BaseStructure::ucharData.
updateUIntData()
void evio::BaseStructure::updateUIntData () inherited
If data in this structure was changed by modifying the vector returned from getUIntData(), then this method needs to be called in order to make this object internally consistent.
Exceptions
EvioException if this object corresponds to a different data type.
References evio::BaseStructure::byteOrder, evio::ByteOrder::byteSwap32(), evio::BaseStructure::header, evio::ByteOrder::needToSwap(), evio::BaseStructure::numberDataItems, evio::BaseStructure::rawBytes, evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), evio::DataType::toString(), evio::DataType::UINT32, and evio::BaseStructure::uintData.
updateULongData()
void evio::BaseStructure::updateULongData () inherited
If data in this structure was changed by modifying the vector returned from getULongData(), then this method needs to be called in order to make this object internally consistent.
Exceptions
EvioException if this object corresponds to a different data type.
References evio::BaseStructure::byteOrder, evio::ByteOrder::byteSwap64(), evio::BaseStructure::header, evio::ByteOrder::needToSwap(), evio::BaseStructure::numberDataItems, evio::BaseStructure::rawBytes, evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), evio::DataType::toString(), evio::DataType::ULONG64, and evio::BaseStructure::ulongData.
updateUShortData()
void evio::BaseStructure::updateUShortData () inherited
If data in this structure was changed by modifying the vector returned from getUShortData(), then this method needs to be called in order to make this object internally consistent.
Exceptions
EvioException if this object corresponds to a different data type.
References evio::BaseStructure::byteOrder, evio::ByteOrder::byteSwap16(), evio::BaseStructure::header, evio::ByteOrder::needToSwap(), evio::BaseStructure::numberDataItems, evio::BaseStructure::rawBytes, evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), evio::DataType::toString(), evio::DataType::USHORT16, and evio::BaseStructure::ushortData.
visitAllStructures() [1/2]
void evio::BaseStructure::visitAllStructures (std::shared_ptr< IEvioListener > listener) inherited
Visit all the structures in this structure (including the structure itself – which is considered its own descendant).
This is similar to listening to the event as it is being parsed, but is done to a complete (already) parsed event.
Parameters
listener a listener to notify as each structure is visited.
References evio::BaseStructure::getThis().
Referenced by evio::BaseStructure::getMatchingStructures().
visitAllStructures() [2/2]
void evio::BaseStructure::visitAllStructures (std::shared_ptr< IEvioListener > listener, std::shared_ptr< IEvioFilter > filter) inherited
Visit all the structures in this structure (including the structure itself – which is considered its own descendant) in a depth first manner.
Parameters
listener a listener to notify as each structure is visited.
filter an optional filter that must "accept" structures before they are passed to the listener. If null, all structures are passed. In this way, specific types of structures can be captured.
References evio::BaseStructure::getThis().
write() [1/2]
size_t evio::BaseStructure::write (ByteBuffer & byteBuffer) inherited
Write myself out into a byte buffer with fastest algorithm I could find.
Parameters
byteBuffer the byteBuffer to write to.
Returns
the number of bytes written.
Exceptions
overflow_error if too little space in byteBuffer.
References evio::ByteBuffer::array(), evio::ByteBuffer::arrayOffset(), evio::BaseStructure::getTotalBytes(), evio::ByteBuffer::order(), evio::ByteBuffer::position(), and evio::ByteBuffer::remaining().
write() [2/2]
size_t evio::BaseStructure::write (uint8_t * dest, ByteOrder const & order) inherited
Write myself out to a pointer.
Parameters
dest pointer at which to write evio format data of this bank.
order byte order in which to write.
Returns
the number of bytes written.
References evio::BaseStructure::byteOrder, evio::ByteOrder::byteSwap16(), evio::ByteOrder::byteSwap32(), evio::ByteOrder::byteSwap64(), evio::DataType::CHAR8, evio::BaseStructure::charData, evio::DataType::CHARSTAR8, evio::BaseStructure::children, evio::DataType::COMPOSITE, evio::DataType::DOUBLE64, evio::BaseStructure::doubleData, evio::DataType::FLOAT32, evio::BaseStructure::floatData, evio::BaseStructure::header, evio::DataType::INT32, evio::BaseStructure::intData, evio::BaseStructure::isLeaf(), evio::ByteOrder::isLocalEndian(), evio::DataType::LONG64, evio::BaseStructure::longData, evio::BaseStructure::rawBytes, evio::DataType::SHORT16, evio::BaseStructure::shortData, evio::CompositeData::swapAll(), evio::DataType::UCHAR8, evio::DataType::UINT32, evio::DataType::ULONG64, evio::DataType::UNKNOWN32, and evio::DataType::USHORT16.
writeQuick() [1/2]
size_t evio::BaseStructure::writeQuick (ByteBuffer & dest) inherited
Write myself into a ByteBuffer as evio format data in the data's current byte order given by getByteOrder().
This method is much more efficient than using write(ByteBuffer &).
However, be warned that this method is only useful when this structure has just been read from a file or buffer. Once the user adds data (and does not call the appropriate update method) or children to this structure, this method does NOT produce correct results.
Parameters
dest destination ByteBuffer to contain evio format data of this bank in currently set byte order.
Returns
the number of bytes written.
References evio::BaseStructure::getByteOrder(), evio::BaseStructure::header, evio::ByteBuffer::order(), evio::ByteBuffer::put(), and evio::BaseStructure::rawBytes.
writeQuick() [2/2]
size_t evio::BaseStructure::writeQuick (uint8_t * dest) inherited
Write myself out as evio format data in the data's current byte order given by getByteOrder() at the given pointer.
This method is much more efficient than using write(uint8_t *, ByteOrder const &).
However, be warned that this method is only useful when this structure has just been read from a file or buffer. Once the user adds data (and does not call the appropriate update method) or children to this structure, this method does NOT produce correct results.
Parameters
dest pointer at which to write evio format data of this bank in currently set byte order.
Returns
the number of bytes written.
References evio::BaseStructure::byteOrder, evio::BaseStructure::header, and evio::BaseStructure::rawBytes.
Member Data Documentation
allowsChildren
bool evio::BaseStructure::allowsChildren = true protected inherited
True if the node is able to have children.
Referenced by evio::BaseStructure::BaseStructure(), evio::BaseStructure::getAllowsChildren(), evio::BaseStructure::insert(), evio::BaseStructure::operator=(), and evio::BaseStructure::setAllowsChildren().
badStringFormat
bool evio::BaseStructure::badStringFormat = false protected inherited
True if char data has non-ascii or non-printable characters, or has too little data to be in proper format.
Referenced by evio::BaseStructure::unpackRawBytesToStrings().
byteOrder
ByteOrder evio::BaseStructure::byteOrder {ByteOrder::ENDIAN_LOCAL} protected inherited
Endianness of the raw data if appropriate.
Initialize to local endian.
Referenced by evio::BaseStructure::getByteOrder(), evio::BaseStructure::getCompositeData(), evio::BaseStructure::needSwap(), evio::BaseStructure::setByteOrder(), evio::BaseStructure::updateCompositeData(), evio::BaseStructure::updateDoubleData(), evio::BaseStructure::updateFloatData(), evio::BaseStructure::updateIntData(), evio::BaseStructure::updateLongData(), evio::BaseStructure::updateShortData(), evio::BaseStructure::updateUIntData(), evio::BaseStructure::updateULongData(), evio::BaseStructure::updateUShortData(), evio::BaseStructure::write(), and evio::BaseStructure::writeQuick().
charData
std::vector<signed char> evio::BaseStructure::charData protected inherited
Used if raw data should be interpreted as signed chars.
The reason rawBytes is not used directly is because it may be padded and it may not, depending on whether this object was created by EvioReader or by EventBuilder, etc., etc. We don't want to return rawBytes when a user calls getCharData() if there are padding bytes in it.
Referenced by evio::BaseStructure::getCharData(), evio::BaseStructure::updateCharData(), and evio::BaseStructure::write().
children
std::vector<std::shared_ptr<BaseStructure> > evio::BaseStructure::children protected inherited
Array of children, may be null if this node has no children.
Referenced by evio::BaseStructure::BaseStructure(), evio::BaseStructure::childrenBegin(), evio::BaseStructure::childrenEnd(), evio::BaseStructure::getChildAt(), evio::BaseStructure::getChildCount(), evio::BaseStructure::getChildren(), evio::BaseStructure::getIndex(), evio::BaseStructure::insert(), evio::BaseStructure::operator=(), evio::BaseStructure::remove(), evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::toString(), evio::EvioEvent::toString(), evio::BaseStructure::transform(), evio::BaseStructure::treeToString(), and evio::BaseStructure::write().
compositeData
std::vector<std::shared_ptr<CompositeData> > evio::BaseStructure::compositeData protected inherited
Used if raw data should be interpreted as composite type.
Referenced by evio::BaseStructure::getCompositeData(), evio::BaseStructure::getNumberDataItems(), and evio::BaseStructure::updateCompositeData().
doubleData
std::vector<double> evio::BaseStructure::doubleData protected inherited
Used if raw data should be interpreted as doubles.
Referenced by evio::BaseStructure::getDoubleData(), evio::BaseStructure::updateDoubleData(), and evio::BaseStructure::write().
floatData
std::vector<float> evio::BaseStructure::floatData protected inherited
Used if raw data should be interpreted as floats.
Referenced by evio::BaseStructure::getFloatData(), evio::BaseStructure::updateFloatData(), and evio::BaseStructure::write().
header
std::shared_ptr<BaseStructureHeader> evio::BaseStructure::header protected inherited
Holds the header of the bank as a shared pointer.
Referenced by evio::BaseStructure::BaseStructure(), evio::BaseStructure::dataLength(), evio::BaseStructure::getCharData(), evio::BaseStructure::getCompositeData(), evio::BaseStructure::getDoubleData(), evio::BaseStructure::getFloatData(), evio::BaseStructure::getHeader(), evio::BaseStructure::getIntData(), evio::BaseStructure::getLongData(), evio::BaseStructure::getNumberDataItems(), evio::BaseStructure::getShortData(), evio::BaseStructure::getStringData(), evio::BaseStructure::getTotalBytes(), evio::BaseStructure::getUCharData(), evio::BaseStructure::getUIntData(), evio::BaseStructure::getULongData(), evio::BaseStructure::getUShortData(), evio::BaseStructure::isContainer(), evio::BaseStructure::operator=(), evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::stringsToRawBytes(), evio::BaseStructure::toString(), evio::EvioEvent::toString(), evio::BaseStructure::updateCharData(), evio::BaseStructure::updateCompositeData(), evio::BaseStructure::updateDoubleData(), evio::BaseStructure::updateFloatData(), evio::BaseStructure::updateIntData(), evio::BaseStructure::updateLongData(), evio::BaseStructure::updateShortData(), evio::BaseStructure::updateStringData(), evio::BaseStructure::updateUCharData(), evio::BaseStructure::updateUIntData(), evio::BaseStructure::updateULongData(), evio::BaseStructure::updateUShortData(), evio::BaseStructure::write(), and evio::BaseStructure::writeQuick().
intData
std::vector<int32_t> evio::BaseStructure::intData protected inherited
Used if raw data should be interpreted as ints.
Referenced by evio::BaseStructure::getIntData(), evio::BaseStructure::updateIntData(), and evio::BaseStructure::write().
lengthsUpToDate
bool evio::BaseStructure::lengthsUpToDate = false protected inherited
Keep track of whether header length data is up-to-date or not.
Referenced by evio::BaseStructure::BaseStructure(), evio::BaseStructure::getLengthsUpToDate(), evio::BaseStructure::operator=(), evio::BaseStructure::setAllHeaderLengths(), evio::BaseStructure::setLengthsUpToDate(), and evio::BaseStructure::transform().
longData
std::vector<int64_t> evio::BaseStructure::longData protected inherited
Used if raw data should be interpreted as longs.
Referenced by evio::BaseStructure::getLongData(), evio::BaseStructure::updateLongData(), and evio::BaseStructure::write().
numberDataItems
size_t evio::BaseStructure::numberDataItems = 0 protected inherited
The number of stored data items like number of banks, ints, floats, etc.
(not the size in ints or bytes). Some items may be padded such as shorts and bytes. This will tell the meaningful number of such data items. In other words, no padding is included. In the case of containers, returns number of bytes not in header.
Referenced by evio::BaseStructure::getNumberDataItems(), evio::BaseStructure::stringsToRawBytes(), evio::BaseStructure::updateCharData(), evio::BaseStructure::updateCompositeData(), evio::BaseStructure::updateDoubleData(), evio::BaseStructure::updateFloatData(), evio::BaseStructure::updateIntData(), evio::BaseStructure::updateLongData(), evio::BaseStructure::updateShortData(), evio::BaseStructure::updateUCharData(), evio::BaseStructure::updateUIntData(), evio::BaseStructure::updateULongData(), and evio::BaseStructure::updateUShortData().
parent
std::shared_ptr<BaseStructure> evio::BaseStructure::parent = nullptr protected inherited
This node's parent, or null if this node has no parent.
Referenced by evio::BaseStructure::BaseStructure(), evio::BaseStructure::getParent(), evio::BaseStructure::operator=(), evio::BaseStructure::setLengthsUpToDate(), and evio::BaseStructure::setParent().
rawBytes
std::vector<uint8_t> evio::BaseStructure::rawBytes protected inherited
The raw data of the structure.
May contain padding.
Referenced by evio::BaseStructure::dataLength(), evio::BaseStructure::getCharData(), evio::BaseStructure::getCompositeData(), evio::BaseStructure::getDoubleData(), evio::BaseStructure::getFloatData(), evio::BaseStructure::getIntData(), evio::BaseStructure::getLongData(), evio::BaseStructure::getNumberDataItems(), evio::BaseStructure::getRawBytes(), evio::BaseStructure::getShortData(), evio::BaseStructure::getStringData(), evio::BaseStructure::getUCharData(), evio::BaseStructure::getUIntData(), evio::BaseStructure::getULongData(), evio::BaseStructure::getUShortData(), evio::BaseStructure::setRawBytes(), evio::BaseStructure::stringsToRawBytes(), evio::BaseStructure::toString(), evio::EvioEvent::toString(), evio::BaseStructure::unpackRawBytesToStrings(), evio::BaseStructure::updateCharData(), evio::BaseStructure::updateCompositeData(), evio::BaseStructure::updateDoubleData(), evio::BaseStructure::updateFloatData(), evio::BaseStructure::updateIntData(), evio::BaseStructure::updateLongData(), evio::BaseStructure::updateShortData(), evio::BaseStructure::updateUCharData(), evio::BaseStructure::updateUIntData(), evio::BaseStructure::updateULongData(), evio::BaseStructure::updateUShortData(), evio::BaseStructure::write(), and evio::BaseStructure::writeQuick().
shortData
std::vector<int16_t> evio::BaseStructure::shortData protected inherited
Used if raw data should be interpreted as shorts.
Referenced by evio::BaseStructure::getShortData(), evio::BaseStructure::updateShortData(), and evio::BaseStructure::write().
stringEnd
int evio::BaseStructure::stringEnd = 0 protected inherited
Keep track of end of the last string added to stringData (including null but not padding).
Referenced by evio::BaseStructure::unpackRawBytesToStrings().
stringList
std::vector<std::string > evio::BaseStructure::stringList protected inherited
Used if raw data should be interpreted as a string.
Referenced by evio::BaseStructure::getStringData(), evio::BaseStructure::stringsToRawBytes(), and evio::BaseStructure::unpackRawBytesToStrings().
ucharData
std::vector<unsigned char> evio::BaseStructure::ucharData protected inherited
Used if raw data should be interpreted as unsigned chars.
Referenced by evio::BaseStructure::getUCharData(), and evio::BaseStructure::updateUCharData().
uintData
std::vector<uint32_t> evio::BaseStructure::uintData protected inherited
Used if raw data should be interpreted as unsigned ints.
Referenced by evio::BaseStructure::getUIntData(), and evio::BaseStructure::updateUIntData().
ulongData
std::vector<uint64_t> evio::BaseStructure::ulongData protected inherited
Used if raw data should be interpreted as unsigned longs.
Referenced by evio::BaseStructure::getULongData(), and evio::BaseStructure::updateULongData().
ushortData
std::vector<uint16_t> evio::BaseStructure::ushortData protected inherited
Used if raw data should be interpreted as unsigned shorts.
Referenced by evio::BaseStructure::getUShortData(), and evio::BaseStructure::updateUShortData().
The documentation for this class was generated from the following file:
EvioTagSegment.h