evio: FORTRAN routines
FORTRAN routines
These routines handle limited evio operations for FORTRAN programs.
Functions
int evopen_ (char *filename, char *flags, int *handle, int fnlen, int flen)
Fortran interface to evOpen.
int evread_ (int *handle, uint32_t *buffer, uint32_t *buflen)
Fortran interface to evRead.
int evwrite_ (int *handle, const uint32_t *buffer)
Fortran interface to evWrite.
int evclose_ (int *handle)
Fortran interface to evClose.
int evioctl_ (int *handle, char *request, void *argp, int reqlen)
Fortran interface to evIoctl.
Detailed Description
These routines handle limited evio operations for FORTRAN programs.
Function Documentation
evclose_()
int evclose_ (int * handle)
Fortran interface to evClose.
References evClose().
evioctl_()
int evioctl_ (int * handle, char * request, void * argp, int reqlen)
Fortran interface to evIoctl.
References evIoctl().
evopen_()
int evopen_ (char * filename, char * flags, int * handle, int fnlen, int flen)
Fortran interface to evOpen.
References evOpen().
evread_()
int evread_ (int * handle, uint32_t * buffer, uint32_t * buflen)
Fortran interface to evRead.
References evRead().
evwrite_()
int evwrite_ (int * handle, const uint32_t * buffer)
Fortran interface to evWrite.
References evWrite().