evio: evio::evioBankIndex Class Reference
evio::evioBankIndex Class Reference
Creates bank index for serialized event.
#include <evioBankIndex.hxx>
Public Member Functions
evioBankIndex (int maxDepth=0)
Constructor.
evioBankIndex (const uint32_t *buffer, int maxDepth=0)
Constructor from buffer.
virtual ~evioBankIndex ()=default
bool parseBuffer (const uint32_t *buffer, int maxDepth)
Indexes buffer and fills map.
bool tagNumExists (const evioDictEntry &tn) const
True if evioDictEntry is in map at least once.
int tagNumCount (const evioDictEntry &tn) const
Returns count of evioDictEntry in map.
bankIndexRange getRange (const evioDictEntry &tn) const
Returns pair of iterators defining range of equal keys in tagNumMap.
bankIndex getBankIndex (const evioDictEntry &tn) const
Returns bankIndex given evioDictEntry, throws exception if no entry found.
int getMaxDepth ()
template<typename T >
const T * getData (const evioDictEntry &tn, int *pLen)
Returns length and pointer to data, NULL if container bank, bad evioDictEntry or wrong data type.
template<typename T >
const T * getData (const bankIndex &bi, int *pLen)
Returns length and pointer to data, assumes valid bankIndex.
Public Attributes
bankIndexMap tagNumMap
Holds index to one or more banks having tag/num.
Detailed Description
Creates bank index for serialized event.
Note that a given tag/num may appear more than once in event and map.
Constructor & Destructor Documentation
evioBankIndex() [1/2]
evioBankIndex::evioBankIndex (int maxDepth = 0)
Constructor.
evioBankIndex() [2/2]
evioBankIndex::evioBankIndex (const uint32_t * buffer, int maxDepth = 0)
Constructor from buffer.
Parameters
buffer Event buffer to index
References parseBuffer().
~evioBankIndex()
virtual evio::evioBankIndex::~evioBankIndex () virtual default
Member Function Documentation
getBankIndex()
bankIndex evioBankIndex::getBankIndex (const evioDictEntry & tn) const
Returns bankIndex given evioDictEntry, throws exception if no entry found.
Parameters
tn evioDictEntry
Returns
bankIndex for evioDictEntry
References tagNumMap.
getData() [1/2]
template<typename T > const T* evio::evioBankIndex::getData (const bankIndex & bi, int * pLen) inline
Returns length and pointer to data, assumes valid bankIndex.
Parameters
bi bankIndex
pLen Pointer to int to receive data length, set to 0 for bad type
Returns
Pointer to data, NULL on bad type
References evio::bankIndex::contentType, evio::bankIndex::data, and evio::bankIndex::dataLength.
getData() [2/2]
template<typename T > const T* evio::evioBankIndex::getData (const evioDictEntry & tn, int * pLen) inline
Returns length and pointer to data, NULL if container bank, bad evioDictEntry or wrong data type.
Parameters
tn evioDictEntry
pLen Pointer to int to receive data length, set to 0 upon error
Returns
Pointer to data, NULL on error
getMaxDepth()
int evio::evioBankIndex::getMaxDepth ()
getRange()
bankIndexRange evioBankIndex::getRange (const evioDictEntry & tn) const
Returns pair of iterators defining range of equal keys in tagNumMap.
Parameters
tn evioDictEntry
Returns
Pair of iterators defining range
References tagNumMap.
parseBuffer()
bool evioBankIndex::parseBuffer (const uint32_t * buffer, int maxDepth)
Indexes buffer and fills map.
Parameters
buffer Buffer containing serialized event
Returns
true if indexing succeeded
References evio::evioStreamParser::parse().
Referenced by evioBankIndex().
tagNumCount()
int evioBankIndex::tagNumCount (const evioDictEntry & tn) const
Returns count of evioDictEntry in map.
Parameters
tn evioDictEntry
Returns
Count of evioDictEntry in map.
References tagNumMap.
tagNumExists()
bool evioBankIndex::tagNumExists (const evioDictEntry & tn) const
True if evioDictEntry is in map at least once.
Parameters
tn evioDictEntry
Returns
true if evioDictEntry is in map
References tagNumMap.
Member Data Documentation
tagNumMap
bankIndexMap evio::evioBankIndex::tagNumMap
Holds index to one or more banks having tag/num.
Referenced by getBankIndex(), getRange(), tagNumCount(), and tagNumExists().
The documentation for this class was generated from the following files:
evioBankIndex.hxx
evioBankIndex.cc