evio: evio::Compressor Class Reference
evio::Compressor Class Reference
Singleton class used to provide data compression and decompression in a variety of formats.
#include <Compressor.h>
Public Types
enum CompressionType { UNCOMPRESSED = 0, LZ4, LZ4_BEST, GZIP }
Enum of supported data compression types.
Static Public Member Functions
static Compressor & getInstance ()
Get an instance of this singleton class.
static CompressionType toCompressionType (uint32_t type)
Method to convert an integer to a CompressionType object.
static int getMaxCompressedLength (CompressionType compressionType, uint32_t uncompressedLength)
Returns the maximum number of bytes needed to compress the given length of uncompressed data.
static int compressLZ4 (ByteBuffer &src, int srcSize, ByteBuffer &dst, int maxSize)
Fastest LZ4 compression.
static int compressLZ4 (uint8_t *src, int srcOff, int srcSize, uint8_t *dst, int dstOff, int maxSize)
Fastest LZ4 compression.
static int compressLZ4 (ByteBuffer &src, int srcOff, int srcSize, ByteBuffer &dst, int dstOff, int maxSize)
Fastest LZ4 compression.
static int compressLZ4Best (ByteBuffer &src, int srcSize, ByteBuffer &dst, int maxSize)
Highest LZ4 compression.
static int compressLZ4Best (uint8_t *src, int srcOff, int srcSize, uint8_t *dst, int dstOff, int maxSize)
Highest LZ4 compression.
static int compressLZ4Best (ByteBuffer &src, int srcOff, int srcSize, ByteBuffer &dst, int dstOff, int maxSize)
Highest LZ4 compression.
static int uncompressLZ4 (ByteBuffer &src, int srcSize, ByteBuffer &dst)
LZ4 decompression.
static int uncompressLZ4 (ByteBuffer &src, int srcOff, int srcSize, ByteBuffer &dst)
LZ4 decompression.
static int uncompressLZ4 (ByteBuffer &src, int srcOff, int srcSize, ByteBuffer &dst, int dstOff)
LZ4 decompression.
static int uncompressLZ4 (uint8_t *src, int srcOff, int srcSize, uint8_t *dst, int dstOff, int dstCapacity)
LZ4 decompression.
Detailed Description
Singleton class used to provide data compression and decompression in a variety of formats.
This class in NOT thread safe when using the gzip deflating and inflating routines.
Date
04/29/2019
Author
timmer
Member Enumeration Documentation
CompressionType
enum evio::Compressor::CompressionType
Enum of supported data compression types.
Enumerator
UNCOMPRESSED
LZ4
LZ4_BEST
GZIP
Member Function Documentation
compressLZ4() [1/3]
int evio::Compressor::compressLZ4 (ByteBuffer & src, int srcOff, int srcSize, ByteBuffer & dst, int dstOff, int maxSize) static
Fastest LZ4 compression.
Returns length of compressed data in bytes.
Parameters
src source of uncompressed data.
srcOff start offset in src regardless of position.
srcSize number of bytes to compress.
dst destination array.
dstOff start offset in dst regardless of position.
maxSize maximum number of bytes to write in dst.
Returns
length of compressed data in bytes.
Exceptions
EvioException if maxSize < max # of compressed bytes or compression failed.
References evio::ByteBuffer::array().
compressLZ4() [2/3]
int evio::Compressor::compressLZ4 (ByteBuffer & src, int srcSize, ByteBuffer & dst, int maxSize) static
Fastest LZ4 compression.
Returns length of compressed data in bytes.
Parameters
src source of uncompressed data from position.
srcSize number of bytes to compress.
dst destination buffer from position.
maxSize maximum number of bytes to write in dst.
Returns
length of compressed data in bytes.
Exceptions
EvioException if maxSize < max # of compressed bytes or compression failed.
References evio::ByteBuffer::array(), and evio::ByteBuffer::position().
Referenced by evio::RecordOutput::build().
compressLZ4() [3/3]
int evio::Compressor::compressLZ4 (uint8_t * src, int srcOff, int srcSize, uint8_t * dst, int dstOff, int maxSize) static
Fastest LZ4 compression.
Returns length of compressed data in bytes.
Parameters
src source of uncompressed data.
srcOff start offset in src.
srcSize number of bytes to compress.
dst destination array.
dstOff start offset in dst.
maxSize maximum number of bytes to write in dst.
Returns
length of compressed data in bytes.
Exceptions
EvioException if maxSize < max # of compressed bytes or compression failed.
compressLZ4Best() [1/3]
int evio::Compressor::compressLZ4Best (ByteBuffer & src, int srcOff, int srcSize, ByteBuffer & dst, int dstOff, int maxSize) static
Highest LZ4 compression.
Returns length of compressed data in bytes.
Parameters
src source of uncompressed data.
srcOff start offset in src.
srcSize number of bytes to compress.
dst destination array.
dstOff start offset in dst.
maxSize maximum number of bytes to write in dst.
Returns
length of compressed data in bytes.
Exceptions
EvioException if maxSize < max # of compressed bytes or compression failed.
References evio::ByteBuffer::array().
compressLZ4Best() [2/3]
int evio::Compressor::compressLZ4Best (ByteBuffer & src, int srcSize, ByteBuffer & dst, int maxSize) static
Highest LZ4 compression.
Returns length of compressed data in bytes.
Parameters
src source of uncompressed data starting at position.
srcSize number of bytes to compress.
dst destination buffer starting at position.
maxSize maximum number of bytes to write in dst.
Returns
length of compressed data in bytes.
Exceptions
EvioException if maxSize < max # of compressed bytes or compression failed.
References evio::ByteBuffer::array(), and evio::ByteBuffer::position().
Referenced by evio::RecordOutput::build().
compressLZ4Best() [3/3]
int evio::Compressor::compressLZ4Best (uint8_t * src, int srcOff, int srcSize, uint8_t * dst, int dstOff, int maxSize) static
Highest LZ4 compression.
Returns length of compressed data in bytes.
Parameters
src source of uncompressed data.
srcOff start offset in src.
srcSize number of bytes to compress.
dst destination array.
dstOff start offset in dst.
maxSize maximum number of bytes to write in dst.
Returns
length of compressed data in bytes.
Exceptions
EvioException if maxSize < max # of compressed bytes or compression failed.
getInstance()
static Compressor& evio::Compressor::getInstance () inline static
Get an instance of this singleton class.
Returns
an instance of this singleton class.
Referenced by evio::RecordOutput::build(), evio::RecordInput::readRecord(), and evio::RecordInput::uncompressRecord().
getMaxCompressedLength()
int evio::Compressor::getMaxCompressedLength (CompressionType compressionType, uint32_t uncompressedLength) static
Returns the maximum number of bytes needed to compress the given length of uncompressed data.
Depends on compression type. Unknown for gzip.
Parameters
compressionType type of data compression to do (0=none, 1=lz4 fast, 2=lz4 best, 3=gzip). Default to none.
uncompressedLength uncompressed data length in bytes.
Returns
maximum compressed length in bytes or -1 if unknown.
References GZIP, LZ4, LZ4_BEST, and UNCOMPRESSED.
toCompressionType()
Compressor::CompressionType evio::Compressor::toCompressionType (uint32_t type) static
Method to convert an integer to a CompressionType object.
Parameters
type integer to convert.
Returns
corresponding CompressionType object.
References GZIP, LZ4, LZ4_BEST, and UNCOMPRESSED.
uncompressLZ4() [1/4]
int evio::Compressor::uncompressLZ4 (ByteBuffer & src, int srcOff, int srcSize, ByteBuffer & dst) static
LZ4 decompression.
Returns original length of decompressed data in bytes.
Parameters
src source of compressed data.
srcOff start offset in src.
srcSize number of compressed bytes.
dst destination array.
Returns
original (uncompressed) input size.
Exceptions
EvioException if destination buffer is too small to hold uncompressed data or source data is malformed.
References evio::ByteBuffer::array(), evio::ByteBuffer::limit(), evio::ByteBuffer::position(), and evio::ByteBuffer::remaining().
uncompressLZ4() [2/4]
int evio::Compressor::uncompressLZ4 (ByteBuffer & src, int srcOff, int srcSize, ByteBuffer & dst, int dstOff) static
LZ4 decompression.
Returns original length of decompressed data in bytes.
Parameters
src source of compressed data.
srcOff start offset in src.
srcSize number of compressed bytes.
dst destination array.
dstOff start offset in dst.
Returns
original (uncompressed) input size.
Exceptions
EvioException if destination buffer is too small to hold uncompressed data or source data is malformed.
References evio::ByteBuffer::array(), evio::ByteBuffer::limit(), and evio::ByteBuffer::remaining().
uncompressLZ4() [3/4]
int evio::Compressor::uncompressLZ4 (ByteBuffer & src, int srcSize, ByteBuffer & dst) static
LZ4 decompression.
Returns original length of decompressed data in bytes.
Parameters
src source of compressed data.
srcSize number of compressed bytes.
dst destination array.
Returns
original (uncompressed) input size.
Exceptions
EvioException if destination buffer is too small to hold uncompressed data or source data is malformed.
References evio::ByteBuffer::position().
Referenced by evio::RecordInput::readRecord(), and evio::RecordInput::uncompressRecord().
uncompressLZ4() [4/4]
int evio::Compressor::uncompressLZ4 (uint8_t * src, int srcOff, int srcSize, uint8_t * dst, int dstOff, int dstCapacity) static
LZ4 decompression.
Returns original length of decompressed data in bytes.
Parameters
src source of compressed data.
srcOff start offset in src.
srcSize number of compressed bytes.
dst destination array.
dstOff start offset in dst.
dstCapacity size of destination buffer in bytes, which must be already allocated.
Returns
original (uncompressed) input size.
Exceptions
EvioException if uncompressed data bytes > dstCapacity or source data is malformed.
The documentation for this class was generated from the following files:
Compressor.h
Compressor.cpp