# Automatic generation of doxygen and javadoc files for Evio's C, C++, and Java code
# on the evio-5.2 branch which will be copied and checked into the gh-pages branch.
name: Documentation generation CI

on:
  push:
    branches: [ evio-5.2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # checkout the evio-5.2 branch
      - uses: actions/checkout@v2

      # generate the C doxygen files
      - name: Doxygen Action C
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          working-directory: '.'
          doxyfile-path: 'doc/doxygen/DoxyfileC'

      # generate the C++ doxygen files
      - name: Doxygen Action C++
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          working-directory: '.'
          doxyfile-path: 'doc/doxygen/DoxyfileCC'

      # generate the javadoc files
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Javadoc Action
        run: ant -noinput -buildfile build.xml javadoc

      # clean up the javadoc files including removing timestamps. OPTIONAL.
      - name: Tidy up the javadocs
        id: tidy
        uses: cicirello/javadoc-cleanup@v1
        with:
          path-to-root: doc/javadoc

      - run: ls doc/javadoc

      # store the doc files
      - name: Upload Output Directory
        uses: actions/upload-artifact@v2
        with:
          name: evio-doc-files
          path: doc
          retention-days: 1

  copy:

    runs-on: ubuntu-latest
    needs: build

    steps:
      # checkout the gh-pages branch
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      # download the doc files, most of which are generated above
      - name: Download Output Directory
        uses: actions/download-artifact@v2
        with:
          name: evio-doc-files
          path: doc-5.2

      # add, commit and push to gh-pages
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Carl Timmer
          author_email: timmer@jlab.org
          message: 'Update docs'
          branch: gh-pages
          add: '["doc-5.2/doxygen/C/html/*", "doc-5.2/doxygen/CC/html/*", "doc-5.2/javadoc/", "doc-5.2/users_guide/evio_Users_Guide.pdf"]'
