name: Java Tests (EVIO-6)

on:
  pull_request:
    branches: [ main ]

jobs:
  java_test:
    name: Run JUnit Tests
    runs-on: ubuntu-latest
    container:
      image: maven:3.9-eclipse-temurin-17-alpine

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Uncomment to set up Java and Maven manually, if desired
      # # (and probably comment out the container image above)
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: temurin
      #     java-version: 17
      # Install maven by hand (if not in container image)
      # - name: Maven Setup
      #   run: sudo apt-get update && apt-get install -y maven

      - name: Build and run tests
        run: mvn --batch-mode test
